package cli

import (
	"bytes"
	"context"
	"testing"

	"github.com/stretchr/testify/require"
)

func Test_CommandFlows_execute_read_and_write_commands(t *testing.T) {
	tests := []struct {
		name     string
		args     []string
		contains string
		fake     commandFlowFakeClient
	}{
		{name: "target", args: []string{"target"}, contains: "org org-id team LIT/team-id project project-id confirmed true"},
		{name: "doctor", args: []string{"doctor"}, contains: "config ok\n token set\n target confirmed LIT/team-id project project-id"},
		{name: "whoami", args: []string{"whoami"}, contains: "Omer <omer@example.com>"},
		{name: "application info", args: []string{"application", "info", "app-client-id"}, contains: "app-id Demo App by Kyanite", fake: commandFlowFakeClient{expectedApplicationClientID: "app-client-id"}},
		{name: "agent activity list", args: []string{"agent-activity", "list", "--limit", "1"}, contains: "agent-activity-id session agent-session-id [action] signal continue"},
		{name: "agent activity get", args: []string{"agent-activity", "get", "agent-activity-id"}, contains: "agent-activity-id session agent-session-id [action] signal continue"},
		{name: "agent skill list", args: []string{"agent-skill", "list", "--limit", "1"}, contains: "agent-skill-id Triage Helper shared true recent 3"},
		{name: "agent skill get", args: []string{"agent-skill", "get", "agent-skill-id"}, contains: "agent-skill-id Triage Helper shared true recent 3"},
		{name: "agent session list", args: []string{"agent-session", "list", "--limit", "1"}, contains: "agent-session-id session-slug [active] LIT-1"},
		{name: "agent session get", args: []string{"agent-session", "get", "agent-session-id"}, contains: "agent-session-id session-slug [active] LIT-1"},
		{name: "external user list", args: []string{"external-user", "list", "--limit", "1"}, contains: "external-user-id External User @external last_seen 2026-06-19T12:00:00Z"},
		{name: "external user get", args: []string{"external-user", "get", "external-user-id"}, contains: "external-user-id External User @external last_seen 2026-06-19T12:00:00Z"},
		{name: "audit entry types", args: []string{"audit-entry", "types"}, contains: "user_login User logged in"},
		{name: "organization exists", args: []string{"organization", "exists", "kyanite"}, contains: "kyanite exists true success true", fake: commandFlowFakeClient{expectedOrganizationURLKey: "kyanite"}},
		{name: "organization labels", args: []string{"organization", "labels", "--limit", "1"}, contains: "label-id Bug #ff0000"},
		{name: "organization project labels", args: []string{"organization", "project-labels", "--limit", "1"}, contains: "project-label-id Roadmap #f2c94c"},
		{name: "organization teams", args: []string{"organization", "teams", "--limit", "1"}, contains: "team-id LIT linctl"},
		{name: "organization templates", args: []string{"organization", "templates", "--limit", "1"}, contains: "template-id Bug report [issue] team LIT"},
		{name: "organization users", args: []string{"organization", "users", "--limit", "1"}, contains: "user-id Omer <omer@example.com>"},
		{name: "rate limit status", args: []string{"rate-limit", "status"}, contains: "api api-key\ncomplexity remaining 900/1000 reset 1720000000000"},
		{name: "notification list", args: []string{"notification", "list", "--limit", "1"}, contains: "notification-id issueMention [mentions] Mentioned you"},
		{name: "notification get", args: []string{"notification", "get", "notification-id"}, contains: "notification-id issueMention [mentions] Mentioned you"},
		{name: "notification subscription list", args: []string{"notification", "subscription", "list", "--limit", "1"}, contains: "notification-subscription-id project Roadmap active true"},
		{name: "notification subscription get", args: []string{"notification", "subscription", "get", "notification-subscription-id"}, contains: "notification-subscription-id project Roadmap active true"},
		{name: "triage responsibility list", args: []string{"triage-responsibility", "list", "--limit", "1"}, contains: "triage-responsibility-id team LIT action notify current Omer"},
		{name: "triage responsibility get", args: []string{"triage-responsibility", "get", "triage-responsibility-id"}, contains: "triage-responsibility-id team LIT action notify current Omer"},
		{name: "triage responsibility manual selection", args: []string{"triage-responsibility", "manual-selection", "triage-responsibility-id"}, contains: "triage-responsibility-id manual users user-id,other-user-id"},
		{name: "SLA configuration list", args: []string{"sla-configuration", "list", "team-id"}, contains: "sla-configuration-id First response sla 3600000 type all removes false"},
		{name: "semantic search", args: []string{"semantic-search", "agent search", "--limit", "2"}, contains: "issue issue-id LIT-3 Search result", fake: commandFlowFakeClient{expectedSemanticSearchQuery: "agent search"}},
		{name: "search documents", args: []string{"search", "documents", "agent search", "--limit", "1"}, contains: "search-document-id Search spec [team]", fake: commandFlowFakeClient{expectedTypedSearchTerm: "agent search"}},
		{name: "search issues", args: []string{"search", "issues", "agent search", "--limit", "1"}, contains: "LIT-30 Search issue [Todo]", fake: commandFlowFakeClient{expectedTypedSearchTerm: "agent search"}},
		{name: "search projects", args: []string{"search", "projects", "agent search", "--limit", "1"}, contains: "search-project-id Search project [Backlog]", fake: commandFlowFakeClient{expectedTypedSearchTerm: "agent search"}},
		{name: "release pipeline list", args: []string{"release-pipeline", "list", "--limit", "1"}, contains: "release-pipeline-id Production production releases 4"},
		{name: "release pipeline get", args: []string{"release-pipeline", "get", "release-pipeline-id"}, contains: "release-pipeline-id Production production releases 4"},
		{name: "release pipeline releases", args: []string{"release-pipeline", "releases", "release-pipeline-id", "--limit", "1"}, contains: "release-id Mobile 1.2.3 [v1.2.3] pipeline Production stage Started issues 3"},
		{name: "release pipeline stages", args: []string{"release-pipeline", "stages", "release-pipeline-id", "--limit", "1"}, contains: "release-stage-id Started [started] pipeline Production"},
		{name: "release pipeline teams", args: []string{"release-pipeline", "teams", "release-pipeline-id", "--limit", "1"}, contains: "team-id LIT linctl"},
		{name: "release stage list", args: []string{"release-stage", "list", "--limit", "1"}, contains: "release-stage-id Started [started] pipeline Production"},
		{name: "release stage get", args: []string{"release-stage", "get", "release-stage-id"}, contains: "release-stage-id Started [started] pipeline Production"},
		{name: "release stage releases", args: []string{"release-stage", "releases", "release-stage-id", "--limit", "1"}, contains: "release-id Mobile 1.2.3 [v1.2.3] pipeline Production stage Started issues 3"},
		{name: "release list", args: []string{"release", "list", "--limit", "1"}, contains: "release-id Mobile 1.2.3 [v1.2.3] pipeline Production stage Started issues 3"},
		{name: "release search", args: []string{"release", "search", "mobile", "--limit", "1"}, contains: "release-id Mobile 1.2.3 [v1.2.3] pipeline Production stage Started issues 3", fake: commandFlowFakeClient{expectedReleaseSearchTerm: "mobile"}},
		{name: "release get", args: []string{"release", "get", "release-id"}, contains: "release-id Mobile 1.2.3 [v1.2.3] pipeline Production stage Started issues 3"},
		{name: "release history", args: []string{"release", "history", "release-id", "--limit", "1"}, contains: "release-history-id release release-id entries 1"},
		{name: "release documents", args: []string{"release", "documents", "release-id", "--limit", "1"}, contains: "document-id Spec [project]"},
		{name: "release issues", args: []string{"release", "issues", "release-id", "--limit", "1"}, contains: "LIT-1 Detail issue [Todo]"},
		{name: "release links", args: []string{"release", "links", "release-id", "--limit", "1"}, contains: "release-link-id Runbook https://example.com/runbook order 1.5"},
		{name: "external link get", args: []string{"external-link", "get", "release-link-id"}, contains: "release-link-id Runbook https://example.com/runbook order 1.5"},
		{name: "release note list", args: []string{"release-note", "list", "--limit", "1"}, contains: "release-note-id Launch notes pipeline Production releases 2"},
		{name: "release note get", args: []string{"release-note", "get", "release-note-id"}, contains: "release-note-id Launch notes pipeline Production releases 2"},
		{name: "issue to release list", args: []string{"issue-to-release", "list", "--limit", "1"}, contains: "issue-to-release-id issue issue-id -> release release-id"},
		{name: "issue to release get", args: []string{"issue-to-release", "get", "issue-to-release-id"}, contains: "issue-to-release-id issue issue-id -> release release-id"},
		{name: "next dry run", args: []string{"next", "--dry-run"}, contains: "LIT-27 Next issue [Todo]"},
		{name: "issue list", args: []string{"issue", "list", "--limit", "1"}, contains: "LIT-1 Listed issue [Todo]"},
		{name: "issue list state filter", args: []string{"issue", "list", "--state", "started", "--limit", "1"}, contains: "LIT-2 Started issue [Started]", fake: commandFlowFakeClient{expectedStateType: "started"}},
		{name: "issue list project filter", args: []string{"issue", "list", "--project", "project-id", "--limit", "1"}, contains: "LIT-4 Project issue [Todo]", fake: commandFlowFakeClient{expectedProjectID: "project-id"}},
		{name: "issue list mine filter", args: []string{"issue", "list", "--mine", "--limit", "1"}, contains: "LIT-5 Mine issue [Todo]", fake: commandFlowFakeClient{expectedAssigneeID: "user-id"}},
		{name: "issue list assignee filter", args: []string{"issue", "list", "--assignee", "assignee-id", "--limit", "1"}, contains: "LIT-6 Assigned issue [Todo]", fake: commandFlowFakeClient{expectedAssigneeID: "assignee-id"}},
		{name: "issue list label filter", args: []string{"issue", "list", "--label", "label-id", "--limit", "1"}, contains: "LIT-7 Labeled issue [Todo]", fake: commandFlowFakeClient{expectedLabelID: "label-id"}},
		{name: "issue list cycle filter", args: []string{"issue", "list", "--cycle", "cycle-id", "--limit", "1"}, contains: "LIT-8 Cycle issue [Todo]", fake: commandFlowFakeClient{expectedCycleID: "cycle-id"}},
		{name: "issue list created-after filter", args: []string{"issue", "list", "--created-after", "2026-06-01", "--limit", "1"}, contains: "LIT-9 Recent issue [Todo]", fake: commandFlowFakeClient{expectedCreatedAfter: "2026-06-01"}},
		{name: "issue list created-since filter", args: []string{"issue", "list", "--created-since", "2026-06-01", "--limit", "1"}, contains: "LIT-9 Recent issue [Todo]", fake: commandFlowFakeClient{expectedCreatedAfter: "2026-06-01"}},
		{name: "issue list created-before filter", args: []string{"issue", "list", "--created-before", "2026-06-30", "--limit", "1"}, contains: "LIT-19 Older issue [Todo]", fake: commandFlowFakeClient{expectedCreatedBefore: "2026-06-30"}},
		{name: "issue list has blockers filter", args: []string{"issue", "list", "--has-blockers", "--limit", "1"}, contains: "LIT-21 Blocked issue [Todo]"},
		{name: "issue list blocks filter", args: []string{"issue", "list", "--blocks", "--limit", "1"}, contains: "LIT-22 Blocking issue [Todo]"},
		{name: "issue list blocked by filter", args: []string{"issue", "list", "--blocked-by", "LIT-1", "--limit", "1"}, contains: "LIT-23 Blocked by issue [Todo]", fake: commandFlowFakeClient{expectedBlockedBy: "LIT-1"}},
		{name: "issue list all teams", args: []string{"issue", "list", "--all-teams", "--limit", "1"}, contains: "LIT-20 All-team issue [Todo]"},
		{name: "issue search", args: []string{"issue", "search", "needle", "--limit", "1"}, contains: "LIT-3 Search result [Todo]", fake: commandFlowFakeClient{expectedSearchQuery: "needle"}},
		{name: "issue figma file key search", args: []string{"issue", "figma-file-key-search", "figma-key", "--limit", "1"}, contains: "LIT-41 Figma issue [Todo]", fake: commandFlowFakeClient{expectedIssueFigmaFileKey: "figma-key"}},
		{name: "issue priority values", args: []string{"issue", "priority-values"}, contains: "1 Urgent"},
		{name: "issue filter suggestion", args: []string{"issue", "filter-suggestion", "started issues", "--team-id", "team-id"}, contains: `log_id=issue-filter-log-id filter={"state":{"type":{"eq":"started"}}}`, fake: commandFlowFakeClient{expectedIssueFilterPrompt: "started issues", expectedIssueFilterTeamID: "team-id"}},
		{name: "issue title suggestion", args: []string{"issue", "title-suggestion", "Customer asks for faster exports"}, contains: "log_id=title-log-id title=Improve exports", fake: commandFlowFakeClient{expectedIssueTitleRequest: "Customer asks for faster exports"}},
		{name: "issue vcs branch search get", args: []string{"issue", "vcs-branch-search", "get", "omer/branch", "--json"}, contains: `"identifier": "LIT-40"`},
		{name: "issue vcs branch attachments", args: []string{"issue", "vcs-branch-search", "attachments", "omer/branch", "--limit", "1"}, contains: "attachment-id Linked PR [github]"},
		{name: "issue vcs branch bot actor", args: []string{"issue", "vcs-branch-search", "bot-actor", "omer/branch"}, contains: "issue-id bot bot-actor-id GitHub [github]"},
		{name: "issue vcs branch children", args: []string{"issue", "vcs-branch-search", "children", "omer/branch", "--limit", "1"}, contains: "LIT-1 Detail issue [Todo]"},
		{name: "issue vcs branch documents", args: []string{"issue", "vcs-branch-search", "documents", "omer/branch", "--limit", "1"}, contains: "document-id Spec [issue]"},
		{name: "issue vcs branch former attachments", args: []string{"issue", "vcs-branch-search", "former-attachments", "omer/branch", "--limit", "1"}, contains: "attachment-id Linked PR [github]"},
		{name: "issue vcs branch comments", args: []string{"issue", "vcs-branch-search", "comments", "omer/branch", "--limit", "1"}, contains: "comment-id Omer 2026-06-19T12:00:00Z"},
		{name: "issue vcs branch former needs", args: []string{"issue", "vcs-branch-search", "former-needs", "omer/branch", "--limit", "1"}, contains: "customer-need-id Acme LIT-1 priority 1"},
		{name: "issue vcs branch history", args: []string{"issue", "vcs-branch-search", "history", "omer/branch", "--limit", "1"}, contains: "issue-history-id issue issue-id updated_description true"},
		{name: "issue vcs branch inverse relations", args: []string{"issue", "vcs-branch-search", "inverse-relations", "omer/branch", "--limit", "1"}, contains: "issue-relation-id blocks LIT-1 -> LIT-2"},
		{name: "issue vcs branch labels", args: []string{"issue", "vcs-branch-search", "labels", "omer/branch", "--limit", "1"}, contains: "label-id Bug #ff0000"},
		{name: "issue vcs branch needs", args: []string{"issue", "vcs-branch-search", "needs", "omer/branch", "--limit", "1"}, contains: "customer-need-id Acme LIT-1 priority 1"},
		{name: "issue vcs branch relations", args: []string{"issue", "vcs-branch-search", "relations", "omer/branch", "--limit", "1"}, contains: "issue-relation-id blocks LIT-1 -> LIT-2"},
		{name: "issue vcs branch releases", args: []string{"issue", "vcs-branch-search", "releases", "omer/branch", "--limit", "1"}, contains: "release-id Mobile 1.2.3 [v1.2.3] pipeline Production stage Started issues 3"},
		{name: "issue vcs branch shared access", args: []string{"issue", "vcs-branch-search", "shared-access", "omer/branch"}, contains: "issue-id LIT-1 shared=true shared_with=2 viewer_shared_only=false disallowed=description,priority"},
		{name: "issue vcs branch state history", args: []string{"issue", "vcs-branch-search", "state-history", "omer/branch", "--limit", "1"}, contains: "issue-state-span-id Started started 2026-06-19T12:00:00Z -> -"},
		{name: "issue vcs branch subscribers", args: []string{"issue", "vcs-branch-search", "subscribers", "omer/branch", "--limit", "1"}, contains: "user-id Omer <omer@example.com>"},
		{name: "issue get", args: []string{"issue", "get", "LIT-1"}, contains: "LIT-1 Detail issue [Todo]"},
		{name: "issue deps", args: []string{"issue", "deps", "LIT-1", "--limit", "2"}, contains: "blocked_by:\nLIT-24 Blocker issue [Todo]", fake: commandFlowFakeClient{expectedIssueDeps: "LIT-1"}},
		{name: "issue attachments", args: []string{"issue", "attachments", "LIT-1", "--limit", "1"}, contains: "attachment-id Linked PR [github]"},
		{name: "issue bot actor", args: []string{"issue", "bot-actor", "LIT-1"}, contains: "issue-id bot bot-actor-id GitHub [github]"},
		{name: "issue children", args: []string{"issue", "children", "LIT-1", "--limit", "1"}, contains: "LIT-1 Detail issue [Todo]"},
		{name: "issue documents", args: []string{"issue", "documents", "LIT-1", "--limit", "1"}, contains: "document-id Spec [issue]"},
		{name: "issue former attachments", args: []string{"issue", "former-attachments", "LIT-1", "--limit", "1"}, contains: "attachment-id Linked PR [github]"},
		{name: "issue former needs", args: []string{"issue", "former-needs", "LIT-1", "--limit", "1"}, contains: "customer-need-id Acme LIT-1 priority 1"},
		{name: "issue history", args: []string{"issue", "history", "LIT-1", "--limit", "1"}, contains: "issue-history-id issue issue-id updated_description true"},
		{name: "issue inverse relations", args: []string{"issue", "inverse-relations", "LIT-1", "--limit", "1"}, contains: "issue-relation-id blocks LIT-1 -> LIT-2"},
		{name: "issue labels", args: []string{"issue", "labels", "LIT-1", "--limit", "1"}, contains: "label-id Bug #ff0000"},
		{name: "issue needs", args: []string{"issue", "needs", "LIT-1", "--limit", "1"}, contains: "customer-need-id Acme LIT-1 priority 1"},
		{name: "issue relations", args: []string{"issue", "relations", "LIT-1", "--limit", "1"}, contains: "issue-relation-id blocks LIT-1 -> LIT-2"},
		{name: "issue releases", args: []string{"issue", "releases", "LIT-1", "--limit", "1"}, contains: "release-id Mobile 1.2.3 [v1.2.3] pipeline Production stage Started issues 3"},
		{name: "issue shared access", args: []string{"issue", "shared-access", "LIT-1"}, contains: "issue-id LIT-1 shared=true shared_with=2 viewer_shared_only=false disallowed=description,priority"},
		{name: "issue state history", args: []string{"issue", "state-history", "LIT-1", "--limit", "1"}, contains: "issue-state-span-id Started started 2026-06-19T12:00:00Z -> -"},
		{name: "issue subscribers", args: []string{"issue", "subscribers", "LIT-1", "--limit", "1"}, contains: "user-id Omer <omer@example.com>"},
		{name: "issue relation list", args: []string{"issue-relation", "list", "--limit", "1"}, contains: "issue-relation-id blocks LIT-1 -> LIT-2"},
		{name: "issue relation get", args: []string{"issue-relation", "get", "issue-relation-id"}, contains: "issue-relation-id blocks LIT-1 -> LIT-2"},
		{name: "issue pr", args: []string{"issue", "pr", "LIT-1"}, contains: `gh pr create --title "LIT-1 Detail issue" --body "https://linear.app/kyanite/issue/LIT-1"`},
		{name: "issue create", args: []string{"issue", "create", "--title", "Created issue"}, contains: "LIT-2 Created issue [Todo]", fake: commandFlowFakeClient{expectedCreateTitle: "Created issue"}},
		{name: "issue create with state alias", args: []string{"issue", "create", "--title", "Created issue", "--state", "todo"}, contains: "LIT-2 Created issue [Todo]", fake: commandFlowFakeClient{expectedCreateTitle: "Created issue"}},
		{name: "issue create with priority alias", args: []string{"issue", "create", "--title", "Created issue", "--priority", "high"}, contains: "LIT-2 Created issue [Todo]", fake: commandFlowFakeClient{expectedCreateTitle: "Created issue"}},
		{name: "issue create with status alias", args: []string{"issue", "create", "--title", "Created issue", "--status", "done"}, contains: "LIT-2 Created issue [Todo]", fake: commandFlowFakeClient{expectedCreateTitle: "Created issue"}},
		{name: "issue create from template", args: []string{"issue", "create", "--template", "template-id"}, contains: "LIT-2 Created issue [Todo]"},
		{name: "issue create with estimate", args: []string{"issue", "create", "--title", "Created issue", "--estimate", "3"}, contains: "LIT-2 Created issue [Todo]", fake: commandFlowFakeClient{expectedCreateTitle: "Created issue"}},
		{name: "issue create with parent", args: []string{"issue", "create", "--title", "Created issue", "--parent", "LIT-1"}, contains: "LIT-2 Created issue [Todo]", fake: commandFlowFakeClient{expectedCreateTitle: "Created issue"}},
		{name: "issue update", args: []string{"issue", "update", "LIT-1", "--title", "Updated issue"}, contains: "LIT-1 Updated issue [Todo]", fake: commandFlowFakeClient{expectedUpdateTitle: "Updated issue"}},
		{name: "issue update with state alias", args: []string{"issue", "update", "LIT-1", "--state", "done"}, contains: "LIT-1 Updated issue [Todo]"},
		{name: "issue update with priority alias", args: []string{"issue", "update", "LIT-1", "--priority", "2"}, contains: "LIT-1 Updated issue [Todo]"},
		{name: "issue update with status alias", args: []string{"issue", "update", "LIT-1", "--status", "started"}, contains: "LIT-1 Updated issue [Todo]"},
		{name: "issue update append", args: []string{"issue", "update", "LIT-1", "--append", "Progress note"}, contains: "LIT-1 Updated issue [Todo]", fake: commandFlowFakeClient{expectedUpdateDescription: "Existing description\n\nProgress note"}},
		{name: "issue update with estimate", args: []string{"issue", "update", "LIT-1", "--estimate", "5"}, contains: "LIT-1 Updated issue [Todo]"},
		{name: "issue update clear estimate", args: []string{"issue", "update", "LIT-1", "--clear-estimate"}, contains: "LIT-1 Updated issue [Todo]"},
		{name: "issue list status alias", args: []string{"issue", "list", "--status", "started", "--limit", "1"}, contains: "LIT-2 Started issue [Started]", fake: commandFlowFakeClient{expectedStateType: "started"}},
		{name: "issue start", args: []string{"issue", "start", "LIT-1"}, contains: "LIT-1 Started issue [Started]", fake: commandFlowFakeClient{expectedStartAssigneeID: "user-id", expectedStartStateID: "started-state"}},
		{name: "issue comment", args: []string{"issue", "comment", "LIT-1", "--body", "Looks good"}, contains: "comment comment-id on LIT-1"},
		{name: "issue reply", args: []string{"issue", "reply", "LIT-1", "comment-id", "--body", "Reply body"}, contains: "comment comment-id on LIT-1", fake: commandFlowFakeClient{expectedCommentBody: "Reply body", expectedCommentParentID: "comment-id"}},
		{name: "issue comments", args: []string{"issue", "comments", "LIT-1", "--limit", "1"}, contains: "comment-id Omer First comment"},
		{name: "comment list", args: []string{"comment", "list", "--limit", "1"}, contains: "comment-id Omer First comment"},
		{name: "comment get", args: []string{"comment", "get", "comment-id"}, contains: "comment-id Omer First comment"},
		{name: "comment update", args: []string{"comment", "update", "comment-id", "--body", "New body"}, contains: "comment-id Omer First comment"},
		{name: "comment delete", args: []string{"comment", "delete", "comment-id"}, contains: "comment-id deleted"},
		{name: "comment bot actor", args: []string{"comment", "bot-actor", "comment-id"}, contains: "comment-id bot bot-actor-id GitHub [github]"},
		{name: "comment children", args: []string{"comment", "children", "comment-id", "--limit", "1"}, contains: "child-comment-id Omer 2026-06-19T12:00:00Z"},
		{name: "comment created issues", args: []string{"comment", "created-issues", "comment-id", "--limit", "1"}, contains: "LIT-1 Detail issue [Todo]"},
		{name: "issue close", args: []string{"issue", "close", "LIT-1"}, contains: "LIT-1 Closed issue [Done]"},
		{name: "issue relate", args: []string{"issue", "relate", "LIT-1", "LIT-2", "--type", "related"}, contains: "issue-relation-id related LIT-1 -> LIT-2"},
		{name: "issue unrelate", args: []string{"issue", "unrelate", "issue-relation-id"}, contains: "issue-relation-id deleted"},
		{name: "issue link", args: []string{"issue", "link", "https://example.com/pr/1", "LIT-1"}, contains: "attachment-id https://example.com/pr/1"},
		{name: "project list", args: []string{"project", "list", "--limit", "1"}, contains: "project-id Listed project [Backlog]"},
		{name: "project all", args: []string{"project", "all", "--limit", "1"}, contains: "project-id Listed project [Backlog]"},
		{name: "project get", args: []string{"project", "get", "project-id"}, contains: "project-id Detail project [Backlog]"},
		{name: "project attachments", args: []string{"project", "attachments", "project-id", "--limit", "1"}, contains: "attachment-id Linked PR [github]"},
		{name: "project documents", args: []string{"project", "documents", "project-id", "--limit", "1"}, contains: "document-id Spec [project]"},
		{name: "project external links", args: []string{"project", "external-links", "project-id", "--limit", "1"}, contains: "release-link-id Runbook https://example.com/runbook order 1.5"},
		{name: "project history", args: []string{"project", "history", "project-id", "--limit", "1"}, contains: "project-history-id project project-id entries 1"},
		{name: "project initiative links", args: []string{"project", "initiative-links", "project-id", "--limit", "1"}, contains: "initiative-to-project-id Platform -> Pinned project order 1"},
		{name: "project initiatives", args: []string{"project", "initiatives", "project-id", "--limit", "1"}, contains: "initiative-id Platform [Active]"},
		{name: "project inverse relations", args: []string{"project", "inverse-relations", "project-id", "--limit", "1"}, contains: "project-relation-id blocks Pinned project -> Related project"},
		{name: "project issues", args: []string{"project", "issues", "project-id", "--limit", "1"}, contains: "LIT-1 Detail issue [Todo]"},
		{name: "project labels", args: []string{"project", "labels", "project-id", "--limit", "1"}, contains: "project-label-id Roadmap #f2c94c"},
		{name: "project members", args: []string{"project", "members", "project-id", "--limit", "1"}, contains: "user-id Omer"},
		{name: "project needs", args: []string{"project", "needs", "project-id", "--limit", "1"}, contains: "customer-need-id Acme LIT-1 priority 1"},
		{name: "project relations", args: []string{"project", "relations", "project-id", "--limit", "1"}, contains: "project-relation-id blocks Pinned project -> Related project"},
		{name: "project teams", args: []string{"project", "teams", "project-id", "--limit", "1"}, contains: "team-id LIT linctl"},
		{name: "project updates", args: []string{"project", "updates", "project-id", "--limit", "1"}, contains: "project-update-id onTrack Omer"},
		{name: "project filter suggestion", args: []string{"project", "filter-suggestion", "started projects"}, contains: `log_id=filter-log-id filter={"status":{"type":{"eq":"started"}}}`},
		{name: "project update list", args: []string{"project-update", "list", "--limit", "1"}, contains: "project-update-id onTrack Omer First update"},
		{name: "project update get", args: []string{"project-update", "get", "project-update-id"}, contains: "project-update-id onTrack Omer First update"},
		{name: "project update create", args: []string{"project-update", "create", "project-id", "--health", "on-track", "--body", "Posted update"}, contains: "project-update-id onTrack Omer First update"},
		{name: "project milestone all", args: []string{"project-milestone", "all", "--limit", "1"}, contains: "project-milestone-id Launch milestone [next]"},
		{name: "project milestone list", args: []string{"project-milestone", "list", "project-id", "--limit", "1"}, contains: "project-milestone-id Launch milestone [next]"},
		{name: "project milestone create", args: []string{"project-milestone", "create", "project-id", "--name", "Created milestone"}, contains: "project-milestone-id Created milestone [next]", fake: commandFlowFakeClient{expectedMilestoneCreateName: "Created milestone"}},
		{name: "project milestone update", args: []string{"project-milestone", "update", "project-milestone-id", "--name", "Updated milestone"}, contains: "project-milestone-id Updated milestone [done]", fake: commandFlowFakeClient{expectedMilestoneUpdateName: "Updated milestone"}},
		{name: "project status list", args: []string{"project-status", "list", "--limit", "1"}, contains: "project-status-id Backlog [backlog] #bec2c8"},
		{name: "project status get", args: []string{"project-status", "get", "project-status-id"}, contains: "project-status-id Backlog [backlog] #bec2c8"},
		{name: "project status project count", args: []string{"project-status", "project-count", "project-status-id"}, contains: "project-status-id count 12 private 2 archived_team 1"},
		{name: "project label list", args: []string{"project-label", "list", "--limit", "1"}, contains: "project-label-id Roadmap #f2c94c"},
		{name: "project label get", args: []string{"project-label", "get", "project-label-id"}, contains: "project-label-id Roadmap #f2c94c"},
		{name: "project label children", args: []string{"project-label", "children", "project-label-id", "--limit", "1"}, contains: "child-project-label-id Mobile #56ccf2"},
		{name: "project label projects", args: []string{"project-label", "projects", "project-label-id", "--limit", "1"}, contains: "project-id Listed project [Backlog]"},
		{name: "project relation list", args: []string{"project-relation", "list", "--limit", "1"}, contains: "project-relation-id blocks Pinned project -> Related project"},
		{name: "project relation get", args: []string{"project-relation", "get", "project-relation-id"}, contains: "project-relation-id blocks Pinned project -> Related project"},
		{name: "project create", args: []string{"project", "create", "--name", "Created project"}, contains: "project-id Created project [Backlog]", fake: commandFlowFakeClient{expectedProjectCreateName: "Created project"}},
		{name: "project update", args: []string{"project", "update", "project-id", "--name", "Updated project"}, contains: "project-id Updated project [Started]", fake: commandFlowFakeClient{expectedProjectUpdateName: "Updated project"}},
		{name: "project archive", args: []string{"project", "archive", "project-id"}, contains: "project-id Archived project [Canceled]"},
		{name: "document list", args: []string{"document", "list", "--limit", "1"}, contains: "document-id Spec [project]"},
		{name: "document get", args: []string{"document", "get", "document-id"}, contains: "document-id Team note [team]"},
		{name: "document comments", args: []string{"document", "comments", "document-id", "--limit", "1"}, contains: "comment-id Omer 2026-06-19T12:00:00Z"},
		{name: "document create", args: []string{"document", "create", "--title", "Created doc"}, contains: "document-id Created doc [team]"},
		{name: "document update", args: []string{"document", "update", "document-id", "--title", "Updated doc"}, contains: "document-id Updated doc [team]"},
		{name: "label list", args: []string{"label", "list", "--limit", "1"}, contains: "label-id Bug #ff0000"},
		{name: "label get", args: []string{"label", "get", "label-id"}, contains: "label-id Bug #ff0000"},
		{name: "label children", args: []string{"label", "children", "label-id", "--limit", "1"}, contains: "child-label-id Mobile #56ccf2"},
		{name: "label issues", args: []string{"label", "issues", "label-id", "--limit", "1"}, contains: "LIT-1 Detail issue [Todo]"},
		{name: "team list", args: []string{"team", "list", "--limit", "1"}, contains: "team-id LIT linctl"},
		{name: "team get", args: []string{"team", "get", "team-id"}, contains: "team-id LIT linctl"},
		{name: "team cycles", args: []string{"team", "cycles", "team-id", "--limit", "1"}, contains: "cycle-id Planning cycle [active]"},
		{name: "team issues", args: []string{"team", "issues", "team-id", "--limit", "1"}, contains: "LIT-1 Detail issue [Todo]"},
		{name: "team labels", args: []string{"team", "labels", "team-id", "--limit", "1"}, contains: "label-id Bug #ff0000"},
		{name: "team members", args: []string{"team", "members", "team-id", "--limit", "1"}, contains: "user-id Omer <omer@example.com>"},
		{name: "team memberships", args: []string{"team", "memberships", "team-id", "--limit", "1"}, contains: "team-membership-id LIT Omer owner true order 1.50"},
		{name: "team projects", args: []string{"team", "projects", "team-id", "--limit", "1"}, contains: "project-id Listed project [Backlog]"},
		{name: "team release pipelines", args: []string{"team", "release-pipelines", "team-id", "--limit", "1"}, contains: "release-pipeline-id Production production releases 4"},
		{name: "team states", args: []string{"team", "states", "team-id", "--limit", "1"}, contains: "workflow-state-id Started [started]"},
		{name: "team git automation states", args: []string{"team", "git-automation-states", "team-id", "--limit", "1"}, contains: "git-automation-state-id review state Started target main"},
		{name: "team templates", args: []string{"team", "templates", "team-id", "--limit", "1"}, contains: "template-id Bug report [issue] team LIT"},
		{name: "team membership list", args: []string{"team-membership", "list", "--limit", "1"}, contains: "team-membership-id LIT Omer owner true order 1.50"},
		{name: "team membership get", args: []string{"team-membership", "get", "team-membership-id"}, contains: "team-membership-id LIT Omer owner true order 1.50"},
		{name: "user list", args: []string{"user", "list", "--limit", "1"}, contains: "user-id Omer <omer@example.com>"},
		{name: "user get", args: []string{"user", "get", "user-id"}, contains: "user-id Omer <omer@example.com>"},
		{name: "user me", args: []string{"user", "me"}, contains: "user-id Omer <omer@example.com>"},
		{name: "user drafts", args: []string{"user", "drafts", "--limit", "1"}, contains: "draft-id issue LIT-3 Draft issue"},
		{name: "user settings get", args: []string{"user", "settings", "get"}, contains: "settings-id user=user-id auto_assign=true full_names=false"},
		{name: "user settings notification categories", args: []string{"user", "settings", "notification-categories", "--json"}, contains: `"apps_and_integrations"`},
		{name: "user settings apps integrations", args: []string{"user", "settings", "notification-category", "apps-and-integrations"}, contains: "apps-and-integrations desktop=true email=false mobile=true slack=false"},
		{name: "user settings assignments", args: []string{"user", "settings", "notification-category", "assignments"}, contains: "assignments desktop=true email=false mobile=true slack=false"},
		{name: "user settings billing", args: []string{"user", "settings", "notification-category", "billing"}, contains: "billing desktop=true email=false mobile=true slack=false"},
		{name: "user settings comments replies", args: []string{"user", "settings", "notification-category", "comments-and-replies"}, contains: "comments-and-replies desktop=true email=false mobile=true slack=false"},
		{name: "user settings customers", args: []string{"user", "settings", "notification-category", "customers"}, contains: "customers desktop=true email=false mobile=true slack=false"},
		{name: "user settings document changes", args: []string{"user", "settings", "notification-category", "document-changes"}, contains: "document-changes desktop=true email=false mobile=true slack=false"},
		{name: "user settings feed", args: []string{"user", "settings", "notification-category", "feed"}, contains: "feed desktop=true email=false mobile=true slack=false"},
		{name: "user settings mentions", args: []string{"user", "settings", "notification-category", "mentions"}, contains: "mentions desktop=true email=false mobile=true slack=false"},
		{name: "user settings posts updates", args: []string{"user", "settings", "notification-category", "posts-and-updates"}, contains: "posts-and-updates desktop=true email=false mobile=true slack=false"},
		{name: "user settings reactions", args: []string{"user", "settings", "notification-category", "reactions"}, contains: "reactions desktop=true email=false mobile=true slack=false"},
		{name: "user settings reminders", args: []string{"user", "settings", "notification-category", "reminders"}, contains: "reminders desktop=true email=false mobile=true slack=false"},
		{name: "user settings reviews", args: []string{"user", "settings", "notification-category", "reviews"}, contains: "reviews desktop=true email=false mobile=true slack=false"},
		{name: "user settings status changes", args: []string{"user", "settings", "notification-category", "status-changes"}, contains: "status-changes desktop=true email=false mobile=true slack=false"},
		{name: "user settings subscriptions", args: []string{"user", "settings", "notification-category", "subscriptions"}, contains: "subscriptions desktop=true email=false mobile=true slack=false"},
		{name: "user settings system", args: []string{"user", "settings", "notification-category", "system"}, contains: "system desktop=true email=false mobile=true slack=false"},
		{name: "user settings triage", args: []string{"user", "settings", "notification-category", "triage"}, contains: "triage desktop=true email=false mobile=true slack=false"},
		{name: "user settings channels", args: []string{"user", "settings", "notification-channels"}, contains: "channels desktop=true email=false mobile=true slack=false"},
		{name: "user settings delivery", args: []string{"user", "settings", "notification-delivery"}, contains: "notification delivery"},
		{name: "user settings mobile delivery", args: []string{"user", "settings", "mobile-delivery"}, contains: "mobile delivery"},
		{name: "user settings mobile schedule", args: []string{"user", "settings", "mobile-schedule"}, contains: "mobile schedule"},
		{name: "user settings friday", args: []string{"user", "settings", "mobile-schedule-day", "friday"}, contains: "friday start=09:00 end=18:00"},
		{name: "user settings monday", args: []string{"user", "settings", "mobile-schedule-day", "monday"}, contains: "monday start=09:00 end=18:00"},
		{name: "user settings saturday", args: []string{"user", "settings", "mobile-schedule-day", "saturday"}, contains: "saturday start=09:00 end=18:00"},
		{name: "user settings sunday", args: []string{"user", "settings", "mobile-schedule-day", "sunday"}, contains: "sunday start=09:00 end=18:00"},
		{name: "user settings thursday", args: []string{"user", "settings", "mobile-schedule-day", "thursday"}, contains: "thursday start=09:00 end=18:00"},
		{name: "user settings tuesday", args: []string{"user", "settings", "mobile-schedule-day", "tuesday"}, contains: "tuesday start=09:00 end=18:00"},
		{name: "user settings wednesday", args: []string{"user", "settings", "mobile-schedule-day", "wednesday"}, contains: "wednesday start=09:00 end=18:00"},
		{name: "user settings theme", args: []string{"user", "settings", "theme", "--device-type", "desktop", "--mode", "dark"}, contains: "theme device_type=desktop mode=dark"},
		{name: "user settings custom theme", args: []string{"user", "settings", "custom-theme", "--json"}, contains: `"contrast": 50`},
		{name: "user settings custom sidebar theme", args: []string{"user", "settings", "custom-sidebar-theme", "--json"}, contains: `"accent"`},
		{name: "user assigned issues", args: []string{"user", "assigned-issues", "user-id", "--limit", "1"}, contains: "LIT-1 Detail issue [Todo]"},
		{name: "user created issues", args: []string{"user", "created-issues", "user-id", "--limit", "1"}, contains: "LIT-1 Detail issue [Todo]"},
		{name: "user delegated issues", args: []string{"user", "delegated-issues", "user-id", "--limit", "1"}, contains: "LIT-1 Detail issue [Todo]"},
		{name: "user team memberships", args: []string{"user", "team-memberships", "user-id", "--limit", "1"}, contains: "team-membership-id LIT Omer owner true order 1.50"},
		{name: "user teams", args: []string{"user", "teams", "user-id", "--limit", "1"}, contains: "team-id LIT linctl"},
		{name: "user my assigned issues", args: []string{"user", "my-assigned-issues", "--limit", "1"}, contains: "LIT-1 Detail issue [Todo]"},
		{name: "user my created issues", args: []string{"user", "my-created-issues", "--limit", "1"}, contains: "LIT-1 Detail issue [Todo]"},
		{name: "user my delegated issues", args: []string{"user", "my-delegated-issues", "--limit", "1"}, contains: "LIT-1 Detail issue [Todo]"},
		{name: "user my team memberships", args: []string{"user", "my-team-memberships", "--limit", "1"}, contains: "team-membership-id LIT Omer owner true order 1.50"},
		{name: "user my teams", args: []string{"user", "my-teams", "--limit", "1"}, contains: "team-id LIT linctl"},
		{name: "workflow state list", args: []string{"workflow-state", "list", "--limit", "1"}, contains: "workflow-state-id Started [started]"},
		{name: "workflow state get", args: []string{"workflow-state", "get", "workflow-state-id"}, contains: "workflow-state-id Started [started]"},
		{name: "workflow state issues", args: []string{"workflow-state", "issues", "workflow-state-id", "--limit", "1"}, contains: "LIT-1 Detail issue [Todo]"},
		{name: "time schedule list", args: []string{"time-schedule", "list", "--limit", "1"}, contains: "time-schedule-id Primary on-call entries 1"},
		{name: "time schedule get", args: []string{"time-schedule", "get", "time-schedule-id"}, contains: "time-schedule-id Primary on-call entries 1"},
		{name: "template list", args: []string{"template", "list", "--limit", "1"}, contains: "template-id Bug report [issue] team LIT"},
		{name: "template get", args: []string{"template", "get", "template-id"}, contains: "template-id Bug report [issue] team LIT"},
		{name: "initiative list", args: []string{"initiative", "list", "--limit", "1"}, contains: "initiative-id Platform [Active]"},
		{name: "initiative get", args: []string{"initiative", "get", "initiative-id"}, contains: "initiative-id Platform [Active]"},
		{name: "initiative history", args: []string{"initiative", "history", "initiative-id", "--limit", "1"}, contains: "initiative-history-id initiative initiative-id entries 1"},
		{name: "initiative links", args: []string{"initiative", "links", "initiative-id", "--limit", "1"}, contains: "release-link-id Runbook https://example.com/runbook order 1.5"},
		{name: "initiative sub-initiatives", args: []string{"initiative", "sub-initiatives", "initiative-id", "--limit", "1"}, contains: "child-initiative-id Child platform [Planned]"},
		{name: "initiative updates", args: []string{"initiative", "updates", "initiative-id", "--limit", "1"}, contains: "initiative-update-id onTrack Omer First initiative update"},
		{name: "initiative documents", args: []string{"initiative", "documents", "initiative-id", "--limit", "1"}, contains: "document-id Spec [project]"},
		{name: "initiative projects", args: []string{"initiative", "projects", "initiative-id", "--limit", "1"}, contains: "project-id Listed project [Backlog]"},
		{name: "initiative relation list", args: []string{"initiative-relation", "list", "--limit", "1"}, contains: "initiative-relation-id Platform -> Child initiative order 1.50"},
		{name: "initiative relation get", args: []string{"initiative-relation", "get", "initiative-relation-id"}, contains: "initiative-relation-id Platform -> Child initiative order 1.50"},
		{name: "initiative to project list", args: []string{"initiative-to-project", "list", "--limit", "1"}, contains: "initiative-to-project-id Platform -> Pinned project order 1"},
		{name: "initiative to project get", args: []string{"initiative-to-project", "get", "initiative-to-project-id"}, contains: "initiative-to-project-id Platform -> Pinned project order 1"},
		{name: "initiative update list", args: []string{"initiative-update", "list", "--limit", "1"}, contains: "initiative-update-id onTrack Omer First initiative update"},
		{name: "initiative update get", args: []string{"initiative-update", "get", "initiative-update-id"}, contains: "initiative-update-id onTrack Omer First initiative update"},
		{name: "initiative update comments", args: []string{"initiative-update", "comments", "initiative-update-id", "--limit", "1"}, contains: "comment-id Omer 2026-06-19T12:00:00Z"},
		{name: "roadmap list", args: []string{"roadmap", "list", "--limit", "1"}, contains: "roadmap-id Platform roadmap platform-roadmap"},
		{name: "roadmap get", args: []string{"roadmap", "get", "roadmap-id"}, contains: "roadmap-id Platform roadmap platform-roadmap"},
		{name: "roadmap projects", args: []string{"roadmap", "projects", "roadmap-id", "--limit", "1"}, contains: "project-id Listed project [Backlog]"},
		{name: "roadmap to project list", args: []string{"roadmap-to-project", "list", "--limit", "1"}, contains: "roadmap-to-project-id Platform roadmap -> Pinned project order 1"},
		{name: "roadmap to project get", args: []string{"roadmap-to-project", "get", "roadmap-to-project-id"}, contains: "roadmap-to-project-id Platform roadmap -> Pinned project order 1"},
		{name: "custom view list", args: []string{"custom-view", "list", "--limit", "1"}, contains: "custom-view-id My issues [Issue]"},
		{name: "custom view subscribers", args: []string{"custom-view", "subscribers", "custom-view-id"}, contains: "custom-view-id has_subscribers true"},
		{name: "custom view get", args: []string{"custom-view", "get", "custom-view-id"}, contains: "custom-view-id My issues [Issue]"},
		{name: "custom view initiatives", args: []string{"custom-view", "initiatives", "custom-view-id", "--limit", "1"}, contains: "initiative-id Platform [Active]"},
		{name: "custom view issues", args: []string{"custom-view", "issues", "custom-view-id", "--limit", "1"}, contains: "LIT-1 Detail issue [Todo]"},
		{name: "custom view organization preferences", args: []string{"custom-view", "organization-preferences", "custom-view-id"}, contains: "custom-view-id organization preferences organization customView layout list"},
		{name: "custom view organization preference values", args: []string{"custom-view", "organization-preferences", "values", "custom-view-id"}, contains: "custom-view-id preference values layout list ordering priority"},
		{name: "custom view projects", args: []string{"custom-view", "projects", "custom-view-id", "--limit", "1"}, contains: "project-id Pinned project [Backlog]"},
		{name: "custom view user preferences", args: []string{"custom-view", "user-preferences", "custom-view-id"}, contains: "custom-view-id user preferences user customView layout board"},
		{name: "custom view user preference values", args: []string{"custom-view", "user-preferences", "values", "custom-view-id"}, contains: "custom-view-id preference values layout board ordering updatedAt"},
		{name: "custom view preference values", args: []string{"custom-view", "preference-values", "custom-view-id"}, contains: "custom-view-id preference values layout board ordering updatedAt"},
		{name: "customer list", args: []string{"customer", "list", "--limit", "1"}, contains: "customer-id Acme [Active] needs 3"},
		{name: "customer get", args: []string{"customer", "get", "customer-id"}, contains: "customer-id Acme [Active] needs 3"},
		{name: "customer need list", args: []string{"customer-need", "list", "--limit", "1"}, contains: "customer-need-id Acme LIT-1 priority 1"},
		{name: "customer need get", args: []string{"customer-need", "get", "customer-need-id"}, contains: "customer-need-id Acme LIT-1 priority 1"},
		{name: "customer need project attachment", args: []string{"customer-need", "project-attachment", "customer-need-id"}, contains: "customer-need-id project_attachment attachment-id Linked PR [github]"},
		{name: "customer status list", args: []string{"customer-status", "list", "--limit", "1"}, contains: "customer-status-id Active #00ff00 1"},
		{name: "customer status get", args: []string{"customer-status", "get", "customer-status-id"}, contains: "customer-status-id Active #00ff00 1"},
		{name: "customer tier list", args: []string{"customer-tier", "list", "--limit", "1"}, contains: "customer-tier-id Enterprise #0000ff 2"},
		{name: "customer tier get", args: []string{"customer-tier", "get", "customer-tier-id"}, contains: "customer-tier-id Enterprise #0000ff 2"},
		{name: "favorite list", args: []string{"favorite", "list", "--limit", "1"}, contains: "favorite-id [issue]"},
		{name: "favorite children", args: []string{"favorite", "children", "favorite-folder-id", "--limit", "1"}, contains: "favorite-child-id [project]"},
		{name: "favorite get", args: []string{"favorite", "get", "favorite-id"}, contains: "favorite-id [issue]"},
		{name: "emoji list", args: []string{"emoji", "list", "--limit", "1"}, contains: "emoji-id party [custom]"},
		{name: "emoji get", args: []string{"emoji", "get", "emoji-id"}, contains: "emoji-id party [custom]"},
		{name: "attachment list", args: []string{"attachment", "list", "--limit", "1"}, contains: "attachment-id Linked PR [github]"},
		{name: "attachment url", args: []string{"attachment", "url", "https://github.com/kyanite/linctl/pull/1", "--limit", "1"}, contains: "attachment-id Linked PR [github]"},
		{name: "attachment get", args: []string{"attachment", "get", "attachment-id"}, contains: "attachment-id Linked PR [github]"},
		{name: "attachment issue get", args: []string{"attachment", "issue", "get", "attachment-id"}, contains: "LIT-1 Detail issue [Todo]"},
		{name: "attachment issue attachments", args: []string{"attachment", "issue", "attachments", "attachment-id", "--limit", "1"}, contains: "attachment-id Linked PR [github]"},
		{name: "attachment issue bot actor", args: []string{"attachment", "issue", "bot-actor", "attachment-id"}, contains: "issue-id bot bot-actor-id GitHub [github]"},
		{name: "attachment issue children", args: []string{"attachment", "issue", "children", "attachment-id", "--limit", "1"}, contains: "LIT-1 Detail issue [Todo]"},
		{name: "attachment issue comments", args: []string{"attachment", "issue", "comments", "attachment-id", "--limit", "1"}, contains: "comment-id Omer 2026-06-19T12:00:00Z"},
		{name: "attachment issue documents", args: []string{"attachment", "issue", "documents", "attachment-id", "--limit", "1"}, contains: "document-id Spec [issue]"},
		{name: "attachment issue former attachments", args: []string{"attachment", "issue", "former-attachments", "attachment-id", "--limit", "1"}, contains: "attachment-id Linked PR [github]"},
		{name: "attachment issue former needs", args: []string{"attachment", "issue", "former-needs", "attachment-id", "--limit", "1"}, contains: "customer-need-id Acme LIT-1 priority 1"},
		{name: "attachment issue history", args: []string{"attachment", "issue", "history", "attachment-id", "--limit", "1"}, contains: "issue-history-id issue issue-id updated_description true"},
		{name: "attachment issue inverse relations", args: []string{"attachment", "issue", "inverse-relations", "attachment-id", "--limit", "1"}, contains: "issue-relation-id blocks LIT-1 -> LIT-2"},
		{name: "attachment issue labels", args: []string{"attachment", "issue", "labels", "attachment-id", "--limit", "1"}, contains: "label-id Bug #ff0000"},
		{name: "attachment issue needs", args: []string{"attachment", "issue", "needs", "attachment-id", "--limit", "1"}, contains: "customer-need-id Acme LIT-1 priority 1"},
		{name: "attachment issue relations", args: []string{"attachment", "issue", "relations", "attachment-id", "--limit", "1"}, contains: "issue-relation-id blocks LIT-1 -> LIT-2"},
		{name: "attachment issue releases", args: []string{"attachment", "issue", "releases", "attachment-id", "--limit", "1"}, contains: "release-id Mobile 1.2.3 [v1.2.3] pipeline Production stage Started issues 3"},
		{name: "attachment issue shared access", args: []string{"attachment", "issue", "shared-access", "attachment-id"}, contains: "issue-id LIT-1 shared=true shared_with=2 viewer_shared_only=false disallowed=description,priority"},
		{name: "attachment issue state history", args: []string{"attachment", "issue", "state-history", "attachment-id", "--limit", "1"}, contains: "issue-state-span-id Started started 2026-06-19T12:00:00Z -> -"},
		{name: "attachment issue subscribers", args: []string{"attachment", "issue", "subscribers", "attachment-id", "--limit", "1"}, contains: "user-id Omer <omer@example.com>"},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			output := bytes.Buffer{}
			restore := useCommandRuntime(t, test.fake)
			defer restore()
			command := NewRootCommand(context.Background(), BuildInfo{})
			command.SetOut(&output)
			command.SetArgs(test.args)

			err := command.ExecuteContext(context.Background())

			require.NoError(t, err)
			require.Contains(t, output.String(), test.contains)
		})
	}
}
