package client

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
)

func Test_ClientReadIssueAndProjectScenarios_return_compact_lists_details_and_members(t *testing.T) {
	endCursor := "cursor-1"
	graphqlClient := readScenarioGraphQLClient(endCursor)

	// When
	allTeamIssues, err := ListIssues(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	issues, err := ListIssuesByTeam(context.Background(), graphqlClient, "team-id", 2, IssueListFilters{})
	require.NoError(t, err)
	startedIssues, err := ListIssuesByTeam(context.Background(), graphqlClient, "team-id", 2, IssueListFilters{StateType: "started"})
	require.NoError(t, err)
	projectIssues, err := ListIssuesByTeam(context.Background(), graphqlClient, "team-id", 2, IssueListFilters{ProjectID: "project-id"})
	require.NoError(t, err)
	mineIssues, err := ListIssuesByTeam(context.Background(), graphqlClient, "team-id", 2, IssueListFilters{AssigneeID: "user-id"})
	require.NoError(t, err)
	labelIssues, err := ListIssuesByTeam(context.Background(), graphqlClient, "team-id", 2, IssueListFilters{LabelID: "label-id"})
	require.NoError(t, err)
	cycleIssues, err := ListIssuesByTeam(context.Background(), graphqlClient, "team-id", 2, IssueListFilters{CycleID: "cycle-id"})
	require.NoError(t, err)
	recentIssues, err := ListIssuesByTeam(context.Background(), graphqlClient, "team-id", 2, IssueListFilters{CreatedAfter: "2026-06-01"})
	require.NoError(t, err)
	olderIssues, err := ListIssuesByTeam(context.Background(), graphqlClient, "team-id", 2, IssueListFilters{CreatedBefore: "2026-06-30"})
	require.NoError(t, err)
	blockedIssues, err := ListIssuesByTeam(context.Background(), graphqlClient, "team-id", 2, IssueListFilters{HasBlockers: true})
	require.NoError(t, err)
	blockingIssues, err := ListIssuesByTeam(context.Background(), graphqlClient, "team-id", 2, IssueListFilters{Blocks: true})
	require.NoError(t, err)
	nextIssues, err := ListNextIssuesByTeam(context.Background(), graphqlClient, "team-id", 2)
	require.NoError(t, err)
	blockedByIssues, err := ListIssuesByTeam(context.Background(), graphqlClient, "team-id", 2, IssueListFilters{BlockedBy: "LIT-1"})
	require.NoError(t, err)
	dependencies, err := GetIssueDependencies(context.Background(), graphqlClient, "LIT-1", 2)
	require.NoError(t, err)
	searchIssues, err := SearchIssuesByTeam(context.Background(), graphqlClient, "team-id", "needle", 2)
	require.NoError(t, err)
	figmaIssues, err := SearchIssuesByFigmaFileKey(context.Background(), graphqlClient, "figma-key", 2)
	require.NoError(t, err)
	issuePriorityValues, err := ListIssuePriorityValues(context.Background(), graphqlClient)
	require.NoError(t, err)
	issueFilterSuggestion, err := GetIssueFilterSuggestion(
		context.Background(),
		graphqlClient,
		"started issues",
		"team-id",
		"",
	)
	require.NoError(t, err)
	issueTitleSuggestion, err := GetIssueTitleSuggestionFromCustomerRequest(
		context.Background(),
		graphqlClient,
		"Customer asks for faster exports",
	)
	require.NoError(t, err)
	issue, err := GetIssueByID(context.Background(), graphqlClient, "LIT-11")
	require.NoError(t, err)
	issueAttachments, err := ListIssueAttachments(context.Background(), graphqlClient, "LIT-1", 2)
	require.NoError(t, err)
	issueBotActor, err := GetIssueBotActor(context.Background(), graphqlClient, "LIT-1")
	require.NoError(t, err)
	issueChildren, err := ListIssueChildren(context.Background(), graphqlClient, "LIT-1", 2)
	require.NoError(t, err)
	issueDocuments, err := ListIssueDocuments(context.Background(), graphqlClient, "LIT-1", 2)
	require.NoError(t, err)
	issueFormerAttachments, err := ListIssueFormerAttachments(context.Background(), graphqlClient, "LIT-1", 2)
	require.NoError(t, err)
	issueHistory, err := ListIssueHistory(context.Background(), graphqlClient, "LIT-1", 2)
	require.NoError(t, err)
	issueInverseRelations, err := ListIssueInverseRelations(context.Background(), graphqlClient, "LIT-1", 2)
	require.NoError(t, err)
	issueLabels, err := ListIssueLabels(context.Background(), graphqlClient, "LIT-1", 2)
	require.NoError(t, err)
	issueScopedRelations, err := ListIssueRelationsForIssue(context.Background(), graphqlClient, "LIT-1", 2)
	require.NoError(t, err)
	issueReleases, err := ListIssueReleases(context.Background(), graphqlClient, "LIT-1", 2)
	require.NoError(t, err)
	issueStateHistory, err := ListIssueStateHistory(context.Background(), graphqlClient, "LIT-1", 2)
	require.NoError(t, err)
	issueSubscribers, err := ListIssueSubscribers(context.Background(), graphqlClient, "LIT-1", 2)
	require.NoError(t, err)
	branchIssue, err := GetIssueByVCSBranch(context.Background(), graphqlClient, "omer/branch")
	require.NoError(t, err)
	branchIssueAttachments, err := ListIssueVCSBranchAttachments(context.Background(), graphqlClient, "omer/branch", 2)
	require.NoError(t, err)
	branchIssueBotActor, err := GetIssueVCSBranchBotActor(context.Background(), graphqlClient, "omer/branch")
	require.NoError(t, err)
	branchIssueChildren, err := ListIssueVCSBranchChildren(context.Background(), graphqlClient, "omer/branch", 2)
	require.NoError(t, err)
	branchIssueDocuments, err := ListIssueVCSBranchDocuments(context.Background(), graphqlClient, "omer/branch", 2)
	require.NoError(t, err)
	branchIssueFormerAttachments, err := ListIssueVCSBranchFormerAttachments(
		context.Background(),
		graphqlClient,
		"omer/branch",
		2,
	)
	require.NoError(t, err)
	branchIssueHistory, err := ListIssueVCSBranchHistory(context.Background(), graphqlClient, "omer/branch", 2)
	require.NoError(t, err)
	branchIssueInverseRelations, err := ListIssueVCSBranchInverseRelations(
		context.Background(),
		graphqlClient,
		"omer/branch",
		2,
	)
	require.NoError(t, err)
	branchIssueLabels, err := ListIssueVCSBranchLabels(context.Background(), graphqlClient, "omer/branch", 2)
	require.NoError(t, err)
	branchIssueRelations, err := ListIssueVCSBranchRelations(context.Background(), graphqlClient, "omer/branch", 2)
	require.NoError(t, err)
	branchIssueReleases, err := ListIssueVCSBranchReleases(context.Background(), graphqlClient, "omer/branch", 2)
	require.NoError(t, err)
	branchIssueStateHistory, err := ListIssueVCSBranchStateHistory(context.Background(), graphqlClient, "omer/branch", 2)
	require.NoError(t, err)
	branchIssueSubscribers, err := ListIssueVCSBranchSubscribers(context.Background(), graphqlClient, "omer/branch", 2)
	require.NoError(t, err)
	projects, err := ListProjectsByTeam(context.Background(), graphqlClient, "team-id", 2)
	require.NoError(t, err)
	project, err := GetProjectByID(context.Background(), graphqlClient, "project-id")
	require.NoError(t, err)
	members, err := ListProjectMembers(context.Background(), graphqlClient, "project-id", 2)
	require.NoError(t, err)
	projectAttachments, err := ListProjectAttachments(context.Background(), graphqlClient, "project-id", 2)
	require.NoError(t, err)
	projectDocuments, err := ListProjectDocuments(context.Background(), graphqlClient, "project-id", 2)
	require.NoError(t, err)
	projectExternalLinks, err := ListProjectExternalLinks(context.Background(), graphqlClient, "project-id", 2)
	require.NoError(t, err)
	projectHistory, err := ListProjectHistory(context.Background(), graphqlClient, "project-id", 2)
	require.NoError(t, err)
	projectInitiativeAssociations, err := ListProjectInitiativeToProjects(
		context.Background(),
		graphqlClient,
		"project-id",
		2,
	)
	require.NoError(t, err)
	projectInitiatives, err := ListProjectInitiatives(context.Background(), graphqlClient, "project-id", 2)
	require.NoError(t, err)
	projectInverseRelations, err := ListProjectInverseRelations(context.Background(), graphqlClient, "project-id", 2)
	require.NoError(t, err)
	scopedProjectIssues, err := ListProjectIssues(context.Background(), graphqlClient, "project-id", 2)
	require.NoError(t, err)
	projectComments, err := ListProjectComments(context.Background(), graphqlClient, "project-id", 2)
	require.NoError(t, err)
	labelsForProject, err := ListLabelsForProject(context.Background(), graphqlClient, "project-id", 2)
	require.NoError(t, err)
	projectNeeds, err := ListProjectNeeds(context.Background(), graphqlClient, "project-id", 2)
	require.NoError(t, err)
	projectScopedRelations, err := ListProjectRelationsForProject(context.Background(), graphqlClient, "project-id", 2)
	require.NoError(t, err)
	projectTeams, err := ListProjectTeams(context.Background(), graphqlClient, "project-id", 2)
	require.NoError(t, err)
	projectUpdates, err := ListProjectUpdates(context.Background(), graphqlClient, "project-id", 2)
	require.NoError(t, err)
	projectFilterSuggestion, err := GetProjectFilterSuggestion(context.Background(), graphqlClient, "started projects", "team-id")
	require.NoError(t, err)
	allProjectUpdates, err := ListAllProjectUpdates(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	projectUpdate, err := GetProjectUpdateByID(context.Background(), graphqlClient, "project-update-id")
	require.NoError(t, err)
	projectUpdateComments, err := ListProjectUpdateComments(context.Background(), graphqlClient, "project-update-id", 2)
	require.NoError(t, err)
	projectMilestones, err := ListProjectMilestones(context.Background(), graphqlClient, "project-id", 2)
	require.NoError(t, err)
	allProjectMilestones, err := ListAllProjectMilestones(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	projectMilestone, err := GetProjectMilestoneByID(context.Background(), graphqlClient, "project-milestone-id")
	require.NoError(t, err)
	projectMilestoneIssues, err := ListProjectMilestoneIssues(context.Background(), graphqlClient, "project-milestone-id", 2)
	require.NoError(t, err)
	workspaceProjects, err := ListProjects(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	projectStatuses, err := ListProjectStatuses(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	projectStatus, err := GetProjectStatusByID(context.Background(), graphqlClient, "project-status-id")
	require.NoError(t, err)
	projectStatusProjectCount, err := GetProjectStatusProjectCount(context.Background(), graphqlClient, "project-status-id")
	require.NoError(t, err)
	projectLabels, err := ListProjectLabels(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	projectLabel, err := GetProjectLabelByID(context.Background(), graphqlClient, "project-label-id")
	require.NoError(t, err)
	projectLabelChildren, err := ListProjectLabelChildren(context.Background(), graphqlClient, "project-label-id", 2)
	require.NoError(t, err)
	projectLabelProjects, err := ListProjectLabelProjects(context.Background(), graphqlClient, "project-label-id", 2)
	require.NoError(t, err)
	projectRelations, err := ListProjectRelations(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	projectRelation, err := GetProjectRelationByID(context.Background(), graphqlClient, "project-relation-id")
	require.NoError(t, err)
	issueRelations, err := ListIssueRelations(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	issueRelation, err := GetIssueRelationByID(context.Background(), graphqlClient, "issue-relation-id")
	require.NoError(t, err)
	issueToReleases, err := ListIssueToReleases(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	issueToRelease, err := GetIssueToReleaseByID(context.Background(), graphqlClient, "issue-to-release-id")
	require.NoError(t, err)

	require.Equal(t, "LIT-20", allTeamIssues.Issues[0].Identifier)
	require.True(t, issues.HasNextPage)
	require.Equal(t, "LIT-10", issues.Issues[0].Identifier)
	require.False(t, startedIssues.HasNextPage)
	require.Equal(t, "started", startedIssues.Issues[0].StateType)
	require.Equal(t, "project-id", projectIssues.Issues[0].ProjectID)
	require.Equal(t, "Omer", mineIssues.Issues[0].Assignee)
	require.Equal(t, "LIT-16", labelIssues.Issues[0].Identifier)
	require.Equal(t, "LIT-17", cycleIssues.Issues[0].Identifier)
	require.Equal(t, "LIT-18", recentIssues.Issues[0].Identifier)
	require.Equal(t, "LIT-19", olderIssues.Issues[0].Identifier)
	require.Equal(t, "LIT-21", blockedIssues.Issues[0].Identifier)
	require.Equal(t, "LIT-22", blockingIssues.Issues[0].Identifier)
	require.Equal(t, "LIT-27", nextIssues.Issues[0].Identifier)
	require.Equal(t, "LIT-23", blockedByIssues.Issues[0].Identifier)
	require.Equal(t, "LIT-1", dependencies.Identifier)
	require.Equal(t, "LIT-25", dependencies.Parent.Identifier)
	require.Equal(t, "LIT-26", dependencies.Children[0].Identifier)
	require.Equal(t, "LIT-23", dependencies.Blocks[0].Identifier)
	require.Equal(t, "LIT-24", dependencies.BlockedBy[0].Identifier)
	require.True(t, dependencies.HasNextPage)
	require.Equal(t, "LIT-13", searchIssues.Issues[0].Identifier)
	require.Equal(t, "LIT-41", figmaIssues.Issues[0].Identifier)
	require.True(t, figmaIssues.HasNextPage)
	require.Equal(t, &endCursor, figmaIssues.EndCursor)
	require.Equal(t, 1, issuePriorityValues[0].Priority)
	require.Equal(t, "Urgent", issuePriorityValues[0].Label)
	require.JSONEq(t, `{"state":{"type":{"eq":"started"}}}`, string(issueFilterSuggestion.Filter))
	require.Equal(t, "issue-filter-log-id", issueFilterSuggestion.LogID)
	require.Equal(t, "Improve exports", issueTitleSuggestion.Title)
	require.Equal(t, "title-log-id", issueTitleSuggestion.LogID)
	require.Equal(t, "LIT-11", issue.Identifier)
	require.True(t, issueAttachments.HasNextPage)
	require.Equal(t, &endCursor, issueAttachments.EndCursor)
	require.Equal(t, "project-attachment-id", issueAttachments.Attachments[0].ID)
	require.Equal(t, "issue-id", issueBotActor.IssueID)
	require.Equal(t, "bot-actor-id", issueBotActor.Bot.ID)
	require.Equal(t, "github", issueBotActor.Bot.Type)
	require.Equal(t, "LIT-31", issueChildren.Issues[0].Identifier)
	require.Equal(t, "Issue spec", issueDocuments.Documents[0].Title)
	require.Equal(t, "issue", issueDocuments.Documents[0].ParentType)
	require.Equal(t, "project-attachment-id", issueFormerAttachments.Attachments[0].ID)
	require.Equal(t, "issue-history-id", issueHistory.History[0].ID)
	require.Equal(t, "issue-id", issueHistory.History[0].IssueID)
	require.Equal(t, "user-id", issueHistory.History[0].ActorID)
	require.True(t, issueHistory.History[0].UpdatedDescription)
	require.Equal(t, "issue-relation-id", issueInverseRelations.Relations[0].ID)
	require.Equal(t, "Bug", issueLabels.Labels[0].Name)
	require.Equal(t, "issue-relation-id", issueScopedRelations.Relations[0].ID)
	require.Equal(t, "release-id", issueReleases.Releases[0].ID)
	require.True(t, issueStateHistory.HasNextPage)
	require.Equal(t, "issue-id", issueStateHistory.IssueID)
	require.Equal(t, "issue-state-span-id", issueStateHistory.Spans[0].ID)
	require.Equal(t, "Started", issueStateHistory.Spans[0].StateName)
	require.Equal(t, "started", issueStateHistory.Spans[0].StateType)
	require.Equal(t, "Omer", issueSubscribers.Users[0].DisplayName)
	require.True(t, issueSubscribers.HasNextPage)
	require.Equal(t, "LIT-40", branchIssue.Identifier)
	require.Equal(t, "project-attachment-id", branchIssueAttachments.Attachments[0].ID)
	require.Equal(t, "issue-id", branchIssueBotActor.IssueID)
	require.Equal(t, "bot-actor-id", branchIssueBotActor.Bot.ID)
	require.Equal(t, "LIT-43", branchIssueChildren.Issues[0].Identifier)
	require.Equal(t, "Branch issue spec", branchIssueDocuments.Documents[0].Title)
	require.Equal(t, "project-attachment-id", branchIssueFormerAttachments.Attachments[0].ID)
	require.Equal(t, "issue-history-id", branchIssueHistory.History[0].ID)
	require.Equal(t, "issue-relation-id", branchIssueInverseRelations.Relations[0].ID)
	require.Equal(t, "Bug", branchIssueLabels.Labels[0].Name)
	require.Equal(t, "issue-relation-id", branchIssueRelations.Relations[0].ID)
	require.Equal(t, "release-id", branchIssueReleases.Releases[0].ID)
	require.Equal(t, "issue-id", branchIssueStateHistory.IssueID)
	require.Equal(t, "issue-state-span-id", branchIssueStateHistory.Spans[0].ID)
	require.Equal(t, "Omer", branchIssueSubscribers.Users[0].DisplayName)
	require.True(t, projects.HasNextPage)
	require.Equal(t, "listed", projects.Projects[0].Name)
	require.Equal(t, "detail", project.Name)
	require.Equal(t, "Omer", members.Members[0].DisplayName)
	require.Equal(t, &endCursor, members.EndCursor)
	require.Equal(t, "project-attachment-id", projectAttachments.Attachments[0].ID)
	require.Equal(t, "github", projectAttachments.Attachments[0].SourceType)
	require.Equal(t, "Project spec", projectDocuments.Documents[0].Title)
	require.Equal(t, "project", projectDocuments.Documents[0].ParentType)
	require.Equal(t, "release-link-id", projectExternalLinks.Links[0].ID)
	require.Equal(t, "Runbook", projectExternalLinks.Links[0].Label)
	require.Equal(t, "project-history-id", projectHistory.History[0].ID)
	require.Equal(t, 1, projectHistory.History[0].EntryCount)
	require.JSONEq(
		t,
		`[{"from":"Backlog","to":"Started","type":"status"}]`,
		string(projectHistory.History[0].Entries),
	)
	require.Equal(t, "initiative-to-project-id", projectInitiativeAssociations.Associations[0].ID)
	require.Equal(t, "Platform", projectInitiativeAssociations.Associations[0].InitiativeName)
	require.Equal(t, "initiative-id", projectInitiatives.Initiatives[0].ID)
	require.Equal(t, "Active", projectInitiatives.Initiatives[0].Status)
	require.Equal(t, "project-relation-id", projectInverseRelations.Relations[0].ID)
	require.Equal(t, "Related project", projectInverseRelations.Relations[0].RelatedProjectName)
	require.Equal(t, "LIT-47", scopedProjectIssues.Issues[0].Identifier)
	require.True(t, projectComments.HasNextPage)
	require.Equal(t, "project-id", projectComments.Comments[0].ProjectID)
	require.Equal(t, "Omer", projectComments.Comments[0].DisplayName)
	require.Empty(t, projectComments.Comments[1].UserID)
	require.Equal(t, &endCursor, projectComments.EndCursor)
	require.Equal(t, "project-label-id", labelsForProject.ProjectLabels[0].ID)
	require.Equal(t, "customer-need-id", projectNeeds.Needs[0].ID)
	require.Equal(t, "Acme", projectNeeds.Needs[0].CustomerName)
	require.Equal(t, "project-relation-id", projectScopedRelations.Relations[0].ID)
	require.Equal(t, "linctl", projectTeams.Teams[0].Name)
	require.True(t, projectUpdates.HasNextPage)
	require.Equal(t, "project-update-id", projectUpdates.Updates[0].ID)
	require.Equal(t, "onTrack", projectUpdates.Updates[0].Health)
	require.Equal(t, "Omer", projectUpdates.Updates[0].DisplayName)
	require.Empty(t, projectUpdates.Updates[0].Body)
	require.Equal(t, &endCursor, projectUpdates.EndCursor)
	require.JSONEq(t, `{"status":{"type":{"eq":"started"}}}`, string(projectFilterSuggestion.Filter))
	require.Equal(t, "filter-log-id", projectFilterSuggestion.LogID)
	require.True(t, allProjectUpdates.HasNextPage)
	require.Equal(t, &endCursor, allProjectUpdates.EndCursor)
	require.Equal(t, "project-id", allProjectUpdates.Updates[0].ProjectID)
	require.Equal(t, "detail", allProjectUpdates.Updates[0].ProjectName)
	require.Equal(t, "project-update-id", projectUpdate.ID)
	require.Equal(t, "detail", projectUpdate.ProjectName)
	require.True(t, projectUpdateComments.HasNextPage)
	require.Equal(t, "project-update-id", projectUpdateComments.ProjectUpdateID)
	require.Equal(t, "project-update-id", projectUpdateComments.Comments[0].ProjectUpdateID)
	require.True(t, projectMilestones.HasNextPage)
	require.Equal(t, "project-milestone-id", projectMilestones.Milestones[0].ID)
	require.Equal(t, "Launch milestone", projectMilestones.Milestones[0].Name)
	require.Equal(t, "milestone body", projectMilestones.Milestones[0].Description)
	require.Equal(t, "2026-06-30", projectMilestones.Milestones[0].TargetDate)
	require.Equal(t, "next", projectMilestones.Milestones[0].Status)
	require.Equal(t, &endCursor, projectMilestones.EndCursor)
	require.True(t, allProjectMilestones.HasNextPage)
	require.Equal(t, "project-milestone-id", allProjectMilestones.Milestones[0].ID)
	require.Equal(t, "project-milestone-id", projectMilestone.ID)
	require.Equal(t, "Launch milestone", projectMilestone.Name)
	require.Equal(t, "next", projectMilestone.Status)
	require.True(t, projectMilestoneIssues.HasNextPage)
	require.Equal(t, "project-milestone-id", projectMilestoneIssues.ProjectMilestoneID)
	require.Equal(t, "LIT-52", projectMilestoneIssues.Issues[0].Identifier)
	require.Equal(t, "workspace-project-id", workspaceProjects.Projects[0].ID)
	require.Equal(t, &endCursor, workspaceProjects.EndCursor)
	require.True(t, projectStatuses.HasNextPage)
	require.Equal(t, &endCursor, projectStatuses.EndCursor)
	require.Equal(t, "project-status-id", projectStatuses.ProjectStatuses[0].ID)
	require.Equal(t, "Backlog", projectStatuses.ProjectStatuses[0].Name)
	require.Equal(t, "backlog", projectStatuses.ProjectStatuses[0].Type)
	require.Equal(t, "#bec2c8", projectStatuses.ProjectStatuses[0].Color)
	require.Equal(t, "project-status-id", projectStatus.ID)
	require.Equal(t, "Ready for planning", projectStatus.Description)
	require.Equal(t, "project-status-id", projectStatusProjectCount.ProjectStatusID)
	require.InEpsilon(t, float64(12), projectStatusProjectCount.Count, 0.001)
	require.InEpsilon(t, float64(2), projectStatusProjectCount.PrivateCount, 0.001)
	require.InEpsilon(t, float64(1), projectStatusProjectCount.ArchivedTeamCount, 0.001)
	require.True(t, projectLabels.HasNextPage)
	require.Equal(t, &endCursor, projectLabels.EndCursor)
	require.Equal(t, "project-label-id", projectLabels.ProjectLabels[0].ID)
	require.Equal(t, "Roadmap", projectLabels.ProjectLabels[0].Name)
	require.Equal(t, "#f2c94c", projectLabels.ProjectLabels[0].Color)
	require.Equal(t, "project-label-id", projectLabel.ID)
	require.Equal(t, "Parent", projectLabel.ParentName)
	require.Equal(t, "project-label-id", projectLabelChildren.ProjectLabelID)
	require.Equal(t, "child-project-label-id", projectLabelChildren.ProjectLabels[0].ID)
	require.Equal(t, "project-id", projectLabelProjects.Projects[0].ID)
	require.True(t, projectRelations.HasNextPage)
	require.Equal(t, &endCursor, projectRelations.EndCursor)
	require.Equal(t, "project-relation-id", projectRelations.Relations[0].ID)
	require.Equal(t, "blocks", projectRelations.Relations[0].Type)
	require.Equal(t, "Pinned project", projectRelations.Relations[0].ProjectName)
	require.Equal(t, "Related project", projectRelations.Relations[0].RelatedProjectName)
	require.Equal(t, "Omer", projectRelations.Relations[0].DisplayName)
	require.Equal(t, "project-milestone-id", projectRelations.Relations[1].ProjectMilestoneID)
	require.Equal(t, "related-project-milestone-id", projectRelations.Relations[1].RelatedProjectMilestoneID)
	require.Empty(t, projectRelations.Relations[1].DisplayName)
	require.Equal(t, "project-relation-id", projectRelation.ID)
	require.Equal(t, "blocks", projectRelation.Type)
	require.True(t, issueRelations.HasNextPage)
	require.Equal(t, &endCursor, issueRelations.EndCursor)
	require.Equal(t, "issue-relation-id", issueRelations.Relations[0].ID)
	require.Equal(t, "blocks", issueRelations.Relations[0].Type)
	require.Equal(t, "LIT-1", issueRelations.Relations[0].IssueIdentifier)
	require.Equal(t, "LIT-2", issueRelations.Relations[0].RelatedIssueIdentifier)
	require.Equal(t, "issue-relation-id", issueRelation.ID)
	require.Equal(t, "related-issue-id", issueRelation.RelatedIssueID)
	require.True(t, issueToReleases.HasNextPage)
	require.Equal(t, &endCursor, issueToReleases.EndCursor)
	require.Equal(t, "issue-to-release-id", issueToReleases.Associations[0].ID)
	require.Equal(t, "issue-id", issueToReleases.Associations[0].IssueID)
	require.Equal(t, "release-id", issueToReleases.Associations[0].ReleaseID)
	require.Equal(t, "issue-to-release-id", issueToRelease.ID)
	require.Equal(t, "release-id", issueToRelease.ReleaseID)
}
