package client

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
)

func Test_ClientReadPlanningAdjacentScenarios_return_compact_lists_details_and_members(t *testing.T) {
	endCursor := "cursor-1"
	graphqlClient := readScenarioGraphQLClient(endCursor)

	initiatives, err := ListInitiatives(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	initiative, err := GetInitiativeByID(context.Background(), graphqlClient, "initiative-id")
	require.NoError(t, err)
	initiativeHistory, err := ListInitiativeHistory(context.Background(), graphqlClient, "initiative-id", 2)
	require.NoError(t, err)
	initiativeLinks, err := ListInitiativeLinks(context.Background(), graphqlClient, "initiative-id", 2)
	require.NoError(t, err)
	subInitiatives, err := ListSubInitiatives(context.Background(), graphqlClient, "initiative-id", 2)
	require.NoError(t, err)
	initiativeScopedUpdates, err := ListInitiativeUpdatesForInitiative(
		context.Background(),
		graphqlClient,
		"initiative-id",
		2,
	)
	require.NoError(t, err)
	initiativeDocuments, err := ListInitiativeDocuments(context.Background(), graphqlClient, "initiative-id", 2)
	require.NoError(t, err)
	initiativeProjects, err := ListInitiativeProjects(context.Background(), graphqlClient, "initiative-id", 2)
	require.NoError(t, err)
	initiativeRelations, err := ListInitiativeRelations(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	initiativeRelation, err := GetInitiativeRelationByID(context.Background(), graphqlClient, "initiative-relation-id")
	require.NoError(t, err)
	initiativeToProjects, err := ListInitiativeToProjects(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	initiativeToProject, err := GetInitiativeToProjectByID(context.Background(), graphqlClient, "initiative-to-project-id")
	require.NoError(t, err)
	roadmapToProjects, err := ListRoadmapToProjects(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	roadmapToProject, err := GetRoadmapToProjectByID(context.Background(), graphqlClient, "roadmap-to-project-id")
	require.NoError(t, err)
	initiativeUpdates, err := ListInitiativeUpdates(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	initiativeUpdate, err := GetInitiativeUpdateByID(context.Background(), graphqlClient, "initiative-update-id")
	require.NoError(t, err)
	initiativeUpdateComments, err := ListInitiativeUpdateComments(
		context.Background(),
		graphqlClient,
		"initiative-update-id",
		2,
	)
	require.NoError(t, err)
	roadmaps, err := ListRoadmaps(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	roadmap, err := GetRoadmapByID(context.Background(), graphqlClient, "roadmap-id")
	require.NoError(t, err)
	roadmapProjects, err := ListRoadmapProjects(context.Background(), graphqlClient, "roadmap-id", 2)
	require.NoError(t, err)
	customViews, err := ListCustomViews(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	customViewSubscribers, err := GetCustomViewSubscriberStatus(context.Background(), graphqlClient, "custom-view-id")
	require.NoError(t, err)
	customView, err := GetCustomViewByID(context.Background(), graphqlClient, "custom-view-id")
	require.NoError(t, err)
	customViewInitiatives, err := ListCustomViewInitiatives(context.Background(), graphqlClient, "custom-view-id", 2)
	require.NoError(t, err)
	customViewIssues, err := ListCustomViewIssues(context.Background(), graphqlClient, "custom-view-id", 2)
	require.NoError(t, err)
	customViewOrganizationPreferences, err := GetCustomViewOrganizationPreferences(
		context.Background(),
		graphqlClient,
		"custom-view-id",
	)
	require.NoError(t, err)
	customViewOrganizationPreferenceValues, err := GetCustomViewOrganizationPreferenceValues(
		context.Background(),
		graphqlClient,
		"custom-view-id",
	)
	require.NoError(t, err)
	customViewProjects, err := ListCustomViewProjects(context.Background(), graphqlClient, "custom-view-id", 2)
	require.NoError(t, err)
	customViewUserPreferences, err := GetCustomViewUserPreferences(context.Background(), graphqlClient, "custom-view-id")
	require.NoError(t, err)
	customViewUserPreferenceValues, err := GetCustomViewUserPreferenceValues(context.Background(), graphqlClient, "custom-view-id")
	require.NoError(t, err)
	customViewPreferenceValues, err := GetCustomViewPreferenceValues(context.Background(), graphqlClient, "custom-view-id")
	require.NoError(t, err)
	customers, err := ListCustomers(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	customer, err := GetCustomerByID(context.Background(), graphqlClient, "customer-id")
	require.NoError(t, err)
	customerNeeds, err := ListCustomerNeeds(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	customerNeed, err := GetCustomerNeedByID(context.Background(), graphqlClient, "customer-need-id")
	require.NoError(t, err)
	customerNeedProjectAttachment, err := GetCustomerNeedProjectAttachment(
		context.Background(),
		graphqlClient,
		"customer-need-id",
	)
	require.NoError(t, err)
	customerStatuses, err := ListCustomerStatuses(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	customerStatus, err := GetCustomerStatusByID(context.Background(), graphqlClient, "customer-status-id")
	require.NoError(t, err)
	customerTiers, err := ListCustomerTiers(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	customerTier, err := GetCustomerTierByID(context.Background(), graphqlClient, "customer-tier-id")
	require.NoError(t, err)
	favorites, err := ListFavorites(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	favoriteChildren, err := ListFavoriteChildren(context.Background(), graphqlClient, "favorite-folder-id", 2)
	require.NoError(t, err)
	favorite, err := GetFavoriteByID(context.Background(), graphqlClient, "favorite-id")
	require.NoError(t, err)
	emojis, err := ListEmojis(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	emoji, err := GetEmojiByID(context.Background(), graphqlClient, "emoji-id")
	require.NoError(t, err)
	attachments, err := ListAttachments(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	attachmentsForURL, err := ListAttachmentsForURL(context.Background(), graphqlClient, "https://example.com/spec", 2)
	require.NoError(t, err)
	attachment, err := GetAttachmentByID(context.Background(), graphqlClient, "attachment-id")
	require.NoError(t, err)
	attachmentIssue, err := GetAttachmentIssue(context.Background(), graphqlClient, "attachment-id")
	require.NoError(t, err)
	attachmentIssueAttachments, err := ListAttachmentIssueAttachments(context.Background(), graphqlClient, "attachment-id", 2)
	require.NoError(t, err)
	attachmentIssueBotActor, err := GetAttachmentIssueBotActor(context.Background(), graphqlClient, "attachment-id")
	require.NoError(t, err)
	attachmentIssueChildren, err := ListAttachmentIssueChildren(context.Background(), graphqlClient, "attachment-id", 2)
	require.NoError(t, err)
	attachmentIssueDocuments, err := ListAttachmentIssueDocuments(context.Background(), graphqlClient, "attachment-id", 2)
	require.NoError(t, err)
	attachmentIssueFormerAttachments, err := ListAttachmentIssueFormerAttachments(
		context.Background(),
		graphqlClient,
		"attachment-id",
		2,
	)
	require.NoError(t, err)
	attachmentIssueHistory, err := ListAttachmentIssueHistory(context.Background(), graphqlClient, "attachment-id", 2)
	require.NoError(t, err)
	attachmentIssueInverseRelations, err := ListAttachmentIssueInverseRelations(
		context.Background(),
		graphqlClient,
		"attachment-id",
		2,
	)
	require.NoError(t, err)
	attachmentIssueLabels, err := ListAttachmentIssueLabels(context.Background(), graphqlClient, "attachment-id", 2)
	require.NoError(t, err)
	attachmentIssueRelations, err := ListAttachmentIssueRelations(context.Background(), graphqlClient, "attachment-id", 2)
	require.NoError(t, err)
	attachmentIssueReleases, err := ListAttachmentIssueReleases(context.Background(), graphqlClient, "attachment-id", 2)
	require.NoError(t, err)
	attachmentIssueStateHistory, err := ListAttachmentIssueStateHistory(context.Background(), graphqlClient, "attachment-id", 2)
	require.NoError(t, err)
	attachmentIssueSubscribers, err := ListAttachmentIssueSubscribers(context.Background(), graphqlClient, "attachment-id", 2)
	require.NoError(t, err)

	require.True(t, initiatives.HasNextPage)
	require.Equal(t, &endCursor, initiatives.EndCursor)
	require.Equal(t, "Platform", initiatives.Initiatives[0].Name)
	require.Equal(t, "Active", initiatives.Initiatives[0].Status)
	require.Equal(t, "2026-12-31", initiatives.Initiatives[0].TargetDate)
	require.Equal(t, "initiative-id", initiative.ID)
	require.Equal(t, "Platform initiative", initiative.Description)
	require.True(t, initiativeHistory.HasNextPage)
	require.Equal(t, &endCursor, initiativeHistory.EndCursor)
	require.Equal(t, "initiative-history-id", initiativeHistory.History[0].ID)
	require.Equal(t, "initiative-id", initiativeHistory.History[0].InitiativeID)
	require.Equal(t, 1, initiativeHistory.History[0].EntryCount)
	require.JSONEq(
		t,
		`[{"from":"Planned","to":"Active","type":"status"}]`,
		string(initiativeHistory.History[0].Entries),
	)
	require.True(t, initiativeLinks.HasNextPage)
	require.Equal(t, &endCursor, initiativeLinks.EndCursor)
	require.Equal(t, "release-link-id", initiativeLinks.Links[0].ID)
	require.Equal(t, "Runbook", initiativeLinks.Links[0].Label)
	require.True(t, subInitiatives.HasNextPage)
	require.Equal(t, "child-initiative-id", subInitiatives.Initiatives[0].ID)
	require.Equal(t, "Child platform", subInitiatives.Initiatives[0].Name)
	require.Equal(t, "Planned", subInitiatives.Initiatives[0].Status)
	require.True(t, initiativeScopedUpdates.HasNextPage)
	require.Equal(t, &endCursor, initiativeScopedUpdates.EndCursor)
	require.Equal(t, "initiative-update-id", initiativeScopedUpdates.Updates[0].ID)
	require.Equal(t, "initiative-id", initiativeScopedUpdates.Updates[0].InitiativeID)
	require.True(t, initiativeDocuments.HasNextPage)
	require.Equal(t, &endCursor, initiativeDocuments.EndCursor)
	require.Equal(t, "initiative-document-id", initiativeDocuments.Documents[0].ID)
	require.Equal(t, "Initiative spec", initiativeDocuments.Documents[0].Title)
	require.True(t, initiativeProjects.HasNextPage)
	require.Equal(t, &endCursor, initiativeProjects.EndCursor)
	require.Equal(t, "initiative-project-id", initiativeProjects.Projects[0].ID)
	require.Equal(t, "Initiative project", initiativeProjects.Projects[0].Name)
	require.True(t, initiativeRelations.HasNextPage)
	require.Equal(t, &endCursor, initiativeRelations.EndCursor)
	require.Equal(t, "initiative-relation-id", initiativeRelations.Relations[0].ID)
	require.Equal(t, "Platform", initiativeRelations.Relations[0].ParentInitiativeName)
	require.Equal(t, "Child initiative", initiativeRelations.Relations[0].RelatedInitiativeName)
	require.Equal(t, "Omer", initiativeRelations.Relations[0].DisplayName)
	require.Empty(t, initiativeRelations.Relations[1].DisplayName)
	require.Equal(t, "initiative-relation-id", initiativeRelation.ID)
	require.InEpsilon(t, 1.5, initiativeRelation.SortOrder, 0)
	require.True(t, initiativeToProjects.HasNextPage)
	require.Equal(t, &endCursor, initiativeToProjects.EndCursor)
	require.Equal(t, "initiative-to-project-id", initiativeToProjects.Associations[0].ID)
	require.Equal(t, "Platform", initiativeToProjects.Associations[0].InitiativeName)
	require.Equal(t, "Pinned project", initiativeToProjects.Associations[0].ProjectName)
	require.Equal(t, "initiative-to-project-id", initiativeToProject.ID)
	require.Equal(t, "project-id", initiativeToProject.ProjectID)
	require.True(t, roadmapToProjects.HasNextPage)
	require.Equal(t, &endCursor, roadmapToProjects.EndCursor)
	require.Equal(t, "roadmap-to-project-id", roadmapToProjects.Associations[0].ID)
	require.Equal(t, "Platform roadmap", roadmapToProjects.Associations[0].RoadmapName)
	require.Equal(t, "Pinned project", roadmapToProjects.Associations[0].ProjectName)
	require.Equal(t, "roadmap-to-project-id", roadmapToProject.ID)
	require.Equal(t, "project-id", roadmapToProject.ProjectID)
	require.True(t, initiativeUpdates.HasNextPage)
	require.Equal(t, &endCursor, initiativeUpdates.EndCursor)
	require.Equal(t, "initiative-update-id", initiativeUpdates.Updates[0].ID)
	require.Equal(t, "Platform", initiativeUpdates.Updates[0].InitiativeName)
	require.Equal(t, 1, initiativeUpdates.Updates[0].CommentCount)
	require.Equal(t, "initiative-update-id", initiativeUpdate.ID)
	require.Equal(t, "First initiative update", initiativeUpdate.Body)
	require.Equal(t, "initiative-update-id", initiativeUpdateComments.InitiativeUpdateID)
	require.Equal(t, "comment-id", initiativeUpdateComments.Comments[0].ID)
	require.Equal(t, &endCursor, initiativeUpdateComments.EndCursor)
	require.True(t, roadmaps.HasNextPage)
	require.Equal(t, &endCursor, roadmaps.EndCursor)
	require.Equal(t, "Platform roadmap", roadmaps.Roadmaps[0].Name)
	require.Equal(t, "roadmap-id", roadmap.ID)
	require.Equal(t, "Owner", roadmap.OwnerDisplayName)
	require.True(t, roadmapProjects.HasNextPage)
	require.Equal(t, "roadmap-id", roadmapProjects.RoadmapID)
	require.Equal(t, "Roadmap project", roadmapProjects.Projects[0].Name)
	require.True(t, customViews.HasNextPage)
	require.Equal(t, &endCursor, customViews.EndCursor)
	require.Equal(t, "My issues", customViews.CustomViews[0].Name)
	require.Equal(t, "Issue", customViews.CustomViews[0].ModelName)
	require.True(t, customViews.CustomViews[0].Shared)
	require.Equal(t, "custom-view-id", customViewSubscribers.ID)
	require.True(t, customViewSubscribers.HasSubscribers)
	require.Equal(t, "custom-view-id", customView.ID)
	require.Equal(t, "Saved issue view", customView.Description)
	require.True(t, customViewInitiatives.HasNextPage)
	require.Equal(t, "Platform", customViewInitiatives.Initiatives[0].Name)
	require.True(t, customViewIssues.HasNextPage)
	require.Equal(t, "LIT-1", customViewIssues.Issues[0].Identifier)
	require.Equal(t, "view-preferences-id", customViewOrganizationPreferences.ID)
	require.Equal(t, "organization", customViewOrganizationPreferences.Type)
	require.Equal(t, "list", customViewOrganizationPreferences.Values.Layout)
	require.True(t, customViewOrganizationPreferenceValues.HasOrganizationPreferences)
	require.Equal(t, "priority", customViewOrganizationPreferenceValues.ViewOrdering)
	require.True(t, customViewOrganizationPreferenceValues.ShowArchivedItems)
	require.Equal(t, []string{"column-id"}, customViewOrganizationPreferenceValues.HiddenColumns)
	require.True(t, customViewProjects.HasNextPage)
	require.Equal(t, "Custom view project", customViewProjects.Projects[0].Name)
	require.Equal(t, "view-preferences-id", customViewUserPreferences.ID)
	require.Equal(t, "user", customViewUserPreferences.Type)
	require.True(t, customViewUserPreferenceValues.HasUserPreferences)
	require.Equal(t, "updatedAt", customViewUserPreferenceValues.ViewOrdering)
	require.True(t, customViewPreferenceValues.HasEffectivePreferenceValue)
	require.Equal(t, "board", customViewPreferenceValues.Layout)
	require.Equal(t, "updatedAt", customViewPreferenceValues.ViewOrdering)
	require.True(t, customers.HasNextPage)
	require.Equal(t, &endCursor, customers.EndCursor)
	require.Equal(t, "Acme", customers.Customers[0].Name)
	require.Equal(t, "Active", customers.Customers[0].StatusName)
	require.InDelta(t, 3, customers.Customers[0].ApproximateNeedCount, 0)
	require.Equal(t, "customer-id", customer.ID)
	require.Equal(t, "Enterprise", customer.TierName)
	require.Equal(t, "Omer", customer.OwnerDisplayName)
	require.True(t, customerNeeds.HasNextPage)
	require.Equal(t, &endCursor, customerNeeds.EndCursor)
	require.Equal(t, "Acme", customerNeeds.Needs[0].CustomerName)
	require.Equal(t, "LIT-1", customerNeed.Issue)
	require.Equal(t, "Need content", customerNeed.Content)
	require.Equal(t, "customer-need-id", customerNeedProjectAttachment.CustomerNeedID)
	require.NotNil(t, customerNeedProjectAttachment.Attachment)
	require.Equal(t, "project-attachment-id", customerNeedProjectAttachment.Attachment.ID)
	require.True(t, customerStatuses.HasNextPage)
	require.Equal(t, &endCursor, customerStatuses.EndCursor)
	require.Equal(t, "Active", customerStatuses.Statuses[0].DisplayName)
	require.Equal(t, "customer-status-id", customerStatus.ID)
	require.Equal(t, "#00ff00", customerStatus.Color)
	require.True(t, customerTiers.HasNextPage)
	require.Equal(t, &endCursor, customerTiers.EndCursor)
	require.Equal(t, "Enterprise", customerTiers.Tiers[0].DisplayName)
	require.Equal(t, "customer-tier-id", customerTier.ID)
	require.Equal(t, "#0000ff", customerTier.Color)
	require.True(t, favorites.HasNextPage)
	require.Equal(t, &endCursor, favorites.EndCursor)
	require.Equal(t, "issue", favorites.Favorites[0].Type)
	require.True(t, favoriteChildren.HasNextPage)
	require.Equal(t, &endCursor, favoriteChildren.EndCursor)
	require.Equal(t, "favorite-child-id", favoriteChildren.Favorites[0].ID)
	require.Equal(t, "project", favoriteChildren.Favorites[0].Type)
	require.Equal(t, "favorite-id", favorite.ID)
	require.Equal(t, "https://linear.app/kyanite/issue/LIT-1", favorite.URL)
	require.True(t, emojis.HasNextPage)
	require.Equal(t, &endCursor, emojis.EndCursor)
	require.Equal(t, "party", emojis.Emojis[0].Name)
	require.Equal(t, "custom", emojis.Emojis[0].Source)
	require.Equal(t, "emoji-id", emoji.ID)
	require.Equal(t, "party", emoji.Name)
	require.True(t, attachments.HasNextPage)
	require.Equal(t, &endCursor, attachments.EndCursor)
	require.Equal(t, "Linked PR", attachments.Attachments[0].Title)
	require.Equal(t, "github", attachments.Attachments[0].SourceType)
	require.True(t, attachmentsForURL.HasNextPage)
	require.Equal(t, &endCursor, attachmentsForURL.EndCursor)
	require.Equal(t, "Linked URL", attachmentsForURL.Attachments[0].Title)
	require.Equal(t, "url", attachmentsForURL.Attachments[0].SourceType)
	require.Equal(t, "attachment-id", attachment.ID)
	require.Equal(t, "feat: add thing", attachment.Subtitle)
	require.Equal(t, "LIT-41", attachmentIssue.Identifier)
	require.Equal(t, "project-attachment-id", attachmentIssueAttachments.Attachments[0].ID)
	require.Equal(t, "issue-id", attachmentIssueBotActor.IssueID)
	require.Equal(t, "bot-actor-id", attachmentIssueBotActor.Bot.ID)
	require.Equal(t, "LIT-42", attachmentIssueChildren.Issues[0].Identifier)
	require.Equal(t, "Attachment issue spec", attachmentIssueDocuments.Documents[0].Title)
	require.Equal(t, "project-attachment-id", attachmentIssueFormerAttachments.Attachments[0].ID)
	require.Equal(t, "issue-history-id", attachmentIssueHistory.History[0].ID)
	require.Equal(t, "issue-relation-id", attachmentIssueInverseRelations.Relations[0].ID)
	require.Equal(t, "Bug", attachmentIssueLabels.Labels[0].Name)
	require.Equal(t, "issue-relation-id", attachmentIssueRelations.Relations[0].ID)
	require.Equal(t, "release-id", attachmentIssueReleases.Releases[0].ID)
	require.Equal(t, "issue-id", attachmentIssueStateHistory.IssueID)
	require.Equal(t, "issue-state-span-id", attachmentIssueStateHistory.Spans[0].ID)
	require.Equal(t, "Omer", attachmentIssueSubscribers.Users[0].DisplayName)
}
