package client

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
)

func Test_ClientReadCoreSearchReleaseScenarios_return_compact_lists_details_and_members(t *testing.T) {
	endCursor := "cursor-1"
	graphqlClient := readScenarioGraphQLClient(endCursor)

	application, err := GetApplicationInfo(context.Background(), graphqlClient, "app-client-id")
	require.NoError(t, err)
	agentActivities, err := ListAgentActivities(context.Background(), graphqlClient, 6)
	require.NoError(t, err)
	agentActivity, err := GetAgentActivityByID(context.Background(), graphqlClient, "agent-activity-id")
	require.NoError(t, err)
	agentSkills, err := ListAgentSkills(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	agentSkill, err := GetAgentSkillByID(context.Background(), graphqlClient, "agent-skill-id")
	require.NoError(t, err)
	externalUsers, err := ListExternalUsers(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	externalUser, err := GetExternalUserByID(context.Background(), graphqlClient, "external-user-id")
	require.NoError(t, err)
	auditEntryTypes, err := ListAuditEntryTypes(context.Background(), graphqlClient)
	require.NoError(t, err)
	comments, err := ListIssueComments(context.Background(), graphqlClient, "LIT-12", 2)
	require.NoError(t, err)
	topLevelComments, err := ListComments(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	topLevelComment, err := GetCommentByID(context.Background(), graphqlClient, "comment-id")
	require.NoError(t, err)
	commentBotActor, err := GetCommentBotActor(context.Background(), graphqlClient, "comment-id")
	require.NoError(t, err)
	commentChildren, err := ListCommentChildren(context.Background(), graphqlClient, "comment-id", 1)
	require.NoError(t, err)
	commentCreatedIssues, err := ListCommentCreatedIssues(context.Background(), graphqlClient, "comment-id", 1)
	require.NoError(t, err)
	documents, err := ListDocuments(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	document, err := GetDocumentByID(context.Background(), graphqlClient, "document-id")
	require.NoError(t, err)
	documentComments, err := ListDocumentComments(context.Background(), graphqlClient, "document-id", 2)
	require.NoError(t, err)
	labels, err := ListLabels(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	label, err := GetLabelByID(context.Background(), graphqlClient, "label-id")
	require.NoError(t, err)
	labelChildren, err := ListLabelChildren(context.Background(), graphqlClient, "label-id", 2)
	require.NoError(t, err)
	labelScopedIssues, err := ListLabelIssues(context.Background(), graphqlClient, "label-id", 2)
	require.NoError(t, err)
	teams, err := ListTeams(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	teamMemberships, err := ListTeamMemberships(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	teamMembership, err := GetTeamMembershipByID(context.Background(), graphqlClient, "team-membership-id")
	require.NoError(t, err)
	organizationExists, err := CheckOrganizationExists(context.Background(), graphqlClient, "kyanite")
	require.NoError(t, err)
	rateLimitStatus, err := GetRateLimitStatus(context.Background(), graphqlClient)
	require.NoError(t, err)
	notifications, err := ListNotifications(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	notification, err := GetNotificationByID(context.Background(), graphqlClient, "notification-id")
	require.NoError(t, err)
	notificationSubscriptions, err := ListNotificationSubscriptions(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	notificationSubscription, err := GetNotificationSubscriptionByID(
		context.Background(),
		graphqlClient,
		"notification-subscription-id",
	)
	require.NoError(t, err)
	triageResponsibilities, err := ListTriageResponsibilities(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	triageResponsibility, err := GetTriageResponsibilityByID(
		context.Background(),
		graphqlClient,
		"triage-responsibility-id",
	)
	require.NoError(t, err)
	triageManualSelection, err := GetTriageResponsibilityManualSelection(
		context.Background(),
		graphqlClient,
		"triage-responsibility-id",
	)
	require.NoError(t, err)
	slaConfigurations, err := ListSLAConfigurations(context.Background(), graphqlClient, "team-id")
	require.NoError(t, err)
	semanticSearch, err := SearchSemantic(context.Background(), graphqlClient, "agent search", 2)
	require.NoError(t, err)
	documentSearch, err := SearchDocuments(context.Background(), graphqlClient, "agent search", 2)
	require.NoError(t, err)
	issueSearch, err := SearchIssues(context.Background(), graphqlClient, "agent search", 2)
	require.NoError(t, err)
	projectSearch, err := SearchProjects(context.Background(), graphqlClient, "agent search", 2)
	require.NoError(t, err)
	releasePipelines, err := ListReleasePipelines(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	releasePipeline, err := GetReleasePipelineByID(context.Background(), graphqlClient, "release-pipeline-id")
	require.NoError(t, err)
	releasePipelineReleases, err := ListReleasePipelineReleases(context.Background(), graphqlClient, "release-pipeline-id", 2)
	require.NoError(t, err)
	releasePipelineStages, err := ListReleasePipelineStages(context.Background(), graphqlClient, "release-pipeline-id", 2)
	require.NoError(t, err)
	releasePipelineTeams, err := ListReleasePipelineTeams(context.Background(), graphqlClient, "release-pipeline-id", 2)
	require.NoError(t, err)
	releaseStages, err := ListReleaseStages(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	releaseStage, err := GetReleaseStageByID(context.Background(), graphqlClient, "release-stage-id")
	require.NoError(t, err)
	releaseStageReleases, err := ListReleaseStageReleases(context.Background(), graphqlClient, "release-stage-id", 2)
	require.NoError(t, err)
	releases, err := ListReleases(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	release, err := GetReleaseByID(context.Background(), graphqlClient, "release-id")
	require.NoError(t, err)
	releaseDocuments, err := ListReleaseDocuments(context.Background(), graphqlClient, "release-id", 2)
	require.NoError(t, err)
	releaseIssues, err := ListReleaseIssues(context.Background(), graphqlClient, "release-id", 2)
	require.NoError(t, err)
	releaseHistory, err := ListReleaseHistory(context.Background(), graphqlClient, "release-id", 2)
	require.NoError(t, err)
	releaseLinks, err := ListReleaseLinks(context.Background(), graphqlClient, "release-id", 2)
	require.NoError(t, err)
	externalLink, err := GetEntityExternalLinkByID(context.Background(), graphqlClient, "release-link-id")
	require.NoError(t, err)
	releaseSearch, err := SearchReleases(context.Background(), graphqlClient, "mobile", 2)
	require.NoError(t, err)
	releaseNotes, err := ListReleaseNotes(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	releaseNote, err := GetReleaseNoteByID(context.Background(), graphqlClient, "release-note-id")
	require.NoError(t, err)
	team, err := GetTeamByID(context.Background(), graphqlClient, "team-id")
	require.NoError(t, err)
	teamMembers, err := ListTeamMembers(context.Background(), graphqlClient, "team-id", 2)
	require.NoError(t, err)
	teamCycles, err := ListTeamCycles(context.Background(), graphqlClient, "team-id", 2)
	require.NoError(t, err)
	teamIssues, err := ListTeamIssues(context.Background(), graphqlClient, "team-id", 2)
	require.NoError(t, err)
	teamLabels, err := ListTeamLabels(context.Background(), graphqlClient, "team-id", 2)
	require.NoError(t, err)
	teamScopedMemberships, err := ListTeamMembershipsForTeam(context.Background(), graphqlClient, "team-id", 2)
	require.NoError(t, err)
	teamProjects, err := ListTeamProjects(context.Background(), graphqlClient, "team-id", 2)
	require.NoError(t, err)
	teamReleasePipelines, err := ListTeamReleasePipelines(context.Background(), graphqlClient, "team-id", 2)
	require.NoError(t, err)
	teamWorkflowStates, err := ListTeamWorkflowStates(context.Background(), graphqlClient, "team-id", 2)
	require.NoError(t, err)
	teamGitAutomationStates, err := ListTeamGitAutomationStates(context.Background(), graphqlClient, "team-id", 2)
	require.NoError(t, err)
	teamTemplates, err := ListTeamTemplates(context.Background(), graphqlClient, "team-id", 2)
	require.NoError(t, err)
	users, err := ListUsers(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	user, err := GetUserByID(context.Background(), graphqlClient, "user-id")
	require.NoError(t, err)
	viewerUser, err := GetViewerUser(context.Background(), graphqlClient)
	require.NoError(t, err)
	drafts, err := ListViewerDrafts(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	userAssignedIssues, err := ListUserAssignedIssues(context.Background(), graphqlClient, "user-id", 2)
	require.NoError(t, err)
	userCreatedIssues, err := ListUserCreatedIssues(context.Background(), graphqlClient, "user-id", 2)
	require.NoError(t, err)
	userDelegatedIssues, err := ListUserDelegatedIssues(context.Background(), graphqlClient, "user-id", 2)
	require.NoError(t, err)
	userTeamMemberships, err := ListUserTeamMemberships(context.Background(), graphqlClient, "user-id", 2)
	require.NoError(t, err)
	userTeams, err := ListUserTeams(context.Background(), graphqlClient, "user-id", 2)
	require.NoError(t, err)
	viewerAssignedIssues, err := ListViewerAssignedIssues(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	viewerCreatedIssues, err := ListViewerCreatedIssues(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	viewerDelegatedIssues, err := ListViewerDelegatedIssues(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	viewerTeamMemberships, err := ListViewerTeamMemberships(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	viewerTeams, err := ListViewerTeams(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	workflowStates, err := ListWorkflowStates(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	workflowState, err := GetWorkflowStateByID(context.Background(), graphqlClient, "workflow-state-id")
	require.NoError(t, err)
	workflowStateIssues, err := ListWorkflowStateIssues(context.Background(), graphqlClient, "workflow-state-id", 2)
	require.NoError(t, err)
	timeSchedules, err := ListTimeSchedules(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	timeSchedule, err := GetTimeScheduleByID(context.Background(), graphqlClient, "time-schedule-id")
	require.NoError(t, err)
	organizationLabels, err := ListOrganizationLabels(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	organizationProjectLabels, err := ListOrganizationProjectLabels(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	organizationTeams, err := ListOrganizationTeams(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	organizationTemplates, err := ListOrganizationTemplates(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	organizationUsers, err := ListOrganizationUsers(context.Background(), graphqlClient, 2)
	require.NoError(t, err)
	templates, err := ListTemplates(context.Background(), graphqlClient, 1)
	require.NoError(t, err)
	template, err := GetTemplateByID(context.Background(), graphqlClient, "template-id")
	require.NoError(t, err)

	require.Equal(t, "app-id", application.ID)
	require.Equal(t, "app-client-id", application.ClientID)
	require.Equal(t, "Demo App", application.Name)
	require.Equal(t, "Kyanite", application.Developer)
	require.True(t, agentActivities.HasNextPage)
	require.Equal(t, &endCursor, agentActivities.EndCursor)
	require.Equal(t, "action", agentActivities.AgentActivities[0].ContentType)
	require.Equal(t, "elicitation", agentActivities.AgentActivities[1].ContentType)
	require.Equal(t, "error", agentActivities.AgentActivities[2].ContentType)
	require.Equal(t, "prompt", agentActivities.AgentActivities[3].ContentType)
	require.Equal(t, "response", agentActivities.AgentActivities[4].ContentType)
	require.Equal(t, "thought", agentActivities.AgentActivities[5].ContentType)
	require.Equal(t, "agent-activity-id", agentActivity.ID)
	require.Equal(t, "agent-session-id", agentActivity.AgentSessionID)
	require.Equal(t, "comment-id", agentActivity.SourceCommentID)
	require.Equal(t, "read_file", agentActivity.Content.Action)
	require.Empty(t, agentActivityContentSummary(nil).Type)
	require.True(t, agentSkills.HasNextPage)
	require.Equal(t, &endCursor, agentSkills.EndCursor)
	require.Equal(t, "agent-skill-id", agentSkills.AgentSkills[0].ID)
	require.Equal(t, "Triage Helper", agentSkills.AgentSkills[0].Title)
	require.Equal(t, "agent-skill-id", agentSkill.ID)
	require.Equal(t, "updater-id", agentSkill.LastUpdatedByID)
	require.True(t, externalUsers.HasNextPage)
	require.Equal(t, &endCursor, externalUsers.EndCursor)
	require.Equal(t, "external-user-id", externalUsers.ExternalUsers[0].ID)
	require.Equal(t, "@external", externalUsers.ExternalUsers[0].DisplayName)
	require.Equal(t, "https://example.com/avatar.png", externalUsers.ExternalUsers[0].AvatarURL)
	require.Equal(t, "external-user-id", externalUser.ID)
	require.Equal(t, "2026-06-19T12:00:00Z", externalUser.LastSeen)
	require.Equal(t, "user_login", auditEntryTypes.AuditEntryTypes[0].Type)
	require.Equal(t, "User logged in", auditEntryTypes.AuditEntryTypes[0].Description)
	require.Equal(t, "LIT-12", comments.Identifier)
	require.True(t, comments.HasNextPage)
	require.Equal(t, &endCursor, comments.EndCursor)
	require.Equal(t, "parent-id", comments.Comments[0].ParentID)
	require.Equal(t, "Omer", comments.Comments[0].DisplayName)
	require.Empty(t, comments.Comments[1].UserID)
	require.Empty(t, comments.Comments[1].ParentID)
	require.True(t, topLevelComments.HasNextPage)
	require.Equal(t, &endCursor, topLevelComments.EndCursor)
	require.Equal(t, "parent-id", topLevelComments.Comments[0].ParentID)
	require.Equal(t, "issue-id", topLevelComments.Comments[0].IssueID)
	require.Equal(t, "Omer", topLevelComments.Comments[0].DisplayName)
	require.Equal(t, "project-id", topLevelComments.Comments[1].ProjectID)
	require.Empty(t, topLevelComments.Comments[1].UserID)
	require.Equal(t, "comment-id", topLevelComment.ID)
	require.Equal(t, "issue-id", topLevelComment.IssueID)
	require.Equal(t, "Omer", topLevelComment.DisplayName)
	require.Equal(t, "comment-id", commentBotActor.CommentID)
	require.Equal(t, "bot-actor-id", commentBotActor.Bot.ID)
	require.Equal(t, "github", commentBotActor.Bot.Type)
	require.Equal(t, "GitHub", commentBotActor.Bot.Name)
	require.True(t, commentChildren.HasNextPage)
	require.Equal(t, "comment-id", commentChildren.CommentID)
	require.Equal(t, "child-comment-id", commentChildren.Comments[0].ID)
	require.Equal(t, "comment-id", commentChildren.Comments[0].ParentID)
	require.True(t, commentCreatedIssues.HasNextPage)
	require.Equal(t, "LIT-54", commentCreatedIssues.Issues[0].Identifier)
	require.True(t, documents.HasNextPage)
	require.Equal(t, "project", documents.Documents[0].ParentType)
	require.Equal(t, "Team note", document.Title)
	require.Equal(t, "team", document.ParentType)
	require.Equal(t, "document-id", documentComments.DocumentID)
	require.Equal(t, "comment-id", documentComments.Comments[0].ID)
	require.Equal(t, &endCursor, documentComments.EndCursor)
	require.True(t, labels.HasNextPage)
	require.Equal(t, "Bug", labels.Labels[0].Name)
	require.Equal(t, "LIT", labels.Labels[0].TeamKey)
	require.Equal(t, "label-id", label.ID)
	require.Empty(t, label.Description)
	require.Equal(t, "child-label-id", labelChildren.Labels[0].ID)
	require.Equal(t, "Mobile", labelChildren.Labels[0].Name)
	require.Equal(t, &endCursor, labelChildren.EndCursor)
	require.Equal(t, "LIT-53", labelScopedIssues.Issues[0].Identifier)
	require.Equal(t, "Label issue", labelScopedIssues.Issues[0].Title)
	require.Equal(t, &endCursor, labelScopedIssues.EndCursor)
	require.True(t, teams.HasNextPage)
	require.True(t, teamMemberships.HasNextPage)
	require.Equal(t, &endCursor, teamMemberships.EndCursor)
	require.Equal(t, "team-membership-id", teamMemberships.Memberships[0].ID)
	require.Equal(t, "team-id", teamMemberships.Memberships[0].TeamID)
	require.Equal(t, "LIT", teamMemberships.Memberships[0].TeamKey)
	require.Equal(t, "user-id", teamMemberships.Memberships[0].UserID)
	require.Equal(t, "Omer", teamMemberships.Memberships[0].DisplayName)
	require.True(t, teamMemberships.Memberships[0].Owner)
	require.InEpsilon(t, 1.5, teamMemberships.Memberships[0].SortOrder, 0)
	require.True(t, teamCycles.HasNextPage)
	require.Equal(t, &endCursor, teamCycles.EndCursor)
	require.Equal(t, "cycle-id", teamCycles.Cycles[0].ID)
	require.Equal(t, "LIT-1", teamIssues.Issues[0].Identifier)
	require.Equal(t, "label-id", teamLabels.Labels[0].ID)
	require.Equal(t, "team-membership-id", teamScopedMemberships.Memberships[0].ID)
	require.Equal(t, "Team project", teamProjects.Projects[0].Name)
	require.Equal(t, "release-pipeline-id", teamReleasePipelines.ReleasePipelines[0].ID)
	require.Equal(t, "workflow-state-id", teamWorkflowStates.WorkflowStates[0].ID)
	require.Equal(t, "git-automation-state-id", teamGitAutomationStates.States[0].ID)
	require.Equal(t, "review", teamGitAutomationStates.States[0].Event)
	require.Equal(t, "Started", teamGitAutomationStates.States[0].StateName)
	require.Equal(t, "main", teamGitAutomationStates.States[0].TargetBranchPattern)
	require.Equal(t, "template-id", teamTemplates.Templates[0].ID)
	require.Equal(t, "team-membership-id", teamMembership.ID)
	require.Equal(t, "omer@example.com", teamMembership.Email)
	require.Equal(t, "LIT", teams.Teams[0].Key)
	require.Equal(t, "kyanite", organizationExists.URLKey)
	require.True(t, organizationExists.Success)
	require.True(t, organizationExists.Exists)
	require.Equal(t, "api-key", rateLimitStatus.Identifier)
	require.Equal(t, "api", rateLimitStatus.Kind)
	require.Equal(t, "complexity", rateLimitStatus.Limits[0].Type)
	require.InDelta(t, 900, rateLimitStatus.Limits[0].RemainingAmount, 0)
	require.True(t, notifications.HasNextPage)
	require.Equal(t, &endCursor, notifications.EndCursor)
	require.Equal(t, "Mentioned you", notifications.Notifications[0].Title)
	require.Equal(t, "mentions", notifications.Notifications[0].Category)
	require.Equal(t, "actor-id", notifications.Notifications[0].ActorID)
	require.Equal(t, "external-user-id", notification.ExternalUserActorID)
	require.True(t, notificationSubscriptions.HasNextPage)
	require.Equal(t, &endCursor, notificationSubscriptions.EndCursor)
	require.Equal(t, "project", notificationSubscriptions.Subscriptions[0].TargetType)
	require.Equal(t, "Roadmap", notificationSubscriptions.Subscriptions[0].TargetName)
	require.Equal(t, "customer", notificationSubscriptions.Subscriptions[1].TargetType)
	require.Equal(t, "custom_view", notificationSubscriptions.Subscriptions[2].TargetType)
	require.Equal(t, "Cycle 7", notificationSubscriptions.Subscriptions[3].TargetName)
	require.Equal(t, "initiative", notificationSubscriptions.Subscriptions[4].TargetType)
	require.Equal(t, "label", notificationSubscriptions.Subscriptions[5].TargetType)
	require.Equal(t, "backlog", notificationSubscriptions.Subscriptions[6].ContextViewType)
	require.Equal(t, "LIT", notificationSubscriptions.Subscriptions[6].TargetName)
	require.Equal(t, "assigned", notificationSubscriptions.Subscriptions[7].UserContextViewType)
	require.Equal(t, "Ada", notificationSubscriptions.Subscriptions[7].TargetName)
	require.Equal(t, "project-id", notificationSubscription.TargetID)
	require.True(t, triageResponsibilities.HasNextPage)
	require.Equal(t, &endCursor, triageResponsibilities.EndCursor)
	require.Equal(t, "notify", triageResponsibilities.TriageResponsibilities[0].Action)
	require.Equal(t, "LIT", triageResponsibilities.TriageResponsibilities[0].TeamKey)
	require.Equal(t, "Primary rotation", triageResponsibilities.TriageResponsibilities[0].TimeScheduleName)
	require.Equal(t, "Omer", triageResponsibilities.TriageResponsibilities[0].CurrentUserName)
	require.Equal(t, []string{"user-id", "other-user-id"}, triageResponsibility.ManualUserIDs)
	require.Equal(t, []string{"user-id", "other-user-id"}, triageManualSelection.UserIDs)
	require.Equal(t, "team-id", slaConfigurations.TeamIDOrKey)
	require.Equal(t, "First response", slaConfigurations.SLAConfigurations[0].Name)
	require.InDelta(t, 3600000, slaConfigurations.SLAConfigurations[0].SLA, 0)
	require.Equal(t, "all", slaConfigurations.SLAConfigurations[0].SLAType)
	require.False(t, slaConfigurations.SLAConfigurations[0].RemovesSLA)
	require.Len(t, semanticSearch.Results, 5)
	require.Equal(t, "issue", semanticSearch.Results[0].Type)
	require.Equal(t, "issue-id", semanticSearch.Results[0].ID)
	require.Equal(t, "LIT-3", semanticSearch.Results[0].Key)
	require.Equal(t, "Search result", semanticSearch.Results[0].Title)
	require.Equal(t, "project", semanticSearch.Results[1].Type)
	require.Equal(t, "Search project", semanticSearch.Results[1].Title)
	require.Equal(t, "initiative", semanticSearch.Results[2].Type)
	require.Equal(t, "Search initiative", semanticSearch.Results[2].Title)
	require.Equal(t, "document", semanticSearch.Results[3].Type)
	require.Equal(t, "Search document", semanticSearch.Results[3].Title)
	require.Equal(t, "unknown-id", semanticSearch.Results[4].ID)
	require.Empty(t, semanticSearch.Results[4].Title)
	require.True(t, documentSearch.HasNextPage)
	require.Equal(t, &endCursor, documentSearch.EndCursor)
	require.Len(t, documentSearch.Documents, 6)
	require.Equal(t, "search-document-id", documentSearch.Documents[0].ID)
	require.Equal(t, "team", documentSearch.Documents[0].ParentType)
	require.Equal(t, "linctl", documentSearch.Documents[0].ParentName)
	require.Equal(t, "project", documentSearch.Documents[1].ParentType)
	require.Equal(t, "initiative", documentSearch.Documents[2].ParentType)
	require.Equal(t, "issue", documentSearch.Documents[3].ParentType)
	require.Equal(t, "release", documentSearch.Documents[4].ParentType)
	require.Equal(t, "cycle", documentSearch.Documents[5].ParentType)
	require.True(t, issueSearch.HasNextPage)
	require.Equal(t, &endCursor, issueSearch.EndCursor)
	require.Equal(t, "LIT-30", issueSearch.Issues[0].Identifier)
	require.Equal(t, "Pinned project", issueSearch.Issues[0].ProjectName)
	require.True(t, projectSearch.HasNextPage)
	require.Equal(t, &endCursor, projectSearch.EndCursor)
	require.Equal(t, "search-project-id", projectSearch.Projects[0].ID)
	require.Equal(t, "Search project", projectSearch.Projects[0].Name)
	require.Equal(t, "Omer", projectSearch.Projects[0].Lead)
	require.True(t, releasePipelines.HasNextPage)
	require.Equal(t, &endCursor, releasePipelines.EndCursor)
	require.Equal(t, "Production", releasePipelines.ReleasePipelines[0].Name)
	require.Equal(t, "scheduled", releasePipelines.ReleasePipelines[0].Type)
	require.True(t, releasePipeline.IsProduction)
	require.Equal(t, "template-id", releasePipeline.ReleaseNoteTemplateID)
	require.True(t, releasePipelineReleases.HasNextPage)
	require.Equal(t, &endCursor, releasePipelineReleases.EndCursor)
	require.Equal(t, "release-id", releasePipelineReleases.Releases[0].ID)
	require.Equal(t, "Production", releasePipelineReleases.Releases[0].PipelineName)
	require.True(t, releasePipelineStages.HasNextPage)
	require.Equal(t, &endCursor, releasePipelineStages.EndCursor)
	require.Equal(t, "release-stage-id", releasePipelineStages.ReleaseStages[0].ID)
	require.Equal(t, "Production", releasePipelineStages.ReleaseStages[0].PipelineName)
	require.True(t, releasePipelineTeams.HasNextPage)
	require.Equal(t, &endCursor, releasePipelineTeams.EndCursor)
	require.Equal(t, "LIT", releasePipelineTeams.Teams[0].Key)
	require.Equal(t, "Kyanite", releasePipelineTeams.Teams[0].OrgName)
	require.True(t, releaseStages.HasNextPage)
	require.Equal(t, &endCursor, releaseStages.EndCursor)
	require.Equal(t, "Started", releaseStages.ReleaseStages[0].Name)
	require.Equal(t, "started", releaseStages.ReleaseStages[0].Type)
	require.Equal(t, "Production", releaseStage.PipelineName)
	require.True(t, releaseStageReleases.HasNextPage)
	require.Equal(t, &endCursor, releaseStageReleases.EndCursor)
	require.Equal(t, "release-id", releaseStageReleases.Releases[0].ID)
	require.Equal(t, "release-stage-id", releaseStageReleases.Releases[0].StageID)
	require.True(t, releases.HasNextPage)
	require.Equal(t, &endCursor, releases.EndCursor)
	require.Equal(t, "Mobile 1.2.3", releases.Releases[0].Name)
	require.Equal(t, "Started", releases.Releases[0].StageName)
	require.Equal(t, "v1.2.3", release.Version)
	require.Equal(t, "Omer", release.CreatorName)
	require.True(t, releaseDocuments.HasNextPage)
	require.Equal(t, "Release spec", releaseDocuments.Documents[0].Title)
	require.Equal(t, "project", releaseDocuments.Documents[0].ParentType)
	require.True(t, releaseIssues.HasNextPage)
	require.Equal(t, "LIT-48", releaseIssues.Issues[0].Identifier)
	require.Equal(t, "Release issue", releaseIssues.Issues[0].Title)
	require.Equal(t, 1, release.ReleaseNoteCount)
	require.True(t, releaseHistory.HasNextPage)
	require.Equal(t, &endCursor, releaseHistory.EndCursor)
	require.Equal(t, "release-history-id", releaseHistory.History[0].ID)
	require.Equal(t, "release-id", releaseHistory.History[0].ReleaseID)
	require.Equal(t, 1, releaseHistory.History[0].EntryCount)
	require.JSONEq(t, `[{"from":"planned","to":"started","type":"stage"}]`, string(releaseHistory.History[0].Entries))
	require.True(t, releaseLinks.HasNextPage)
	require.Equal(t, &endCursor, releaseLinks.EndCursor)
	require.Equal(t, "release-link-id", releaseLinks.Links[0].ID)
	require.Equal(t, "Runbook", releaseLinks.Links[0].Label)
	require.Equal(t, "https://example.com/runbook", releaseLinks.Links[0].URL)
	require.Equal(t, "user-id", releaseLinks.Links[0].CreatorID)
	require.Equal(t, "initiative-id", releaseLinks.Links[1].InitiativeID)
	require.Equal(t, "Platform", releaseLinks.Links[1].InitiativeName)
	require.Equal(t, "project-id", releaseLinks.Links[1].ProjectID)
	require.Equal(t, "Pinned project", releaseLinks.Links[1].ProjectName)
	require.Equal(t, "release-link-id", externalLink.ID)
	require.Equal(t, "Runbook", externalLink.Label)
	require.Equal(t, "https://example.com/runbook", externalLink.URL)
	require.Equal(t, "release-id", releaseSearch.Releases[0].ID)
	require.True(t, releaseNotes.HasNextPage)
	require.Equal(t, &endCursor, releaseNotes.EndCursor)
	require.Equal(t, "Launch notes", releaseNotes.ReleaseNotes[0].Title)
	require.Equal(t, "completed", releaseNote.GenerationStatus)
	require.Equal(t, "Mobile 1.2.3", releaseNote.LastReleaseName)
	require.Equal(t, "team body", team.Description)
	require.Equal(t, "Omer", teamMembers.Members[0].DisplayName)
	require.Equal(t, &endCursor, teamMembers.EndCursor)
	require.True(t, users.HasNextPage)
	require.True(t, users.Users[0].Admin)
	require.Equal(t, "Omer", user.DisplayName)
	require.Equal(t, "Omer", viewerUser.DisplayName)
	require.True(t, drafts.HasNextPage)
	require.Equal(t, &endCursor, drafts.EndCursor)
	require.Equal(t, "issue", drafts.Drafts[0].ParentType)
	require.Equal(t, "LIT-3", drafts.Drafts[0].ParentKey)
	require.Equal(t, "project", drafts.Drafts[1].ParentType)
	require.Equal(t, "project_update", drafts.Drafts[2].ParentType)
	require.Equal(t, "initiative", drafts.Drafts[3].ParentType)
	require.Equal(t, "initiative_update", drafts.Drafts[4].ParentType)
	require.Equal(t, "comment", drafts.Drafts[5].ParentType)
	require.Equal(t, "customer_need", drafts.Drafts[6].ParentType)
	require.Equal(t, "team", drafts.Drafts[7].ParentType)
	require.Equal(t, "unknown", drafts.Drafts[8].ParentType)
	require.Equal(t, "LIT-41", userAssignedIssues.Issues[0].Identifier)
	require.Equal(t, "LIT-42", userCreatedIssues.Issues[0].Identifier)
	require.Equal(t, "LIT-43", userDelegatedIssues.Issues[0].Identifier)
	require.Equal(t, "team-membership-id", userTeamMemberships.Memberships[0].ID)
	require.Equal(t, "LIT", userTeams.Teams[0].Key)
	require.Equal(t, "LIT-44", viewerAssignedIssues.Issues[0].Identifier)
	require.Equal(t, "LIT-45", viewerCreatedIssues.Issues[0].Identifier)
	require.Equal(t, "LIT-46", viewerDelegatedIssues.Issues[0].Identifier)
	require.Equal(t, "team-membership-id", viewerTeamMemberships.Memberships[0].ID)
	require.Equal(t, "LIT", viewerTeams.Teams[0].Key)
	require.True(t, workflowStates.HasNextPage)
	require.Equal(t, &endCursor, workflowStates.EndCursor)
	require.Equal(t, "Started", workflowStates.WorkflowStates[0].Name)
	require.Equal(t, "LIT", workflowStates.WorkflowStates[0].TeamKey)
	require.Equal(t, "started", workflowState.Type)
	require.Equal(t, "linctl", workflowState.TeamName)
	require.True(t, workflowStateIssues.HasNextPage)
	require.Equal(t, "workflow-state-id", workflowStateIssues.WorkflowStateID)
	require.Equal(t, "LIT-55", workflowStateIssues.Issues[0].Identifier)
	require.True(t, timeSchedules.HasNextPage)
	require.Equal(t, &endCursor, timeSchedules.EndCursor)
	require.Equal(t, "Primary on-call", timeSchedules.TimeSchedules[0].Name)
	require.Equal(t, 1, timeSchedule.EntryCount)
	require.Equal(t, "integration-id", timeSchedule.IntegrationID)
	require.Equal(t, "omer@example.com", timeSchedule.Entries[0].UserEmail)
	require.True(t, organizationLabels.HasNextPage)
	require.Equal(t, &endCursor, organizationLabels.EndCursor)
	require.Equal(t, "Bug", organizationLabels.Labels[0].Name)
	require.True(t, organizationProjectLabels.HasNextPage)
	require.Equal(t, "Roadmap", organizationProjectLabels.ProjectLabels[0].Name)
	require.True(t, organizationTeams.HasNextPage)
	require.Equal(t, "linctl", organizationTeams.Teams[0].Name)
	require.True(t, organizationTemplates.HasNextPage)
	require.Equal(t, &endCursor, organizationTemplates.EndCursor)
	require.Equal(t, "Bug report", organizationTemplates.Templates[0].Name)
	require.True(t, organizationUsers.HasNextPage)
	require.Equal(t, "Omer", organizationUsers.Users[0].DisplayName)
	require.Equal(t, 2, templates.TotalCount)
	require.Len(t, templates.Templates, 1)
	require.Equal(t, "Bug report", templates.Templates[0].Name)
	require.Equal(t, "issue", templates.Templates[0].Type)
	require.Equal(t, "LIT", templates.Templates[0].TeamKey)
	require.Equal(t, "template-id", template.ID)
	require.Equal(t, "pipeline-id", template.PipelineID)
}
