package client

import (
	"context"
	"fmt"
	"sort"

	"github.com/Khan/genqlient/graphql"

	"github.com/KyaniteHQ/linctl/internal/client/internal/gql"
)

// ListNextIssuesByTeam returns unstarted issues that are not blocked by another issue.
func ListNextIssuesByTeam(
	ctx context.Context,
	graphqlClient graphql.Client,
	teamID string,
	limit int,
) (IssueList, error) {
	issues, err := gql.NextIssuesByTeam(ctx, graphqlClient, teamID, &limit, nil, boolPtr(true))
	if err != nil {
		return IssueList{}, fmt.Errorf("list next issues: %w", err)
	}

	summaries := mapNodes(issues.Issues.Nodes, nextIssueSummary)
	sortNextIssueCandidates(summaries)

	return IssueList{
		Issues:      summaries,
		HasNextPage: issues.Issues.PageInfo.HasNextPage,
		EndCursor:   issues.Issues.PageInfo.EndCursor,
	}, nil
}

func nextIssueSummary(issue gql.NextIssuesByTeamIssuesIssueConnectionNodesIssue) IssueSummary {
	summary := issueSummaryFromFields(issue.IssueSummaryFields)
	summary.CreatedAt = issue.CreatedAt
	summary.UnblocksCount = nextIssueUnblocksCount(issue.Relations.Nodes)

	return summary
}

//nolint:lll // The aliased name is generated by genqlient from the GraphQL selection path.
type nextIssueRelation = gql.NextIssuesByTeamIssuesIssueConnectionNodesIssueRelationsIssueRelationConnectionNodesIssueRelation

func nextIssueUnblocksCount(relations []nextIssueRelation) int {
	count := 0
	for _, relation := range relations {
		if relation.Type == "blocks" && isActiveIssueStateType(relation.RelatedIssue.State.Type) {
			count++
		}
	}

	return count
}

func isActiveIssueStateType(stateType string) bool {
	return stateType != "completed" && stateType != "canceled"
}

func sortNextIssueCandidates(issues []IssueSummary) {
	sort.SliceStable(issues, func(leftIndex int, rightIndex int) bool {
		left := issues[leftIndex]
		right := issues[rightIndex]
		if left.UnblocksCount != right.UnblocksCount {
			return left.UnblocksCount > right.UnblocksCount
		}
		if left.Priority != right.Priority {
			return linearPriorityRank(left.Priority) > linearPriorityRank(right.Priority)
		}

		return left.CreatedAt < right.CreatedAt
	})
}

func linearPriorityRank(priority float64) float64 {
	if priority == 0 {
		return -1
	}

	return 5 - priority
}
