package client

import (
	"context"
	"sort"

	"github.com/Khan/genqlient/graphql"

	"github.com/KyaniteHQ/linctl/internal/client/internal/gql"
)

//nolint:lll
type nextIssueNode = gql.NextIssuesByTeamIssuesIssueConnectionNodesIssue

// ListNextIssuesByTeam returns unstarted issues that are not blocked by another issue.
func ListNextIssuesByTeam(
	ctx context.Context,
	graphqlClient graphql.Client,
	teamID string,
	limit int,
) (IssueList, error) {
	page, err := listConnection(
		"list next issues", limit, defaultListPageSize,
		func(pageSize int, after *string) ([]nextIssueNode, bool, *string, error) {
			issues, err := gql.NextIssuesByTeam(
				ctx, graphqlClient, teamID, intPtr(pageSize), after, boolPtr(true),
			)
			if err != nil {
				return nil, false, nil, err
			}

			return issues.Issues.Nodes,
				issues.Issues.PageInfo.HasNextPage,
				issues.Issues.PageInfo.EndCursor,
				nil
		},
		nextIssueSummary,
	)
	if err != nil {
		return IssueList{}, err
	}

	sortNextIssueCandidates(page.Items)

	return IssueList{Issues: page.Items, Page: page.Page}, nil
}

func nextIssueSummary(issue nextIssueNode) IssueSummary {
	summary := issueSummaryFromFields(issue.IssueSummaryFields)
	summary.CreatedAt = issue.CreatedAt
	summary.UnblocksCount = nextIssueUnblocksCount(issue.Relations.Nodes)

	return summary
}

//nolint:lll // The aliased name is generated by genqlient from the GraphQL selection path.
type nextIssueRelation = gql.NextIssuesByTeamIssuesIssueConnectionNodesIssueRelationsIssueRelationConnectionNodesIssueRelation

func nextIssueUnblocksCount(relations []nextIssueRelation) int {
	count := 0
	for _, relation := range relations {
		if relation.Type == "blocks" && isActiveIssueStateType(relation.RelatedIssue.State.Type) {
			count++
		}
	}

	return count
}

func isActiveIssueStateType(stateType string) bool {
	return stateType != "completed" && stateType != "canceled"
}

func sortNextIssueCandidates(issues []IssueSummary) {
	sort.SliceStable(issues, func(leftIndex int, rightIndex int) bool {
		left := issues[leftIndex]
		right := issues[rightIndex]
		if left.UnblocksCount != right.UnblocksCount {
			return left.UnblocksCount > right.UnblocksCount
		}
		if left.Priority != right.Priority {
			return linearPriorityRank(left.Priority) > linearPriorityRank(right.Priority)
		}

		return left.CreatedAt < right.CreatedAt
	})
}

func linearPriorityRank(priority float64) float64 {
	if priority == 0 {
		return -1
	}

	return 5 - priority
}
