query attachments($first: Int, $after: String, $includeArchived: Boolean) {
  attachments(first: $first, after: $after, includeArchived: $includeArchived) {
    nodes {
      ...AttachmentSummaryFields
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}

query attachmentsForURL($url: String!, $first: Int, $after: String, $includeArchived: Boolean) {
  attachmentsForURL(url: $url, first: $first, after: $after, includeArchived: $includeArchived) {
    nodes {
      ...AttachmentSummaryFields
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}

query attachment($id: String!) {
  attachment(id: $id) {
    ...AttachmentSummaryFields
  }
}

query attachmentIssue($id: String!) {
  attachmentIssue(id: $id) {
    ...IssueSummaryFields
  }
}

query attachmentIssue_attachments($id: String!, $first: Int, $after: String, $includeArchived: Boolean) {
  attachmentIssue(id: $id) {
    ...IssueAttachmentsProjection
  }
}

query attachmentIssue_botActor($id: String!) {
  attachmentIssue(id: $id) {
    ...IssueBotActorProjection
  }
}

query attachmentIssue_children($id: String!, $first: Int, $after: String, $includeArchived: Boolean) {
  attachmentIssue(id: $id) {
    ...IssueChildrenProjection
  }
}

query attachmentIssue_comments($id: String!, $first: Int, $after: String, $includeArchived: Boolean) {
  attachmentIssue(id: $id) {
    ...IssueCommentMetadataProjection
  }
}

query attachmentIssue_documents($id: String!, $first: Int, $after: String, $includeArchived: Boolean) {
  attachmentIssue(id: $id) {
    ...IssueDocumentsProjection
  }
}

query attachmentIssue_formerAttachments($id: String!, $first: Int, $after: String, $includeArchived: Boolean) {
  attachmentIssue(id: $id) {
    ...IssueFormerAttachmentsProjection
  }
}

query attachmentIssue_formerNeeds($id: String!, $first: Int, $after: String, $includeArchived: Boolean) {
  attachmentIssue(id: $id) {
    ...IssueFormerNeedsProjection
  }
}

query attachmentIssue_history($id: String!, $first: Int, $after: String, $includeArchived: Boolean) {
  attachmentIssue(id: $id) {
    ...IssueHistoryProjection
  }
}

query attachmentIssue_inverseRelations($id: String!, $first: Int, $after: String, $includeArchived: Boolean) {
  attachmentIssue(id: $id) {
    ...IssueInverseRelationsProjection
  }
}

query attachmentIssue_labels($id: String!, $first: Int, $after: String, $includeArchived: Boolean) {
  attachmentIssue(id: $id) {
    ...IssueLabelsProjection
  }
}

query attachmentIssue_needs($id: String!, $first: Int, $after: String, $includeArchived: Boolean) {
  attachmentIssue(id: $id) {
    ...IssueNeedsProjection
  }
}

query attachmentIssue_relations($id: String!, $first: Int, $after: String, $includeArchived: Boolean) {
  attachmentIssue(id: $id) {
    ...IssueRelationsProjection
  }
}

query attachmentIssue_releases($id: String!, $first: Int, $after: String, $includeArchived: Boolean) {
  attachmentIssue(id: $id) {
    ...IssueReleasesProjection
  }
}

query attachmentIssue_sharedAccess($id: String!) {
  attachmentIssue(id: $id) {
    ...IssueSharedAccessProjection
  }
}

query attachmentIssue_stateHistory($id: String!, $first: Int, $after: String) {
  attachmentIssue(id: $id) {
    ...IssueStateHistoryProjection
  }
}

query attachmentIssue_subscribers($id: String!, $first: Int, $after: String, $includeArchived: Boolean) {
  attachmentIssue(id: $id) {
    ...IssueSubscribersProjection
  }
}

mutation AttachmentLinkURL($input: AttachmentCreateInput!) {
  attachmentCreate(input: $input) {
    success
    attachment {
      ...AttachmentSummaryFields
    }
  }
}

fragment AttachmentSummaryFields on Attachment {
  id
  title
  subtitle
  url
  sourceType
}
