query IssueLabels($first: Int, $after: String, $includeArchived: Boolean) {
  issueLabels(first: $first, after: $after, includeArchived: $includeArchived) {
    nodes {
      ...IssueLabelSummaryFields
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}

query issueLabel($id: String!) {
  issueLabel(id: $id) {
    ...IssueLabelSummaryFields
  }
}

query issueLabel_children($id: String!, $first: Int, $after: String, $includeArchived: Boolean) {
  issueLabel(id: $id) {
    id
    name
    children(first: $first, after: $after, includeArchived: $includeArchived) {
      nodes {
        ...IssueLabelSummaryFields
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}

query issueLabel_issues($id: String!, $first: Int, $after: String, $includeArchived: Boolean) {
  issueLabel(id: $id) {
    id
    name
    issues(first: $first, after: $after, includeArchived: $includeArchived) {
      nodes {
        ...IssueSummaryFields
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}

fragment IssueLabelSummaryFields on IssueLabel {
  id
  name
  description
  color
  isGroup
  team {
    id
    key
    name
  }
}

mutation IssueLabelCreate($replaceTeamLabels: Boolean, $input: IssueLabelCreateInput!) {
  issueLabelCreate(replaceTeamLabels: $replaceTeamLabels, input: $input) {
    success
    issueLabel {
      ...IssueLabelSummaryFields
    }
  }
}

mutation IssueLabelUpdate($id: String!, $replaceTeamLabels: Boolean, $input: IssueLabelUpdateInput!) {
  issueLabelUpdate(id: $id, replaceTeamLabels: $replaceTeamLabels, input: $input) {
    success
    issueLabel {
      ...IssueLabelSummaryFields
    }
  }
}

mutation IssueLabelRetire($id: String!) {
  issueLabelRetire(id: $id) {
    success
    issueLabel {
      ...IssueLabelSummaryFields
    }
  }
}

mutation IssueLabelRestore($id: String!) {
  issueLabelRestore(id: $id) {
    success
    issueLabel {
      ...IssueLabelSummaryFields
    }
  }
}
