// Code generated by exportgen; DO NOT EDIT.

package gql

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

func XActiveCyclesByTeam(ctx_ context.Context, client_ graphql.Client, teamId string) (data_ *activeCyclesByTeamResponse, err_ error) {
	return activeCyclesByTeam(ctx_, client_, teamId)
}

func XAgentActivities(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *agentActivitiesResponse, err_ error) {
	return agentActivities(ctx_, client_, first, after, includeArchived)
}

type XAgentActivitiesAgentActivitiesAgentActivityConnectionNodesAgentActivity = agentActivitiesAgentActivitiesAgentActivityConnectionNodesAgentActivity

func XAgentActivity(ctx_ context.Context, client_ graphql.Client, id string) (data_ *agentActivityResponse, err_ error) {
	return agentActivity(ctx_, client_, id)
}

func XAgentSession(ctx_ context.Context, client_ graphql.Client, id string) (data_ *agentSessionResponse, err_ error) {
	return agentSession(ctx_, client_, id)
}

func XAgentSessions(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *agentSessionsResponse, err_ error) {
	return agentSessions(ctx_, client_, first, after, includeArchived)
}

type XAgentSessionsAgentSessionsAgentSessionConnectionNodesAgentSession = agentSessionsAgentSessionsAgentSessionConnectionNodesAgentSession

func XAgentSkill(ctx_ context.Context, client_ graphql.Client, id string) (data_ *agentSkillResponse, err_ error) {
	return agentSkill(ctx_, client_, id)
}

func XAgentSkills(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *agentSkillsResponse, err_ error) {
	return agentSkills(ctx_, client_, first, after, includeArchived)
}

type XAgentSkillsAgentSkillsAgentSkillConnectionNodesAgentSkill = agentSkillsAgentSkillsAgentSkillConnectionNodesAgentSkill

func XApplicationInfo(ctx_ context.Context, client_ graphql.Client, clientId string) (data_ *applicationInfoResponse, err_ error) {
	return applicationInfo(ctx_, client_, clientId)
}

func XAttachment(ctx_ context.Context, client_ graphql.Client, id string) (data_ *attachmentResponse, err_ error) {
	return attachment(ctx_, client_, id)
}

func XAttachmentIssue(ctx_ context.Context, client_ graphql.Client, id string) (data_ *attachmentIssueResponse, err_ error) {
	return attachmentIssue(ctx_, client_, id)
}

func XAttachmentIssue_attachments(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *attachmentIssue_attachmentsResponse, err_ error) {
	return attachmentIssue_attachments(ctx_, client_, id, first, after, includeArchived)
}

func XAttachmentIssue_botActor(ctx_ context.Context, client_ graphql.Client, id string) (data_ *attachmentIssue_botActorResponse, err_ error) {
	return attachmentIssue_botActor(ctx_, client_, id)
}

func XAttachmentIssue_children(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *attachmentIssue_childrenResponse, err_ error) {
	return attachmentIssue_children(ctx_, client_, id, first, after, includeArchived)
}

func XAttachmentIssue_comments(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *attachmentIssue_commentsResponse, err_ error) {
	return attachmentIssue_comments(ctx_, client_, id, first, after, includeArchived)
}

func XAttachmentIssue_documents(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *attachmentIssue_documentsResponse, err_ error) {
	return attachmentIssue_documents(ctx_, client_, id, first, after, includeArchived)
}

func XAttachmentIssue_formerAttachments(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *attachmentIssue_formerAttachmentsResponse, err_ error) {
	return attachmentIssue_formerAttachments(ctx_, client_, id, first, after, includeArchived)
}

func XAttachmentIssue_formerNeeds(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *attachmentIssue_formerNeedsResponse, err_ error) {
	return attachmentIssue_formerNeeds(ctx_, client_, id, first, after, includeArchived)
}

func XAttachmentIssue_history(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *attachmentIssue_historyResponse, err_ error) {
	return attachmentIssue_history(ctx_, client_, id, first, after, includeArchived)
}

func XAttachmentIssue_inverseRelations(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *attachmentIssue_inverseRelationsResponse, err_ error) {
	return attachmentIssue_inverseRelations(ctx_, client_, id, first, after, includeArchived)
}

func XAttachmentIssue_labels(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *attachmentIssue_labelsResponse, err_ error) {
	return attachmentIssue_labels(ctx_, client_, id, first, after, includeArchived)
}

func XAttachmentIssue_needs(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *attachmentIssue_needsResponse, err_ error) {
	return attachmentIssue_needs(ctx_, client_, id, first, after, includeArchived)
}

func XAttachmentIssue_relations(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *attachmentIssue_relationsResponse, err_ error) {
	return attachmentIssue_relations(ctx_, client_, id, first, after, includeArchived)
}

func XAttachmentIssue_releases(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *attachmentIssue_releasesResponse, err_ error) {
	return attachmentIssue_releases(ctx_, client_, id, first, after, includeArchived)
}

func XAttachmentIssue_sharedAccess(ctx_ context.Context, client_ graphql.Client, id string) (data_ *attachmentIssue_sharedAccessResponse, err_ error) {
	return attachmentIssue_sharedAccess(ctx_, client_, id)
}

func XAttachmentIssue_stateHistory(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string) (data_ *attachmentIssue_stateHistoryResponse, err_ error) {
	return attachmentIssue_stateHistory(ctx_, client_, id, first, after)
}

func XAttachmentIssue_subscribers(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *attachmentIssue_subscribersResponse, err_ error) {
	return attachmentIssue_subscribers(ctx_, client_, id, first, after, includeArchived)
}

func XAttachments(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *attachmentsResponse, err_ error) {
	return attachments(ctx_, client_, first, after, includeArchived)
}

type XAttachmentsAttachmentsAttachmentConnectionNodesAttachment = attachmentsAttachmentsAttachmentConnectionNodesAttachment

func XAttachmentsForURL(ctx_ context.Context, client_ graphql.Client, url string, first *int, after *string, includeArchived *bool) (data_ *attachmentsForURLResponse, err_ error) {
	return attachmentsForURL(ctx_, client_, url, first, after, includeArchived)
}

type XAttachmentsForURLAttachmentsForURLAttachmentConnectionNodesAttachment = attachmentsForURLAttachmentsForURLAttachmentConnectionNodesAttachment

func XAuditEntryTypes(ctx_ context.Context, client_ graphql.Client) (data_ *auditEntryTypesResponse, err_ error) {
	return auditEntryTypes(ctx_, client_)
}

type XAuditEntryTypesAuditEntryTypesAuditEntryType = auditEntryTypesAuditEntryTypesAuditEntryType

func XComment(ctx_ context.Context, client_ graphql.Client, id *string, hash *string) (data_ *commentResponse, err_ error) {
	return comment(ctx_, client_, id, hash)
}

func XComment_botActor(ctx_ context.Context, client_ graphql.Client, id *string, hash *string) (data_ *comment_botActorResponse, err_ error) {
	return comment_botActor(ctx_, client_, id, hash)
}

type XComment_botActorCommentBotActorActorBot = comment_botActorCommentBotActorActorBot

func XComment_children(ctx_ context.Context, client_ graphql.Client, id *string, hash *string, first *int, after *string, includeArchived *bool) (data_ *comment_childrenResponse, err_ error) {
	return comment_children(ctx_, client_, id, hash, first, after, includeArchived)
}

type XComment_childrenCommentChildrenCommentConnectionNodesComment = comment_childrenCommentChildrenCommentConnectionNodesComment

func XComment_createdIssues(ctx_ context.Context, client_ graphql.Client, id *string, hash *string, first *int, after *string, includeArchived *bool) (data_ *comment_createdIssuesResponse, err_ error) {
	return comment_createdIssues(ctx_, client_, id, hash, first, after, includeArchived)
}

type XComment_createdIssuesCommentCreatedIssuesIssueConnectionNodesIssue = comment_createdIssuesCommentCreatedIssuesIssueConnectionNodesIssue

func XComments(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *commentsResponse, err_ error) {
	return comments(ctx_, client_, first, after, includeArchived)
}

type XCommentsCommentsCommentConnectionNodesComment = commentsCommentsCommentConnectionNodesComment

func XCustomView(ctx_ context.Context, client_ graphql.Client, id string) (data_ *customViewResponse, err_ error) {
	return customView(ctx_, client_, id)
}

func XCustomViewHasSubscribers(ctx_ context.Context, client_ graphql.Client, id string) (data_ *customViewHasSubscribersResponse, err_ error) {
	return customViewHasSubscribers(ctx_, client_, id)
}

func XCustomView_initiatives(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *customView_initiativesResponse, err_ error) {
	return customView_initiatives(ctx_, client_, id, first, after, includeArchived)
}

type XCustomView_initiativesCustomViewInitiativesInitiativeConnectionNodesInitiative = customView_initiativesCustomViewInitiativesInitiativeConnectionNodesInitiative

func XCustomView_issues(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *customView_issuesResponse, err_ error) {
	return customView_issues(ctx_, client_, id, first, after, includeArchived)
}

type XCustomView_issuesCustomViewIssuesIssueConnectionNodesIssue = customView_issuesCustomViewIssuesIssueConnectionNodesIssue

func XCustomView_organizationViewPreferences(ctx_ context.Context, client_ graphql.Client, id string) (data_ *customView_organizationViewPreferencesResponse, err_ error) {
	return customView_organizationViewPreferences(ctx_, client_, id)
}

func XCustomView_organizationViewPreferences_preferences(ctx_ context.Context, client_ graphql.Client, id string) (data_ *customView_organizationViewPreferences_preferencesResponse, err_ error) {
	return customView_organizationViewPreferences_preferences(ctx_, client_, id)
}

func XCustomView_projects(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *customView_projectsResponse, err_ error) {
	return customView_projects(ctx_, client_, id, first, after, includeArchived)
}

type XCustomView_projectsCustomViewProjectsProjectConnectionNodesProject = customView_projectsCustomViewProjectsProjectConnectionNodesProject

func XCustomView_userViewPreferences(ctx_ context.Context, client_ graphql.Client, id string) (data_ *customView_userViewPreferencesResponse, err_ error) {
	return customView_userViewPreferences(ctx_, client_, id)
}

func XCustomView_userViewPreferences_preferences(ctx_ context.Context, client_ graphql.Client, id string) (data_ *customView_userViewPreferences_preferencesResponse, err_ error) {
	return customView_userViewPreferences_preferences(ctx_, client_, id)
}

func XCustomView_viewPreferencesValues(ctx_ context.Context, client_ graphql.Client, id string) (data_ *customView_viewPreferencesValuesResponse, err_ error) {
	return customView_viewPreferencesValues(ctx_, client_, id)
}

func XCustomViews(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *customViewsResponse, err_ error) {
	return customViews(ctx_, client_, first, after, includeArchived)
}

type XCustomViewsCustomViewsCustomViewConnectionNodesCustomView = customViewsCustomViewsCustomViewConnectionNodesCustomView

func XCustomer(ctx_ context.Context, client_ graphql.Client, id string) (data_ *customerResponse, err_ error) {
	return customer(ctx_, client_, id)
}

func XCustomerNeed(ctx_ context.Context, client_ graphql.Client, id *string) (data_ *customerNeedResponse, err_ error) {
	return customerNeed(ctx_, client_, id)
}

func XCustomerNeed_projectAttachment(ctx_ context.Context, client_ graphql.Client, id *string) (data_ *customerNeed_projectAttachmentResponse, err_ error) {
	return customerNeed_projectAttachment(ctx_, client_, id)
}

func XCustomerNeeds(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *customerNeedsResponse, err_ error) {
	return customerNeeds(ctx_, client_, first, after, includeArchived)
}

type XCustomerNeedsCustomerNeedsCustomerNeedConnectionNodesCustomerNeed = customerNeedsCustomerNeedsCustomerNeedConnectionNodesCustomerNeed

func XCustomerStatus(ctx_ context.Context, client_ graphql.Client, id string) (data_ *customerStatusResponse, err_ error) {
	return customerStatus(ctx_, client_, id)
}

func XCustomerStatuses(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *customerStatusesResponse, err_ error) {
	return customerStatuses(ctx_, client_, first, after, includeArchived)
}

type XCustomerStatusesCustomerStatusesCustomerStatusConnectionNodesCustomerStatus = customerStatusesCustomerStatusesCustomerStatusConnectionNodesCustomerStatus

func XCustomerTier(ctx_ context.Context, client_ graphql.Client, id string) (data_ *customerTierResponse, err_ error) {
	return customerTier(ctx_, client_, id)
}

func XCustomerTiers(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *customerTiersResponse, err_ error) {
	return customerTiers(ctx_, client_, first, after, includeArchived)
}

type XCustomerTiersCustomerTiersCustomerTierConnectionNodesCustomerTier = customerTiersCustomerTiersCustomerTierConnectionNodesCustomerTier

func XCustomers(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *customersResponse, err_ error) {
	return customers(ctx_, client_, first, after, includeArchived)
}

type XCustomersCustomersCustomerConnectionNodesCustomer = customersCustomersCustomerConnectionNodesCustomer

func XCycle(ctx_ context.Context, client_ graphql.Client, id string) (data_ *cycleResponse, err_ error) {
	return cycle(ctx_, client_, id)
}

func XCycle_issues(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *cycle_issuesResponse, err_ error) {
	return cycle_issues(ctx_, client_, id, first, after, includeArchived)
}

type XCycle_issuesCycleIssuesIssueConnectionNodesIssue = cycle_issuesCycleIssuesIssueConnectionNodesIssue

func XCycle_uncompletedIssuesUponClose(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *cycle_uncompletedIssuesUponCloseResponse, err_ error) {
	return cycle_uncompletedIssuesUponClose(ctx_, client_, id, first, after, includeArchived)
}

type XCycle_uncompletedIssuesUponCloseCycleUncompletedIssuesUponCloseIssueConnectionNodesIssue = cycle_uncompletedIssuesUponCloseCycleUncompletedIssuesUponCloseIssueConnectionNodesIssue

func XCycles(ctx_ context.Context, client_ graphql.Client, teamId string, first *int, after *string, includeArchived *bool) (data_ *cyclesResponse, err_ error) {
	return cycles(ctx_, client_, teamId, first, after, includeArchived)
}

type XCyclesCyclesCycleConnectionNodesCycle = cyclesCyclesCycleConnectionNodesCycle

func XDocument(ctx_ context.Context, client_ graphql.Client, id string) (data_ *documentResponse, err_ error) {
	return document(ctx_, client_, id)
}

func XDocument_comments(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *document_commentsResponse, err_ error) {
	return document_comments(ctx_, client_, id, first, after, includeArchived)
}

type XDocument_commentsDocumentCommentsCommentConnectionNodesComment = document_commentsDocumentCommentsCommentConnectionNodesComment

func XEmoji(ctx_ context.Context, client_ graphql.Client, id string) (data_ *emojiResponse, err_ error) {
	return emoji(ctx_, client_, id)
}

func XEmojis(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *emojisResponse, err_ error) {
	return emojis(ctx_, client_, first, after, includeArchived)
}

type XEmojisEmojisEmojiConnectionNodesEmoji = emojisEmojisEmojiConnectionNodesEmoji

func XEntityExternalLink(ctx_ context.Context, client_ graphql.Client, id string) (data_ *entityExternalLinkResponse, err_ error) {
	return entityExternalLink(ctx_, client_, id)
}

func XExternalUser(ctx_ context.Context, client_ graphql.Client, id string) (data_ *externalUserResponse, err_ error) {
	return externalUser(ctx_, client_, id)
}

func XExternalUsers(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *externalUsersResponse, err_ error) {
	return externalUsers(ctx_, client_, first, after, includeArchived)
}

type XExternalUsersExternalUsersExternalUserConnectionNodesExternalUser = externalUsersExternalUsersExternalUserConnectionNodesExternalUser

func XFavorite(ctx_ context.Context, client_ graphql.Client, id string) (data_ *favoriteResponse, err_ error) {
	return favorite(ctx_, client_, id)
}

func XFavorite_children(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *favorite_childrenResponse, err_ error) {
	return favorite_children(ctx_, client_, id, first, after, includeArchived)
}

type XFavorite_childrenFavoriteChildrenFavoriteConnectionNodesFavorite = favorite_childrenFavoriteChildrenFavoriteConnectionNodesFavorite

func XFavorites(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *favoritesResponse, err_ error) {
	return favorites(ctx_, client_, first, after, includeArchived)
}

type XFavoritesFavoritesFavoriteConnectionNodesFavorite = favoritesFavoritesFavoriteConnectionNodesFavorite

func XFileUpload(ctx_ context.Context, client_ graphql.Client, contentType string, filename string, size int) (data_ *fileUploadResponse, err_ error) {
	return fileUpload(ctx_, client_, contentType, filename, size)
}

type XFileUploadFileUploadUploadPayloadUploadFileHeadersUploadFileHeader = fileUploadFileUploadUploadPayloadUploadFileHeadersUploadFileHeader

func XInitiative(ctx_ context.Context, client_ graphql.Client, id string) (data_ *initiativeResponse, err_ error) {
	return initiative(ctx_, client_, id)
}

func XInitiativeLabel(ctx_ context.Context, client_ graphql.Client, id string) (data_ *initiativeLabelResponse, err_ error) {
	return initiativeLabel(ctx_, client_, id)
}

func XInitiativeLabels(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *initiativeLabelsResponse, err_ error) {
	return initiativeLabels(ctx_, client_, first, after, includeArchived)
}

type XInitiativeLabelsInitiativeLabelsInitiativeLabelConnectionNodesInitiativeLabel = initiativeLabelsInitiativeLabelsInitiativeLabelConnectionNodesInitiativeLabel

func XInitiativeRelation(ctx_ context.Context, client_ graphql.Client, id string) (data_ *initiativeRelationResponse, err_ error) {
	return initiativeRelation(ctx_, client_, id)
}

func XInitiativeRelations(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *initiativeRelationsResponse, err_ error) {
	return initiativeRelations(ctx_, client_, first, after, includeArchived)
}

type XInitiativeRelationsInitiativeRelationsInitiativeRelationConnectionNodesInitiativeRelation = initiativeRelationsInitiativeRelationsInitiativeRelationConnectionNodesInitiativeRelation

func XInitiativeToProject(ctx_ context.Context, client_ graphql.Client, id string) (data_ *initiativeToProjectResponse, err_ error) {
	return initiativeToProject(ctx_, client_, id)
}

func XInitiativeToProjects(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *initiativeToProjectsResponse, err_ error) {
	return initiativeToProjects(ctx_, client_, first, after, includeArchived)
}

type XInitiativeToProjectsInitiativeToProjectsInitiativeToProjectConnectionNodesInitiativeToProject = initiativeToProjectsInitiativeToProjectsInitiativeToProjectConnectionNodesInitiativeToProject

func XInitiativeUpdate(ctx_ context.Context, client_ graphql.Client, id string) (data_ *initiativeUpdateResponse, err_ error) {
	return initiativeUpdate(ctx_, client_, id)
}

func XInitiativeUpdate_comments(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *initiativeUpdate_commentsResponse, err_ error) {
	return initiativeUpdate_comments(ctx_, client_, id, first, after, includeArchived)
}

type XInitiativeUpdate_commentsInitiativeUpdateCommentsCommentConnectionNodesComment = initiativeUpdate_commentsInitiativeUpdateCommentsCommentConnectionNodesComment

func XInitiativeUpdates(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *initiativeUpdatesResponse, err_ error) {
	return initiativeUpdates(ctx_, client_, first, after, includeArchived)
}

type XInitiativeUpdatesInitiativeUpdatesInitiativeUpdateConnectionNodesInitiativeUpdate = initiativeUpdatesInitiativeUpdatesInitiativeUpdateConnectionNodesInitiativeUpdate

func XInitiative_documents(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *initiative_documentsResponse, err_ error) {
	return initiative_documents(ctx_, client_, id, first, after, includeArchived)
}

type XInitiative_documentsInitiativeDocumentsDocumentConnectionNodesDocument = initiative_documentsInitiativeDocumentsDocumentConnectionNodesDocument

func XInitiative_history(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *initiative_historyResponse, err_ error) {
	return initiative_history(ctx_, client_, id, first, after, includeArchived)
}

type XInitiative_historyInitiativeHistoryInitiativeHistoryConnectionNodesInitiativeHistory = initiative_historyInitiativeHistoryInitiativeHistoryConnectionNodesInitiativeHistory

func XInitiative_initiativeUpdates(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *initiative_initiativeUpdatesResponse, err_ error) {
	return initiative_initiativeUpdates(ctx_, client_, id, first, after, includeArchived)
}

type XInitiative_initiativeUpdatesInitiativeInitiativeUpdatesInitiativeUpdateConnectionNodesInitiativeUpdate = initiative_initiativeUpdatesInitiativeInitiativeUpdatesInitiativeUpdateConnectionNodesInitiativeUpdate

func XInitiative_links(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *initiative_linksResponse, err_ error) {
	return initiative_links(ctx_, client_, id, first, after, includeArchived)
}

type XInitiative_linksInitiativeLinksEntityExternalLinkConnectionNodesEntityExternalLink = initiative_linksInitiativeLinksEntityExternalLinkConnectionNodesEntityExternalLink

func XInitiative_projects(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool, includeSubInitiatives *bool) (data_ *initiative_projectsResponse, err_ error) {
	return initiative_projects(ctx_, client_, id, first, after, includeArchived, includeSubInitiatives)
}

type XInitiative_projectsInitiativeProjectsProjectConnectionNodesProject = initiative_projectsInitiativeProjectsProjectConnectionNodesProject

func XInitiative_subInitiatives(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *initiative_subInitiativesResponse, err_ error) {
	return initiative_subInitiatives(ctx_, client_, id, first, after, includeArchived)
}

type XInitiative_subInitiativesInitiativeSubInitiativesInitiativeConnectionNodesInitiative = initiative_subInitiativesInitiativeSubInitiativesInitiativeConnectionNodesInitiative

func XInitiatives(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *initiativesResponse, err_ error) {
	return initiatives(ctx_, client_, first, after, includeArchived)
}

type XInitiativesInitiativesInitiativeConnectionNodesInitiative = initiativesInitiativesInitiativeConnectionNodesInitiative

func XIssue(ctx_ context.Context, client_ graphql.Client, id string) (data_ *issueResponse, err_ error) {
	return issue(ctx_, client_, id)
}

func XIssueFigmaFileKeySearch(ctx_ context.Context, client_ graphql.Client, fileKey string, first *int, after *string, includeArchived *bool) (data_ *issueFigmaFileKeySearchResponse, err_ error) {
	return issueFigmaFileKeySearch(ctx_, client_, fileKey, first, after, includeArchived)
}

type XIssueFigmaFileKeySearchIssueFigmaFileKeySearchIssueConnectionNodesIssue = issueFigmaFileKeySearchIssueFigmaFileKeySearchIssueConnectionNodesIssue

func XIssueFilterSuggestion(ctx_ context.Context, client_ graphql.Client, prompt string, teamId *string, projectId *string) (data_ *issueFilterSuggestionResponse, err_ error) {
	return issueFilterSuggestion(ctx_, client_, prompt, teamId, projectId)
}

type XIssueIssue = issueIssue

func XIssueLabel(ctx_ context.Context, client_ graphql.Client, id string) (data_ *issueLabelResponse, err_ error) {
	return issueLabel(ctx_, client_, id)
}

func XIssueLabel_children(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *issueLabel_childrenResponse, err_ error) {
	return issueLabel_children(ctx_, client_, id, first, after, includeArchived)
}

type XIssueLabel_childrenIssueLabelChildrenIssueLabelConnectionNodesIssueLabel = issueLabel_childrenIssueLabelChildrenIssueLabelConnectionNodesIssueLabel

func XIssueLabel_issues(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *issueLabel_issuesResponse, err_ error) {
	return issueLabel_issues(ctx_, client_, id, first, after, includeArchived)
}

type XIssueLabel_issuesIssueLabelIssuesIssueConnectionNodesIssue = issueLabel_issuesIssueLabelIssuesIssueConnectionNodesIssue

func XIssuePriorityValues(ctx_ context.Context, client_ graphql.Client) (data_ *issuePriorityValuesResponse, err_ error) {
	return issuePriorityValues(ctx_, client_)
}

type XIssuePriorityValuesIssuePriorityValuesIssuePriorityValue = issuePriorityValuesIssuePriorityValuesIssuePriorityValue

func XIssueRelation(ctx_ context.Context, client_ graphql.Client, id string) (data_ *issueRelationResponse, err_ error) {
	return issueRelation(ctx_, client_, id)
}

func XIssueRelations(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *issueRelationsResponse, err_ error) {
	return issueRelations(ctx_, client_, first, after, includeArchived)
}

type XIssueRelationsIssueRelationsIssueRelationConnectionNodesIssueRelation = issueRelationsIssueRelationsIssueRelationConnectionNodesIssueRelation

func XIssueSearch(ctx_ context.Context, client_ graphql.Client, teamId string, query string, first *int, after *string, includeArchived *bool) (data_ *issueSearchResponse, err_ error) {
	return issueSearch(ctx_, client_, teamId, query, first, after, includeArchived)
}

type XIssueSearchIssueSearchIssueConnectionNodesIssue = issueSearchIssueSearchIssueConnectionNodesIssue

func XIssueTitleSuggestionFromCustomerRequest(ctx_ context.Context, client_ graphql.Client, request string) (data_ *issueTitleSuggestionFromCustomerRequestResponse, err_ error) {
	return issueTitleSuggestionFromCustomerRequest(ctx_, client_, request)
}

func XIssueToRelease(ctx_ context.Context, client_ graphql.Client, id string) (data_ *issueToReleaseResponse, err_ error) {
	return issueToRelease(ctx_, client_, id)
}

func XIssueToReleases(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *issueToReleasesResponse, err_ error) {
	return issueToReleases(ctx_, client_, first, after, includeArchived)
}

type XIssueToReleasesIssueToReleasesIssueToReleaseConnectionNodesIssueToRelease = issueToReleasesIssueToReleasesIssueToReleaseConnectionNodesIssueToRelease

func XIssueVcsBranchSearch(ctx_ context.Context, client_ graphql.Client, branchName string) (data_ *issueVcsBranchSearchResponse, err_ error) {
	return issueVcsBranchSearch(ctx_, client_, branchName)
}

func XIssueVcsBranchSearch_attachments(ctx_ context.Context, client_ graphql.Client, branchName string, first *int, after *string, includeArchived *bool) (data_ *issueVcsBranchSearch_attachmentsResponse, err_ error) {
	return issueVcsBranchSearch_attachments(ctx_, client_, branchName, first, after, includeArchived)
}

func XIssueVcsBranchSearch_botActor(ctx_ context.Context, client_ graphql.Client, branchName string) (data_ *issueVcsBranchSearch_botActorResponse, err_ error) {
	return issueVcsBranchSearch_botActor(ctx_, client_, branchName)
}

func XIssueVcsBranchSearch_children(ctx_ context.Context, client_ graphql.Client, branchName string, first *int, after *string, includeArchived *bool) (data_ *issueVcsBranchSearch_childrenResponse, err_ error) {
	return issueVcsBranchSearch_children(ctx_, client_, branchName, first, after, includeArchived)
}

func XIssueVcsBranchSearch_comments(ctx_ context.Context, client_ graphql.Client, branchName string, first *int, after *string, includeArchived *bool) (data_ *issueVcsBranchSearch_commentsResponse, err_ error) {
	return issueVcsBranchSearch_comments(ctx_, client_, branchName, first, after, includeArchived)
}

func XIssueVcsBranchSearch_documents(ctx_ context.Context, client_ graphql.Client, branchName string, first *int, after *string, includeArchived *bool) (data_ *issueVcsBranchSearch_documentsResponse, err_ error) {
	return issueVcsBranchSearch_documents(ctx_, client_, branchName, first, after, includeArchived)
}

func XIssueVcsBranchSearch_formerAttachments(ctx_ context.Context, client_ graphql.Client, branchName string, first *int, after *string, includeArchived *bool) (data_ *issueVcsBranchSearch_formerAttachmentsResponse, err_ error) {
	return issueVcsBranchSearch_formerAttachments(ctx_, client_, branchName, first, after, includeArchived)
}

func XIssueVcsBranchSearch_formerNeeds(ctx_ context.Context, client_ graphql.Client, branchName string, first *int, after *string, includeArchived *bool) (data_ *issueVcsBranchSearch_formerNeedsResponse, err_ error) {
	return issueVcsBranchSearch_formerNeeds(ctx_, client_, branchName, first, after, includeArchived)
}

func XIssueVcsBranchSearch_history(ctx_ context.Context, client_ graphql.Client, branchName string, first *int, after *string, includeArchived *bool) (data_ *issueVcsBranchSearch_historyResponse, err_ error) {
	return issueVcsBranchSearch_history(ctx_, client_, branchName, first, after, includeArchived)
}

func XIssueVcsBranchSearch_inverseRelations(ctx_ context.Context, client_ graphql.Client, branchName string, first *int, after *string, includeArchived *bool) (data_ *issueVcsBranchSearch_inverseRelationsResponse, err_ error) {
	return issueVcsBranchSearch_inverseRelations(ctx_, client_, branchName, first, after, includeArchived)
}

func XIssueVcsBranchSearch_labels(ctx_ context.Context, client_ graphql.Client, branchName string, first *int, after *string, includeArchived *bool) (data_ *issueVcsBranchSearch_labelsResponse, err_ error) {
	return issueVcsBranchSearch_labels(ctx_, client_, branchName, first, after, includeArchived)
}

func XIssueVcsBranchSearch_needs(ctx_ context.Context, client_ graphql.Client, branchName string, first *int, after *string, includeArchived *bool) (data_ *issueVcsBranchSearch_needsResponse, err_ error) {
	return issueVcsBranchSearch_needs(ctx_, client_, branchName, first, after, includeArchived)
}

func XIssueVcsBranchSearch_relations(ctx_ context.Context, client_ graphql.Client, branchName string, first *int, after *string, includeArchived *bool) (data_ *issueVcsBranchSearch_relationsResponse, err_ error) {
	return issueVcsBranchSearch_relations(ctx_, client_, branchName, first, after, includeArchived)
}

func XIssueVcsBranchSearch_releases(ctx_ context.Context, client_ graphql.Client, branchName string, first *int, after *string, includeArchived *bool) (data_ *issueVcsBranchSearch_releasesResponse, err_ error) {
	return issueVcsBranchSearch_releases(ctx_, client_, branchName, first, after, includeArchived)
}

func XIssueVcsBranchSearch_sharedAccess(ctx_ context.Context, client_ graphql.Client, branchName string) (data_ *issueVcsBranchSearch_sharedAccessResponse, err_ error) {
	return issueVcsBranchSearch_sharedAccess(ctx_, client_, branchName)
}

func XIssueVcsBranchSearch_stateHistory(ctx_ context.Context, client_ graphql.Client, branchName string, first *int, after *string) (data_ *issueVcsBranchSearch_stateHistoryResponse, err_ error) {
	return issueVcsBranchSearch_stateHistory(ctx_, client_, branchName, first, after)
}

func XIssueVcsBranchSearch_subscribers(ctx_ context.Context, client_ graphql.Client, branchName string, first *int, after *string, includeArchived *bool) (data_ *issueVcsBranchSearch_subscribersResponse, err_ error) {
	return issueVcsBranchSearch_subscribers(ctx_, client_, branchName, first, after, includeArchived)
}

func XIssue_attachments(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *issue_attachmentsResponse, err_ error) {
	return issue_attachments(ctx_, client_, id, first, after, includeArchived)
}

func XIssue_botActor(ctx_ context.Context, client_ graphql.Client, id string) (data_ *issue_botActorResponse, err_ error) {
	return issue_botActor(ctx_, client_, id)
}

func XIssue_children(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *issue_childrenResponse, err_ error) {
	return issue_children(ctx_, client_, id, first, after, includeArchived)
}

func XIssue_comments(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *issue_commentsResponse, err_ error) {
	return issue_comments(ctx_, client_, id, first, after, includeArchived)
}

type XIssue_commentsIssueCommentsCommentConnectionNodesComment = issue_commentsIssueCommentsCommentConnectionNodesComment

func XIssue_documents(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *issue_documentsResponse, err_ error) {
	return issue_documents(ctx_, client_, id, first, after, includeArchived)
}

func XIssue_formerAttachments(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *issue_formerAttachmentsResponse, err_ error) {
	return issue_formerAttachments(ctx_, client_, id, first, after, includeArchived)
}

func XIssue_formerNeeds(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *issue_formerNeedsResponse, err_ error) {
	return issue_formerNeeds(ctx_, client_, id, first, after, includeArchived)
}

func XIssue_history(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *issue_historyResponse, err_ error) {
	return issue_history(ctx_, client_, id, first, after, includeArchived)
}

func XIssue_inverseRelations(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *issue_inverseRelationsResponse, err_ error) {
	return issue_inverseRelations(ctx_, client_, id, first, after, includeArchived)
}

func XIssue_labels(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *issue_labelsResponse, err_ error) {
	return issue_labels(ctx_, client_, id, first, after, includeArchived)
}

func XIssue_needs(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *issue_needsResponse, err_ error) {
	return issue_needs(ctx_, client_, id, first, after, includeArchived)
}

func XIssue_relations(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *issue_relationsResponse, err_ error) {
	return issue_relations(ctx_, client_, id, first, after, includeArchived)
}

func XIssue_releases(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *issue_releasesResponse, err_ error) {
	return issue_releases(ctx_, client_, id, first, after, includeArchived)
}

func XIssue_sharedAccess(ctx_ context.Context, client_ graphql.Client, id string) (data_ *issue_sharedAccessResponse, err_ error) {
	return issue_sharedAccess(ctx_, client_, id)
}

func XIssue_stateHistory(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string) (data_ *issue_stateHistoryResponse, err_ error) {
	return issue_stateHistory(ctx_, client_, id, first, after)
}

func XIssue_subscribers(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *issue_subscribersResponse, err_ error) {
	return issue_subscribers(ctx_, client_, id, first, after, includeArchived)
}

func XIssues(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *issuesResponse, err_ error) {
	return issues(ctx_, client_, first, after, includeArchived)
}

type XIssuesIssuesIssueConnectionNodesIssue = issuesIssuesIssueConnectionNodesIssue

func XNotification(ctx_ context.Context, client_ graphql.Client, id string) (data_ *notificationResponse, err_ error) {
	return notification(ctx_, client_, id)
}

func XNotificationSubscription(ctx_ context.Context, client_ graphql.Client, id string) (data_ *notificationSubscriptionResponse, err_ error) {
	return notificationSubscription(ctx_, client_, id)
}

func XNotificationSubscriptions(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *notificationSubscriptionsResponse, err_ error) {
	return notificationSubscriptions(ctx_, client_, first, after, includeArchived)
}

func XNotifications(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *notificationsResponse, err_ error) {
	return notifications(ctx_, client_, first, after, includeArchived)
}

type XNotificationsNotificationsNotificationConnectionNodesNotification = notificationsNotificationsNotificationConnectionNodesNotification

func XNotificationsUnreadCount(ctx_ context.Context, client_ graphql.Client) (data_ *notificationsUnreadCountResponse, err_ error) {
	return notificationsUnreadCount(ctx_, client_)
}

func XOrganizationExists(ctx_ context.Context, client_ graphql.Client, urlKey string) (data_ *organizationExistsResponse, err_ error) {
	return organizationExists(ctx_, client_, urlKey)
}

func XOrganization_labels(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *organization_labelsResponse, err_ error) {
	return organization_labels(ctx_, client_, first, after, includeArchived)
}

type XOrganization_labelsOrganizationLabelsIssueLabelConnectionNodesIssueLabel = organization_labelsOrganizationLabelsIssueLabelConnectionNodesIssueLabel

func XOrganization_projectLabels(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *organization_projectLabelsResponse, err_ error) {
	return organization_projectLabels(ctx_, client_, first, after, includeArchived)
}

type XOrganization_projectLabelsOrganizationProjectLabelsProjectLabelConnectionNodesProjectLabel = organization_projectLabelsOrganizationProjectLabelsProjectLabelConnectionNodesProjectLabel

func XOrganization_teams(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *organization_teamsResponse, err_ error) {
	return organization_teams(ctx_, client_, first, after, includeArchived)
}

type XOrganization_teamsOrganizationTeamsTeamConnectionNodesTeam = organization_teamsOrganizationTeamsTeamConnectionNodesTeam

func XOrganization_templates(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *organization_templatesResponse, err_ error) {
	return organization_templates(ctx_, client_, first, after, includeArchived)
}

type XOrganization_templatesOrganizationTemplatesTemplateConnectionNodesTemplate = organization_templatesOrganizationTemplatesTemplateConnectionNodesTemplate

func XOrganization_users(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *organization_usersResponse, err_ error) {
	return organization_users(ctx_, client_, first, after, includeArchived)
}

type XOrganization_usersOrganizationUsersUserConnectionNodesUser = organization_usersOrganizationUsersUserConnectionNodesUser

func XProject(ctx_ context.Context, client_ graphql.Client, id string) (data_ *projectResponse, err_ error) {
	return project(ctx_, client_, id)
}

func XProjectFilterSuggestion(ctx_ context.Context, client_ graphql.Client, prompt string, teamId *string) (data_ *projectFilterSuggestionResponse, err_ error) {
	return projectFilterSuggestion(ctx_, client_, prompt, teamId)
}

func XProjectLabel(ctx_ context.Context, client_ graphql.Client, id string) (data_ *projectLabelResponse, err_ error) {
	return projectLabel(ctx_, client_, id)
}

func XProjectLabel_children(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *projectLabel_childrenResponse, err_ error) {
	return projectLabel_children(ctx_, client_, id, first, after, includeArchived)
}

type XProjectLabel_childrenProjectLabelChildrenProjectLabelConnectionNodesProjectLabel = projectLabel_childrenProjectLabelChildrenProjectLabelConnectionNodesProjectLabel

func XProjectLabel_projects(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *projectLabel_projectsResponse, err_ error) {
	return projectLabel_projects(ctx_, client_, id, first, after, includeArchived)
}

type XProjectLabel_projectsProjectLabelProjectsProjectConnectionNodesProject = projectLabel_projectsProjectLabelProjectsProjectConnectionNodesProject

func XProjectLabels(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *projectLabelsResponse, err_ error) {
	return projectLabels(ctx_, client_, first, after, includeArchived)
}

type XProjectLabelsProjectLabelsProjectLabelConnectionNodesProjectLabel = projectLabelsProjectLabelsProjectLabelConnectionNodesProjectLabel

func XProjectMilestone(ctx_ context.Context, client_ graphql.Client, id string) (data_ *projectMilestoneResponse, err_ error) {
	return projectMilestone(ctx_, client_, id)
}

func XProjectMilestone_issues(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *projectMilestone_issuesResponse, err_ error) {
	return projectMilestone_issues(ctx_, client_, id, first, after, includeArchived)
}

type XProjectMilestone_issuesProjectMilestoneIssuesIssueConnectionNodesIssue = projectMilestone_issuesProjectMilestoneIssuesIssueConnectionNodesIssue

func XProjectMilestones(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *projectMilestonesResponse, err_ error) {
	return projectMilestones(ctx_, client_, first, after, includeArchived)
}

type XProjectMilestonesProjectMilestonesProjectMilestoneConnectionNodesProjectMilestone = projectMilestonesProjectMilestonesProjectMilestoneConnectionNodesProjectMilestone

func XProjectRelation(ctx_ context.Context, client_ graphql.Client, id string) (data_ *projectRelationResponse, err_ error) {
	return projectRelation(ctx_, client_, id)
}

func XProjectRelations(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *projectRelationsResponse, err_ error) {
	return projectRelations(ctx_, client_, first, after, includeArchived)
}

type XProjectRelationsProjectRelationsProjectRelationConnectionNodesProjectRelation = projectRelationsProjectRelationsProjectRelationConnectionNodesProjectRelation

func XProjectStatus(ctx_ context.Context, client_ graphql.Client, id string) (data_ *projectStatusResponse, err_ error) {
	return projectStatus(ctx_, client_, id)
}

func XProjectStatusProjectCount(ctx_ context.Context, client_ graphql.Client, id string) (data_ *projectStatusProjectCountResponse, err_ error) {
	return projectStatusProjectCount(ctx_, client_, id)
}

func XProjectStatuses(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *projectStatusesResponse, err_ error) {
	return projectStatuses(ctx_, client_, first, after, includeArchived)
}

type XProjectStatusesProjectStatusesProjectStatusConnectionNodesProjectStatus = projectStatusesProjectStatusesProjectStatusConnectionNodesProjectStatus

func XProjectUpdate(ctx_ context.Context, client_ graphql.Client, id string) (data_ *projectUpdateResponse, err_ error) {
	return projectUpdate(ctx_, client_, id)
}

func XProjectUpdate_comments(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *projectUpdate_commentsResponse, err_ error) {
	return projectUpdate_comments(ctx_, client_, id, first, after, includeArchived)
}

type XProjectUpdate_commentsProjectUpdateCommentsCommentConnectionNodesComment = projectUpdate_commentsProjectUpdateCommentsCommentConnectionNodesComment

func XProjectUpdates(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *projectUpdatesResponse, err_ error) {
	return projectUpdates(ctx_, client_, first, after, includeArchived)
}

type XProjectUpdatesProjectUpdatesProjectUpdateConnectionNodesProjectUpdate = projectUpdatesProjectUpdatesProjectUpdateConnectionNodesProjectUpdate

func XProject_attachments(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *project_attachmentsResponse, err_ error) {
	return project_attachments(ctx_, client_, id, first, after, includeArchived)
}

type XProject_attachmentsProjectAttachmentsProjectAttachmentConnectionNodesProjectAttachment = project_attachmentsProjectAttachmentsProjectAttachmentConnectionNodesProjectAttachment

func XProject_comments(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *project_commentsResponse, err_ error) {
	return project_comments(ctx_, client_, id, first, after, includeArchived)
}

type XProject_commentsProjectCommentsCommentConnectionNodesComment = project_commentsProjectCommentsCommentConnectionNodesComment

func XProject_documents(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *project_documentsResponse, err_ error) {
	return project_documents(ctx_, client_, id, first, after, includeArchived)
}

type XProject_documentsProjectDocumentsDocumentConnectionNodesDocument = project_documentsProjectDocumentsDocumentConnectionNodesDocument

func XProject_externalLinks(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *project_externalLinksResponse, err_ error) {
	return project_externalLinks(ctx_, client_, id, first, after, includeArchived)
}

type XProject_externalLinksProjectExternalLinksEntityExternalLinkConnectionNodesEntityExternalLink = project_externalLinksProjectExternalLinksEntityExternalLinkConnectionNodesEntityExternalLink

func XProject_history(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *project_historyResponse, err_ error) {
	return project_history(ctx_, client_, id, first, after, includeArchived)
}

type XProject_historyProjectHistoryProjectHistoryConnectionNodesProjectHistory = project_historyProjectHistoryProjectHistoryConnectionNodesProjectHistory

func XProject_initiativeToProjects(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *project_initiativeToProjectsResponse, err_ error) {
	return project_initiativeToProjects(ctx_, client_, id, first, after, includeArchived)
}

type XProject_initiativeToProjectsProjectInitiativeToProjectsInitiativeToProjectConnectionNodesInitiativeToProject = project_initiativeToProjectsProjectInitiativeToProjectsInitiativeToProjectConnectionNodesInitiativeToProject

func XProject_initiatives(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *project_initiativesResponse, err_ error) {
	return project_initiatives(ctx_, client_, id, first, after, includeArchived)
}

type XProject_initiativesProjectInitiativesInitiativeConnectionNodesInitiative = project_initiativesProjectInitiativesInitiativeConnectionNodesInitiative

func XProject_inverseRelations(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *project_inverseRelationsResponse, err_ error) {
	return project_inverseRelations(ctx_, client_, id, first, after, includeArchived)
}

type XProject_inverseRelationsProjectInverseRelationsProjectRelationConnectionNodesProjectRelation = project_inverseRelationsProjectInverseRelationsProjectRelationConnectionNodesProjectRelation

func XProject_issues(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *project_issuesResponse, err_ error) {
	return project_issues(ctx_, client_, id, first, after, includeArchived)
}

type XProject_issuesProjectIssuesIssueConnectionNodesIssue = project_issuesProjectIssuesIssueConnectionNodesIssue

func XProject_labels(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *project_labelsResponse, err_ error) {
	return project_labels(ctx_, client_, id, first, after, includeArchived)
}

type XProject_labelsProjectLabelsProjectLabelConnectionNodesProjectLabel = project_labelsProjectLabelsProjectLabelConnectionNodesProjectLabel

func XProject_members(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *project_membersResponse, err_ error) {
	return project_members(ctx_, client_, id, first, after, includeArchived)
}

type XProject_membersProjectMembersUserConnectionNodesUser = project_membersProjectMembersUserConnectionNodesUser

func XProject_needs(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *project_needsResponse, err_ error) {
	return project_needs(ctx_, client_, id, first, after, includeArchived)
}

type XProject_needsProjectNeedsCustomerNeedConnectionNodesCustomerNeed = project_needsProjectNeedsCustomerNeedConnectionNodesCustomerNeed

func XProject_projectMilestones(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *project_projectMilestonesResponse, err_ error) {
	return project_projectMilestones(ctx_, client_, id, first, after, includeArchived)
}

type XProject_projectMilestonesProjectProjectMilestonesProjectMilestoneConnectionNodesProjectMilestone = project_projectMilestonesProjectProjectMilestonesProjectMilestoneConnectionNodesProjectMilestone

func XProject_projectUpdates(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *project_projectUpdatesResponse, err_ error) {
	return project_projectUpdates(ctx_, client_, id, first, after, includeArchived)
}

type XProject_projectUpdatesProjectProjectUpdatesProjectUpdateConnectionNodesProjectUpdate = project_projectUpdatesProjectProjectUpdatesProjectUpdateConnectionNodesProjectUpdate

func XProject_relations(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *project_relationsResponse, err_ error) {
	return project_relations(ctx_, client_, id, first, after, includeArchived)
}

type XProject_relationsProjectRelationsProjectRelationConnectionNodesProjectRelation = project_relationsProjectRelationsProjectRelationConnectionNodesProjectRelation

func XProject_teams(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *project_teamsResponse, err_ error) {
	return project_teams(ctx_, client_, id, first, after, includeArchived)
}

type XProject_teamsProjectTeamsTeamConnectionNodesTeam = project_teamsProjectTeamsTeamConnectionNodesTeam

func XProjects(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *projectsResponse, err_ error) {
	return projects(ctx_, client_, first, after, includeArchived)
}

type XProjectsProjectsProjectConnectionNodesProject = projectsProjectsProjectConnectionNodesProject

func XRateLimitStatus(ctx_ context.Context, client_ graphql.Client) (data_ *rateLimitStatusResponse, err_ error) {
	return rateLimitStatus(ctx_, client_)
}

type XRateLimitStatusRateLimitStatusRateLimitPayloadLimitsRateLimitResultPayload = rateLimitStatusRateLimitStatusRateLimitPayloadLimitsRateLimitResultPayload

func XRelease(ctx_ context.Context, client_ graphql.Client, id string) (data_ *releaseResponse, err_ error) {
	return release(ctx_, client_, id)
}

func XReleaseNote(ctx_ context.Context, client_ graphql.Client, id string) (data_ *releaseNoteResponse, err_ error) {
	return releaseNote(ctx_, client_, id)
}

func XReleaseNotes(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *releaseNotesResponse, err_ error) {
	return releaseNotes(ctx_, client_, first, after, includeArchived)
}

type XReleaseNotesReleaseNotesReleaseNoteConnectionNodesReleaseNote = releaseNotesReleaseNotesReleaseNoteConnectionNodesReleaseNote

func XReleasePipeline(ctx_ context.Context, client_ graphql.Client, id string) (data_ *releasePipelineResponse, err_ error) {
	return releasePipeline(ctx_, client_, id)
}

func XReleasePipeline_releases(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *releasePipeline_releasesResponse, err_ error) {
	return releasePipeline_releases(ctx_, client_, id, first, after, includeArchived)
}

type XReleasePipeline_releasesReleasePipelineReleasesReleaseConnectionNodesRelease = releasePipeline_releasesReleasePipelineReleasesReleaseConnectionNodesRelease

func XReleasePipeline_stages(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *releasePipeline_stagesResponse, err_ error) {
	return releasePipeline_stages(ctx_, client_, id, first, after, includeArchived)
}

type XReleasePipeline_stagesReleasePipelineStagesReleaseStageConnectionNodesReleaseStage = releasePipeline_stagesReleasePipelineStagesReleaseStageConnectionNodesReleaseStage

func XReleasePipeline_teams(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *releasePipeline_teamsResponse, err_ error) {
	return releasePipeline_teams(ctx_, client_, id, first, after, includeArchived)
}

type XReleasePipeline_teamsReleasePipelineTeamsTeamConnectionNodesTeam = releasePipeline_teamsReleasePipelineTeamsTeamConnectionNodesTeam

func XReleasePipelines(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *releasePipelinesResponse, err_ error) {
	return releasePipelines(ctx_, client_, first, after, includeArchived)
}

type XReleasePipelinesReleasePipelinesReleasePipelineConnectionNodesReleasePipeline = releasePipelinesReleasePipelinesReleasePipelineConnectionNodesReleasePipeline

func XReleaseSearch(ctx_ context.Context, client_ graphql.Client, term *string, first *int) (data_ *releaseSearchResponse, err_ error) {
	return releaseSearch(ctx_, client_, term, first)
}

type XReleaseSearchReleaseSearchRelease = releaseSearchReleaseSearchRelease

func XReleaseStage(ctx_ context.Context, client_ graphql.Client, id string) (data_ *releaseStageResponse, err_ error) {
	return releaseStage(ctx_, client_, id)
}

func XReleaseStage_releases(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *releaseStage_releasesResponse, err_ error) {
	return releaseStage_releases(ctx_, client_, id, first, after, includeArchived)
}

type XReleaseStage_releasesReleaseStageReleasesReleaseConnectionNodesRelease = releaseStage_releasesReleaseStageReleasesReleaseConnectionNodesRelease

func XReleaseStages(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *releaseStagesResponse, err_ error) {
	return releaseStages(ctx_, client_, first, after, includeArchived)
}

type XReleaseStagesReleaseStagesReleaseStageConnectionNodesReleaseStage = releaseStagesReleaseStagesReleaseStageConnectionNodesReleaseStage

func XRelease_documents(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *release_documentsResponse, err_ error) {
	return release_documents(ctx_, client_, id, first, after, includeArchived)
}

type XRelease_documentsReleaseDocumentsDocumentConnectionNodesDocument = release_documentsReleaseDocumentsDocumentConnectionNodesDocument

func XRelease_history(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *release_historyResponse, err_ error) {
	return release_history(ctx_, client_, id, first, after, includeArchived)
}

type XRelease_historyReleaseHistoryReleaseHistoryConnectionNodesReleaseHistory = release_historyReleaseHistoryReleaseHistoryConnectionNodesReleaseHistory

func XRelease_issues(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *release_issuesResponse, err_ error) {
	return release_issues(ctx_, client_, id, first, after, includeArchived)
}

type XRelease_issuesReleaseIssuesIssueConnectionNodesIssue = release_issuesReleaseIssuesIssueConnectionNodesIssue

func XRelease_links(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *release_linksResponse, err_ error) {
	return release_links(ctx_, client_, id, first, after, includeArchived)
}

type XRelease_linksReleaseLinksEntityExternalLinkConnectionNodesEntityExternalLink = release_linksReleaseLinksEntityExternalLinkConnectionNodesEntityExternalLink

func XReleases(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *releasesResponse, err_ error) {
	return releases(ctx_, client_, first, after, includeArchived)
}

type XReleasesReleasesReleaseConnectionNodesRelease = releasesReleasesReleaseConnectionNodesRelease

func XRoadmap(ctx_ context.Context, client_ graphql.Client, id string) (data_ *roadmapResponse, err_ error) {
	return roadmap(ctx_, client_, id)
}

func XRoadmapToProject(ctx_ context.Context, client_ graphql.Client, id string) (data_ *roadmapToProjectResponse, err_ error) {
	return roadmapToProject(ctx_, client_, id)
}

func XRoadmapToProjects(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *roadmapToProjectsResponse, err_ error) {
	return roadmapToProjects(ctx_, client_, first, after, includeArchived)
}

type XRoadmapToProjectsRoadmapToProjectsRoadmapToProjectConnectionNodesRoadmapToProject = roadmapToProjectsRoadmapToProjectsRoadmapToProjectConnectionNodesRoadmapToProject

func XRoadmap_projects(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *roadmap_projectsResponse, err_ error) {
	return roadmap_projects(ctx_, client_, id, first, after, includeArchived)
}

type XRoadmap_projectsRoadmapProjectsProjectConnectionNodesProject = roadmap_projectsRoadmapProjectsProjectConnectionNodesProject

func XRoadmaps(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *roadmapsResponse, err_ error) {
	return roadmaps(ctx_, client_, first, after, includeArchived)
}

type XRoadmapsRoadmapsRoadmapConnectionNodesRoadmap = roadmapsRoadmapsRoadmapConnectionNodesRoadmap

func XSearchDocuments(ctx_ context.Context, client_ graphql.Client, term string, first *int, after *string) (data_ *searchDocumentsResponse, err_ error) {
	return searchDocuments(ctx_, client_, term, first, after)
}

type XSearchDocumentsSearchDocumentsDocumentSearchPayloadNodesDocumentSearchResult = searchDocumentsSearchDocumentsDocumentSearchPayloadNodesDocumentSearchResult

func XSearchIssues(ctx_ context.Context, client_ graphql.Client, term string, first *int, after *string) (data_ *searchIssuesResponse, err_ error) {
	return searchIssues(ctx_, client_, term, first, after)
}

type XSearchIssuesSearchIssuesIssueSearchPayloadNodesIssueSearchResult = searchIssuesSearchIssuesIssueSearchPayloadNodesIssueSearchResult

func XSearchProjects(ctx_ context.Context, client_ graphql.Client, term string, first *int, after *string) (data_ *searchProjectsResponse, err_ error) {
	return searchProjects(ctx_, client_, term, first, after)
}

type XSearchProjectsSearchProjectsProjectSearchPayloadNodesProjectSearchResult = searchProjectsSearchProjectsProjectSearchPayloadNodesProjectSearchResult

func XSemanticSearch(ctx_ context.Context, client_ graphql.Client, query string, maxResults *int, includeArchived *bool) (data_ *semanticSearchResponse, err_ error) {
	return semanticSearch(ctx_, client_, query, maxResults, includeArchived)
}

type XSemanticSearchSemanticSearchSemanticSearchPayloadResultsSemanticSearchResult = semanticSearchSemanticSearchSemanticSearchPayloadResultsSemanticSearchResult

func XSlaConfigurations(ctx_ context.Context, client_ graphql.Client, teamId string) (data_ *slaConfigurationsResponse, err_ error) {
	return slaConfigurations(ctx_, client_, teamId)
}

type XSlaConfigurationsSlaConfigurationsSlaConfiguration = slaConfigurationsSlaConfigurationsSlaConfiguration

func XTeam(ctx_ context.Context, client_ graphql.Client, id string) (data_ *teamResponse, err_ error) {
	return team(ctx_, client_, id)
}

func XTeamEstimateConfig(ctx_ context.Context, client_ graphql.Client, id string) (data_ *teamEstimateConfigResponse, err_ error) {
	return teamEstimateConfig(ctx_, client_, id)
}

func XTeamMembership(ctx_ context.Context, client_ graphql.Client, id string) (data_ *teamMembershipResponse, err_ error) {
	return teamMembership(ctx_, client_, id)
}

func XTeamMemberships(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *teamMembershipsResponse, err_ error) {
	return teamMemberships(ctx_, client_, first, after, includeArchived)
}

type XTeamMembershipsTeamMembershipsTeamMembershipConnectionNodesTeamMembership = teamMembershipsTeamMembershipsTeamMembershipConnectionNodesTeamMembership

func XTeam_cycles(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *team_cyclesResponse, err_ error) {
	return team_cycles(ctx_, client_, id, first, after, includeArchived)
}

type XTeam_cyclesTeamCyclesCycleConnectionNodesCycle = team_cyclesTeamCyclesCycleConnectionNodesCycle

func XTeam_gitAutomationStates(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *team_gitAutomationStatesResponse, err_ error) {
	return team_gitAutomationStates(ctx_, client_, id, first, after, includeArchived)
}

type XTeam_gitAutomationStatesTeamGitAutomationStatesGitAutomationStateConnectionNodesGitAutomationState = team_gitAutomationStatesTeamGitAutomationStatesGitAutomationStateConnectionNodesGitAutomationState

func XTeam_issues(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *team_issuesResponse, err_ error) {
	return team_issues(ctx_, client_, id, first, after, includeArchived)
}

type XTeam_issuesTeamIssuesIssueConnectionNodesIssue = team_issuesTeamIssuesIssueConnectionNodesIssue

func XTeam_labels(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *team_labelsResponse, err_ error) {
	return team_labels(ctx_, client_, id, first, after, includeArchived)
}

type XTeam_labelsTeamLabelsIssueLabelConnectionNodesIssueLabel = team_labelsTeamLabelsIssueLabelConnectionNodesIssueLabel

func XTeam_members(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *team_membersResponse, err_ error) {
	return team_members(ctx_, client_, id, first, after, includeArchived)
}

type XTeam_membersTeamMembersUserConnectionNodesUser = team_membersTeamMembersUserConnectionNodesUser

func XTeam_memberships(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *team_membershipsResponse, err_ error) {
	return team_memberships(ctx_, client_, id, first, after, includeArchived)
}

type XTeam_membershipsTeamMembershipsTeamMembershipConnectionNodesTeamMembership = team_membershipsTeamMembershipsTeamMembershipConnectionNodesTeamMembership

func XTeam_projects(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *team_projectsResponse, err_ error) {
	return team_projects(ctx_, client_, id, first, after, includeArchived)
}

type XTeam_projectsTeamProjectsProjectConnectionNodesProject = team_projectsTeamProjectsProjectConnectionNodesProject

func XTeam_releasePipelines(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *team_releasePipelinesResponse, err_ error) {
	return team_releasePipelines(ctx_, client_, id, first, after, includeArchived)
}

type XTeam_releasePipelinesTeamReleasePipelinesReleasePipelineConnectionNodesReleasePipeline = team_releasePipelinesTeamReleasePipelinesReleasePipelineConnectionNodesReleasePipeline

func XTeam_states(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *team_statesResponse, err_ error) {
	return team_states(ctx_, client_, id, first, after, includeArchived)
}

type XTeam_statesTeamStatesWorkflowStateConnectionNodesWorkflowState = team_statesTeamStatesWorkflowStateConnectionNodesWorkflowState

func XTeam_templates(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *team_templatesResponse, err_ error) {
	return team_templates(ctx_, client_, id, first, after, includeArchived)
}

type XTeam_templatesTeamTemplatesTemplateConnectionNodesTemplate = team_templatesTeamTemplatesTemplateConnectionNodesTemplate

func XTeams_list(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *teams_listResponse, err_ error) {
	return teams_list(ctx_, client_, first, after, includeArchived)
}

type XTeams_listTeamsTeamConnectionNodesTeam = teams_listTeamsTeamConnectionNodesTeam

func XTemplate(ctx_ context.Context, client_ graphql.Client, id string) (data_ *templateResponse, err_ error) {
	return template(ctx_, client_, id)
}

func XTemplateContent(ctx_ context.Context, client_ graphql.Client, id string) (data_ *templateContentResponse, err_ error) {
	return templateContent(ctx_, client_, id)
}

func XTemplates(ctx_ context.Context, client_ graphql.Client) (data_ *templatesResponse, err_ error) {
	return templates(ctx_, client_)
}

func XTimeSchedule(ctx_ context.Context, client_ graphql.Client, id string) (data_ *timeScheduleResponse, err_ error) {
	return timeSchedule(ctx_, client_, id)
}

func XTimeSchedules(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *timeSchedulesResponse, err_ error) {
	return timeSchedules(ctx_, client_, first, after, includeArchived)
}

type XTimeSchedulesTimeSchedulesTimeScheduleConnectionNodesTimeSchedule = timeSchedulesTimeSchedulesTimeScheduleConnectionNodesTimeSchedule

func XTriageResponsibilities(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *triageResponsibilitiesResponse, err_ error) {
	return triageResponsibilities(ctx_, client_, first, after, includeArchived)
}

type XTriageResponsibilitiesTriageResponsibilitiesTriageResponsibilityConnectionNodesTriageResponsibility = triageResponsibilitiesTriageResponsibilitiesTriageResponsibilityConnectionNodesTriageResponsibility

func XTriageResponsibility(ctx_ context.Context, client_ graphql.Client, id string) (data_ *triageResponsibilityResponse, err_ error) {
	return triageResponsibility(ctx_, client_, id)
}

func XTriageResponsibility_manualSelection(ctx_ context.Context, client_ graphql.Client, id string) (data_ *triageResponsibility_manualSelectionResponse, err_ error) {
	return triageResponsibility_manualSelection(ctx_, client_, id)
}

func XUser(ctx_ context.Context, client_ graphql.Client, id string) (data_ *userResponse, err_ error) {
	return user(ctx_, client_, id)
}

func XUserSettings(ctx_ context.Context, client_ graphql.Client) (data_ *userSettingsResponse, err_ error) {
	return userSettings(ctx_, client_)
}

func XUserSettings_notificationCategoryPreferences(ctx_ context.Context, client_ graphql.Client) (data_ *userSettings_notificationCategoryPreferencesResponse, err_ error) {
	return userSettings_notificationCategoryPreferences(ctx_, client_)
}

func XUserSettings_notificationChannelPreferences(ctx_ context.Context, client_ graphql.Client) (data_ *userSettings_notificationChannelPreferencesResponse, err_ error) {
	return userSettings_notificationChannelPreferences(ctx_, client_)
}

func XUserSettings_notificationDeliveryPreferences(ctx_ context.Context, client_ graphql.Client) (data_ *userSettings_notificationDeliveryPreferencesResponse, err_ error) {
	return userSettings_notificationDeliveryPreferences(ctx_, client_)
}

func XUserSettings_notificationDeliveryPreferences_mobile(ctx_ context.Context, client_ graphql.Client) (data_ *userSettings_notificationDeliveryPreferences_mobileResponse, err_ error) {
	return userSettings_notificationDeliveryPreferences_mobile(ctx_, client_)
}

func XUserSettings_notificationDeliveryPreferences_mobile_schedule(ctx_ context.Context, client_ graphql.Client) (data_ *userSettings_notificationDeliveryPreferences_mobile_scheduleResponse, err_ error) {
	return userSettings_notificationDeliveryPreferences_mobile_schedule(ctx_, client_)
}

func XUserSettings_theme(ctx_ context.Context, client_ graphql.Client, deviceType *UserSettingsThemeDeviceType, mode *UserSettingsThemeMode) (data_ *userSettings_themeResponse, err_ error) {
	return userSettings_theme(ctx_, client_, deviceType, mode)
}

func XUserSettings_theme_custom(ctx_ context.Context, client_ graphql.Client, deviceType *UserSettingsThemeDeviceType, mode *UserSettingsThemeMode) (data_ *userSettings_theme_customResponse, err_ error) {
	return userSettings_theme_custom(ctx_, client_, deviceType, mode)
}

func XUserSettings_theme_custom_sidebar(ctx_ context.Context, client_ graphql.Client, deviceType *UserSettingsThemeDeviceType, mode *UserSettingsThemeMode) (data_ *userSettings_theme_custom_sidebarResponse, err_ error) {
	return userSettings_theme_custom_sidebar(ctx_, client_, deviceType, mode)
}

func XUser_assignedIssues(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *user_assignedIssuesResponse, err_ error) {
	return user_assignedIssues(ctx_, client_, id, first, after, includeArchived)
}

type XUser_assignedIssuesUserAssignedIssuesIssueConnectionNodesIssue = user_assignedIssuesUserAssignedIssuesIssueConnectionNodesIssue

func XUser_createdIssues(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *user_createdIssuesResponse, err_ error) {
	return user_createdIssues(ctx_, client_, id, first, after, includeArchived)
}

type XUser_createdIssuesUserCreatedIssuesIssueConnectionNodesIssue = user_createdIssuesUserCreatedIssuesIssueConnectionNodesIssue

func XUser_delegatedIssues(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *user_delegatedIssuesResponse, err_ error) {
	return user_delegatedIssues(ctx_, client_, id, first, after, includeArchived)
}

type XUser_delegatedIssuesUserDelegatedIssuesIssueConnectionNodesIssue = user_delegatedIssuesUserDelegatedIssuesIssueConnectionNodesIssue

func XUser_teamMemberships(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *user_teamMembershipsResponse, err_ error) {
	return user_teamMemberships(ctx_, client_, id, first, after, includeArchived)
}

type XUser_teamMembershipsUserTeamMembershipsTeamMembershipConnectionNodesTeamMembership = user_teamMembershipsUserTeamMembershipsTeamMembershipConnectionNodesTeamMembership

func XUser_teams(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *user_teamsResponse, err_ error) {
	return user_teams(ctx_, client_, id, first, after, includeArchived)
}

type XUser_teamsUserTeamsTeamConnectionNodesTeam = user_teamsUserTeamsTeamConnectionNodesTeam

func XUsers(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool, includeDisabled *bool) (data_ *usersResponse, err_ error) {
	return users(ctx_, client_, first, after, includeArchived, includeDisabled)
}

type XUsersUsersUserConnectionNodesUser = usersUsersUserConnectionNodesUser

func XViewer(ctx_ context.Context, client_ graphql.Client) (data_ *viewerResponse, err_ error) {
	return viewer(ctx_, client_)
}

func XViewer_assignedIssues(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *viewer_assignedIssuesResponse, err_ error) {
	return viewer_assignedIssues(ctx_, client_, first, after, includeArchived)
}

type XViewer_assignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue = viewer_assignedIssuesViewerUserAssignedIssuesIssueConnectionNodesIssue

func XViewer_createdIssues(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *viewer_createdIssuesResponse, err_ error) {
	return viewer_createdIssues(ctx_, client_, first, after, includeArchived)
}

type XViewer_createdIssuesViewerUserCreatedIssuesIssueConnectionNodesIssue = viewer_createdIssuesViewerUserCreatedIssuesIssueConnectionNodesIssue

func XViewer_delegatedIssues(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *viewer_delegatedIssuesResponse, err_ error) {
	return viewer_delegatedIssues(ctx_, client_, first, after, includeArchived)
}

type XViewer_delegatedIssuesViewerUserDelegatedIssuesIssueConnectionNodesIssue = viewer_delegatedIssuesViewerUserDelegatedIssuesIssueConnectionNodesIssue

func XViewer_drafts(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *viewer_draftsResponse, err_ error) {
	return viewer_drafts(ctx_, client_, first, after, includeArchived)
}

type XViewer_draftsViewerUserDraftsDraftConnectionNodesDraft = viewer_draftsViewerUserDraftsDraftConnectionNodesDraft

func XViewer_teamMemberships(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *viewer_teamMembershipsResponse, err_ error) {
	return viewer_teamMemberships(ctx_, client_, first, after, includeArchived)
}

type XViewer_teamMembershipsViewerUserTeamMembershipsTeamMembershipConnectionNodesTeamMembership = viewer_teamMembershipsViewerUserTeamMembershipsTeamMembershipConnectionNodesTeamMembership

func XViewer_teams(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *viewer_teamsResponse, err_ error) {
	return viewer_teams(ctx_, client_, first, after, includeArchived)
}

type XViewer_teamsViewerUserTeamsTeamConnectionNodesTeam = viewer_teamsViewerUserTeamsTeamConnectionNodesTeam

func XWorkflowState(ctx_ context.Context, client_ graphql.Client, id string) (data_ *workflowStateResponse, err_ error) {
	return workflowState(ctx_, client_, id)
}

func XWorkflowState_issues(ctx_ context.Context, client_ graphql.Client, id string, first *int, after *string, includeArchived *bool) (data_ *workflowState_issuesResponse, err_ error) {
	return workflowState_issues(ctx_, client_, id, first, after, includeArchived)
}

type XWorkflowState_issuesWorkflowStateIssuesIssueConnectionNodesIssue = workflowState_issuesWorkflowStateIssuesIssueConnectionNodesIssue

func XWorkflowStates(ctx_ context.Context, client_ graphql.Client, first *int, after *string, includeArchived *bool) (data_ *workflowStatesResponse, err_ error) {
	return workflowStates(ctx_, client_, first, after, includeArchived)
}

type XWorkflowStatesWorkflowStatesWorkflowStateConnectionNodesWorkflowState = workflowStatesWorkflowStatesWorkflowStateConnectionNodesWorkflowState
