//go:build ignore

// Command gen-skill renders the linctl agent command references from the cobra
// command tree: the full command inventory
// (skills/linctl/references/commands.md) and the guarded-write list
// (skills/linctl/references/guarded-writes.md).
//
// The curated skills/linctl/SKILL.md is hand-maintained and intentionally not a
// command dump; this generator produces the always-current full command
// inventory it links to. It is a standalone maintenance tool, excluded from the
// module build/vet/lint/test graph via the ignore build tag (and from
// scripts/go-packages.sh). Run it with `go run scripts/gen-skill.go` or
// `task gen-skill`. CI re-runs it and fails if the committed reference differs
// from the binary's command surface, so the agent-facing doc can never drift.
//
// The generator reads only the in-memory cobra command tree: no Linear API call,
// no token, no schema change.
package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/KyaniteHQ/linctl/internal/cli"
)

const (
	commandsPath      = "skills/linctl/references/commands.md"
	guardedWritesPath = "skills/linctl/references/guarded-writes.md"
)

func main() {
	root := cli.NewRootCommand(context.Background(), cli.BuildInfo{})

	var commands strings.Builder
	writeHeader(&commands, root)
	writeCommandTree(&commands, root)

	var writes strings.Builder
	writeGuardedWriteReference(&writes, root)

	write(commandsPath, commands.String())
	write(guardedWritesPath, writes.String())
}

func write(path string, content string) {
	content = strings.TrimRight(content, "\n") + "\n"
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "gen-skill:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil { //nolint:gosec // generated docs are world-readable
		fmt.Fprintln(os.Stderr, "gen-skill:", err)
		os.Exit(1)
	}
}

func writeHeader(builder *strings.Builder, root *cobra.Command) {
	fmt.Fprintf(builder, "# %s command reference\n\n", root.Name())
	fmt.Fprintf(builder, "%s\n\n", root.Short)
	builder.WriteString(
		"Generated by `scripts/gen-skill.go` from the linctl command tree. " +
			"Do not edit by hand; run `task gen-skill` to refresh it. This is the full " +
			"command inventory linked from `SKILL.md`.\n\n",
	)
	if usages := strings.TrimRight(root.PersistentFlags().FlagUsages(), "\n"); usages != "" {
		builder.WriteString("## Global flags\n\n```\n")
		builder.WriteString(usages)
		builder.WriteString("\n```\n\n")
	}
	builder.WriteString("## Commands\n\n")
}

// writeEntry is one write-classified command plus the flag facts the reference
// reports about it.
type writeEntry struct {
	info    cli.CommandInfo
	orgWide bool
}

// writeGuardedWriteReference renders the complete write surface from the
// command tree. It exits non-zero when a runnable write command does not
// declare a write effect, so a new write can never be missing from the list.
func writeGuardedWriteReference(builder *strings.Builder, root *cobra.Command) {
	byPath := map[string]*cobra.Command{}
	collectCommands(root, byPath)

	var guarded, unguarded, local []writeEntry
	for _, info := range cli.CommandInventory(root) {
		command := byPath[info.Path]
		// A write-classified group command only routes to subcommands; the
		// subcommands carry the effect.
		if info.Safety != cli.CommandSafetyWrite || command == nil || command.HasSubCommands() {
			continue
		}
		entry := writeEntry{info: info, orgWide: command.Flags().Lookup("org-wide") != nil}
		switch info.WriteEffect {
		case cli.WriteEffectGuarded:
			guarded = append(guarded, entry)
		case cli.WriteEffectUnguarded:
			unguarded = append(unguarded, entry)
		case cli.WriteEffectLocal:
			local = append(local, entry)
		case cli.WriteEffectNone:
			fmt.Fprintf(
				os.Stderr,
				"gen-skill: command %q writes but declares no write effect; register it with addWriteCommand\n",
				info.Path,
			)
			os.Exit(1)
		}
	}

	writeGuardedWriteHeader(builder, len(cli.SortedAvailableCommands(root)), len(guarded))
	writeGuardedWriteGroups(builder, guarded)
	writeOtherWriteSection(
		builder,
		"Writes to Linear outside the target guard",
		"These commands change Linear. The entity has no team and no project, so linctl has no "+
			"pinned scope to compare. Control them with the scope of the OAuth credential.",
		unguarded,
	)
	writeOtherWriteSection(
		builder,
		"Writes to this machine only",
		"These commands read Linear and write a file on the local machine. They do not change Linear.",
		local,
	)
}

func writeGuardedWriteHeader(builder *strings.Builder, groupCount int, guardedCount int) {
	builder.WriteString("# linctl guarded writes\n\n")
	builder.WriteString(
		"Generated by `scripts/gen-skill.go` from the linctl command tree. Do not edit by hand; " +
			"run `task gen-skill` to refresh it. CI fails when this file and the command tree disagree.\n\n",
	)
	fmt.Fprintf(
		builder,
		"linctl has %d top-level commands. %d of them are guarded writes.\n\n",
		groupCount,
		guardedCount,
	)
	builder.WriteString("## Guarded writes\n\n")
	builder.WriteString(
		"Each command below changes Linear. Before the change, linctl resolves the target from the " +
			"live OAuth credential and compares it with the target pinned in `.linctl.toml`. " +
			"A mismatch is a hard stop: linctl makes no change, prints " +
			"`{\"error_code\":\"TARGET_MISMATCH\"}`, and exits non-zero. No flag makes a " +
			"mismatched write proceed.\n\n",
	)
	builder.WriteString("Two notes appear in the tables:\n\n")
	builder.WriteString(
		"- **org-wide** — the command has an `--org-wide` flag. The entity has no team, so the " +
			"comparison is organization-only. The flag makes the blast radius explicit. " +
			"It is not a bypass, and a mismatch is still a hard stop.\n",
	)
	builder.WriteString(
		"- **irreversible** — linctl cannot undo the command. Every other removal archives or " +
			"retires the entity, and you can restore it.\n\n",
	)
}

func writeGuardedWriteGroups(builder *strings.Builder, entries []writeEntry) {
	for _, group := range writeGroups(entries) {
		fmt.Fprintf(builder, "### %s\n\n", group)
		builder.WriteString("| Command | Description | Notes |\n| --- | --- | --- |\n")
		for _, entry := range entries {
			if writeGroup(entry) != group {
				continue
			}
			fmt.Fprintf(
				builder,
				"| `linctl %s` | %s | %s |\n",
				entry.info.Path,
				entry.info.Short,
				writeNotes(entry),
			)
		}
		builder.WriteString("\n")
	}
}

func writeOtherWriteSection(builder *strings.Builder, title string, intro string, entries []writeEntry) {
	if len(entries) == 0 {
		return
	}
	fmt.Fprintf(builder, "## %s\n\n%s\n\n", title, intro)
	builder.WriteString("| Command | Description |\n| --- | --- |\n")
	for _, entry := range entries {
		fmt.Fprintf(builder, "| `linctl %s` | %s |\n", entry.info.Path, entry.info.Short)
	}
	builder.WriteString("\n")
}

// writeGroups lists the command groups in render order: the bare top-level
// commands first, then every group in path order.
func writeGroups(entries []writeEntry) []string {
	seen := map[string]bool{}
	groups := make([]string, 0, len(entries))
	for _, entry := range entries {
		group := writeGroup(entry)
		if seen[group] {
			continue
		}
		seen[group] = true
		if group == topLevelGroup {
			groups = append([]string{group}, groups...)
			continue
		}
		groups = append(groups, group)
	}

	return groups
}

const topLevelGroup = "top level"

func writeGroup(entry writeEntry) string {
	fields := strings.Fields(entry.info.Path)
	if len(fields) < 2 {
		return topLevelGroup
	}

	return fields[0]
}

func writeNotes(entry writeEntry) string {
	notes := make([]string, 0, 2)
	if entry.orgWide {
		notes = append(notes, "org-wide")
	}
	if entry.info.Irreversible {
		notes = append(notes, "**irreversible**")
	}
	if len(notes) == 0 {
		return "—"
	}

	return strings.Join(notes, ", ")
}

func collectCommands(parent *cobra.Command, byPath map[string]*cobra.Command) {
	for _, command := range cli.SortedAvailableCommands(parent) {
		byPath[cli.CommandPath(command)] = command
		collectCommands(command, byPath)
	}
}

func writeCommandTree(builder *strings.Builder, parent *cobra.Command) {
	for _, command := range cli.SortedAvailableCommands(parent) {
		writeCommandEntry(builder, command)
		writeCommandTree(builder, command)
	}
}

func writeCommandEntry(builder *strings.Builder, command *cobra.Command) {
	fmt.Fprintf(builder, "### %s\n\n", command.CommandPath())
	if command.Short != "" {
		fmt.Fprintf(builder, "%s\n\n", command.Short)
	}
	fmt.Fprintf(builder, "```\n%s\n```\n\n", command.UseLine())
	if usages := strings.TrimRight(command.LocalNonPersistentFlags().FlagUsages(), "\n"); usages != "" {
		fmt.Fprintf(builder, "Flags:\n\n```\n%s\n```\n\n", usages)
	}
}
