//go:build ignore

// Command gen-skill renders the linctl agent command reference
// (skills/linctl/references/commands.md) from the cobra command tree.
//
// The curated skills/linctl/SKILL.md is hand-maintained and intentionally not a
// command dump; this generator produces the always-current full command
// inventory it links to. It is a standalone maintenance tool, excluded from the
// module build/vet/lint/test graph via the ignore build tag (and from
// scripts/go-packages.sh). Run it with `go run scripts/gen-skill.go` or
// `task gen-skill`. CI re-runs it and fails if the committed reference differs
// from the binary's command surface, so the agent-facing doc can never drift.
//
// The generator reads only the in-memory cobra command tree: no Linear API call,
// no token, no schema change.
package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/KyaniteHQ/linctl/internal/cli"
)

const outputPath = "skills/linctl/references/commands.md"

func main() {
	root := cli.NewRootCommand(context.Background(), cli.BuildInfo{})

	var builder strings.Builder
	writeHeader(&builder, root)
	writeCommandTree(&builder, root)

	content := strings.TrimRight(builder.String(), "\n") + "\n"
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "gen-skill:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(outputPath, []byte(content), 0o644); err != nil { //nolint:gosec // generated docs are world-readable
		fmt.Fprintln(os.Stderr, "gen-skill:", err)
		os.Exit(1)
	}
}

func writeHeader(builder *strings.Builder, root *cobra.Command) {
	fmt.Fprintf(builder, "# %s command reference\n\n", root.Name())
	fmt.Fprintf(builder, "%s\n\n", root.Short)
	builder.WriteString(
		"Generated by `scripts/gen-skill.go` from the linctl command tree. " +
			"Do not edit by hand; run `task gen-skill` to refresh it. This is the full " +
			"command inventory linked from `SKILL.md`.\n\n",
	)
	if usages := strings.TrimRight(root.PersistentFlags().FlagUsages(), "\n"); usages != "" {
		builder.WriteString("## Global flags\n\n```\n")
		builder.WriteString(usages)
		builder.WriteString("\n```\n\n")
	}
	builder.WriteString("## Commands\n\n")
}

func writeCommandTree(builder *strings.Builder, parent *cobra.Command) {
	for _, command := range sortedSubcommands(parent) {
		writeCommandEntry(builder, command)
		writeCommandTree(builder, command)
	}
}

func sortedSubcommands(parent *cobra.Command) []*cobra.Command {
	commands := make([]*cobra.Command, 0, len(parent.Commands()))
	for _, command := range parent.Commands() {
		if !command.IsAvailableCommand() || command.Name() == "help" || command.Name() == "completion" {
			continue
		}
		commands = append(commands, command)
	}
	sort.Slice(commands, func(left int, right int) bool {
		return commands[left].CommandPath() < commands[right].CommandPath()
	})

	return commands
}

func writeCommandEntry(builder *strings.Builder, command *cobra.Command) {
	fmt.Fprintf(builder, "### %s\n\n", command.CommandPath())
	if command.Short != "" {
		fmt.Fprintf(builder, "%s\n\n", command.Short)
	}
	fmt.Fprintf(builder, "```\n%s\n```\n\n", command.UseLine())
	if usages := strings.TrimRight(command.LocalNonPersistentFlags().FlagUsages(), "\n"); usages != "" {
		fmt.Fprintf(builder, "Flags:\n\n```\n%s\n```\n\n", usages)
	}
}
